### ISSUE TITLE
ShardingSphere Examples for upcoming release 5.0.0-beta

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10455]
Hi community,

I know you are expecting the new release coming. The next release does not include many wonderful features but becomes more stable, and reliable. Please keep your keen here.

This issue is around examples for the incoming release. Currently, @RaigorJiang is taking charge. After this issue is closed, the next release will be closer to us.

**Comment by RaigorJiang** [comment]
Thanks @tristaZero 
The changes are being sorted out, and the detailed task list will be updated later.

**Comment by RaigorJiang** [comment]
Hi community,

Due to the changes of the configuration format, we need to check whether the configuration of the following modules is correct (synchronized with the master branch), and run tests to verify the correctness of each function.

Note: There are adjustments to authority, db discovery and readwrting splitiing in the recent commits, and may also contain other changes, which need to be carefully checked.

### Task List

- [ ] shardingsphere-jdbc-example
  - [ ] sharding-example
     - sharding-raw-jdbc-example
     - sharding-spring-boot-jpa-example
     - sharding-spring-boot-mybatis-example
     - sharding-spring-namespace-jpa-example
     - sharding-spring-namespace-mybatis-example
  - [ ] governance-example
    - governance-raw-jdbc-example
    - governance-spring-boot-example
    - governance-spring-namespace-example
  - [ ] transaction-example
    - transaction-2pc-xa-raw-jdbc-example
    - transaction-2pc-xa-bitronix-raw-jdbc-example
    - transaction-2pc-xa-narayana-raw-jdbc-example
    - transaction-2pc-xa-spring-boot-example
    - transaction-2pc-xa-spring-namespace-example
    - transaction-base-seata-raw-jdbc-example
    - transaction-base-seata-spring-boot-example
  - [ ]     other-feature-example
    - [ ]     encrypt-example
      - encrypt-raw-jdbc-example
      - encrypt-spring-boot-example
      - encrypt-spring-namespace-example
    - [ ]     hint-example
      - hint-raw-jdbc-example
    - [ ]     shadow-example
      - shadow-raw-jdbc-example
      - shadow-spring-boot-example
      - shadow-spring-namespace-example
- [ ] shardingsphere-proxy-example
  - shardingsphere-proxy-boot-mybatis-example
  - shardingsphere-proxy-hint-example


If someone is interested in the above tasks, you can comment here, but each task is time-limited and needs to be completed within 4 days

**Comment by totalo** [comment]
hi can try to finish sharding-example task?

**Comment by RaigorJiang** [comment]
Hi @totalo 
Of course, it’s great that you can help.
Now I will mark the task to you.

**Comment by totalo** [comment]
> Hi @totalo
> Of course, it’s great that you can help.
> Now I will mark the task to you.

thx

**Comment by tristaZero** [comment]
@RaigorJiang Clear enough.
@totalo Hey, thanks for your hand with inc release.

**Comment by tristaZero** [comment]
Hi @zjcnb 
Are you interested in this one? We can move it forward together.

**Comment by zjcnb** [comment]
> Hi @zjcnb
> Are you interested in this one? We can move it forward together.

Yes, of course. I'm interested, i can try to finish  encrypt-example and  hint-example task

**Comment by RaigorJiang** [comment]
@zjcnb Thanks

**Comment by tristaZero** [comment]
Hi @MingxingLAI 
I am curious whether you'd like to be part of this task?

**Comment by totalo** [comment]
#10504 @RaigorJiang @tristaZero hi ,This is the result of my test. Next I will try to find the cause of the error and try to fix it.

**Comment by RaigorJiang** [comment]
@totalo  OK, thanks

**Comment by zjcnb** [comment]
> @zjcnb Thanks

#10543  This is my test report. I have a problem that needs to be discussed.

**Comment by RaigorJiang** [comment]
@tristaZero @totalo @zjcnb 
Hi everyone, the inspection and testing of `shardingsphere-example` module have been completed，thanks for your help.

**Comment by tristaZero** [comment]
Hi @RaigorJiang @zjcnb @totalo Your nice work definitely brings our upcoming release closer!

Did we find any bugs or issues during your tests? Suppose they show up, we can create issues and mention them here to help we thread them later on.

**Comment by zjcnb** [comment]
> Hi @RaigorJiang @zjcnb @totalo Your nice work definitely brings our upcoming release closer!
> 
> Did we find any bugs or issues during your tests? Suppose they show up, we can create issues and mention them here to help us thread them later on.

#10577  Yeah, I have a problem that needs to be discussed

**Comment by totalo** [comment]
> Hi @RaigorJiang @zjcnb @totalo Your nice work definitely brings our upcoming release closer!
> 
> Did we find any bugs or issues during your tests? Suppose they show up, we can create issues and mention them here to help us thread them later on.

#10584  and #10583 i found two problem.

**Comment by MingxingLAI** [comment]
@tristaZero Sorry, it’s too late to see the news, It looks like the problem has been solved. So, I will try to fix more bugs in the future.

**Comment by tristaZero** [comment]
Hi guys, your efforts are a major boost for the upcoming release, thanks. ;-)
