### ISSUE TITLE
Add more metrics for proxy

### ISSUE THREAD

**Issue by dachuan9e** [apache/shardingsphere#11444]
# Introduction
   Will add the following metrics for proxy.  It needs to change both the proxy and agent. 

# Tasks
+ proxy service status.
     + [x] proxy uptime （DistSQL + Metrics）
     + [x] proxy state      （DistSQL + Metrics）
+ more type of SQL
     - [x] DML INSERT
     - [x]  DML DELETE
     - [x]  DML UPDATE
     - [x]  DML SELECT
     - [x]  DDLStatement
     - [x]  DCLStatement
     - [x]  DALStatement
     - [x]  TCLStatement
     - [x]  RQLStatement(DistSQL)
     - [x]  RDLStatement(DistSQL)
     - [x]  RALStatement(DistSQL)
+ transfer bytes of proxy
    - [x] request bytes
    - [x] response bytes
+ exception statistics
    - [x] request error number
+ meta statistics (DistSQL + Metrics) 
    - [x] schema number
    - [x] database number (it represents the actual database used by proxy. R-W split seen as 1. The same database in different data source is seen as 1.)

**Comment by dachuan9e** [comment]
Adding request error number by recording the exceptions happened in "org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask"

**Comment by taojintianxia** [comment]
fantastic !

**Comment by dachuan9e** [comment]
Add proxy state, uptime and sql metrics

**Comment by menghaoranss** [comment]
Completed.
