### ISSUE TITLE
Tasks in the federate optimizer.

### ISSUE THREAD

**Issue by wgy8283335** [apache/shardingsphere#12709]
## Tasks in the federate optimizer

- [x] Integration between Calcite optimization and ShardingSphere infra.
- [x] Add the filter push-down rule in the hep planner and related unit test.
- [x] Add sub-query in sqlNodeConvertEngine and unit tests for sub-query rules.
- [ ] Add metadata query for volcano planner and related unit test.
- [ ] Recheck the rule and test, make sure that the rule list and test result are reasonable.
- [ ] Add unit tests for other rules. 
- [ ] Resolve some hard cases:
  - [ ]  ISSUE 12894

**Comment by strongduanmu** [comment]
@wgy8283335 It looks great, and I want to participate together.

**Comment by wgy8283335** [comment]
@strongduanmu  Greate!
SqlNodeConvertEngine.convert() parse SQL with subquery correctly. # 12581
This issue could be related to `Add sub-query in sqlNodeConvertEngine and unit tests for sub-query rules.`

**Comment by strongduanmu** [comment]
> @strongduanmu Greate!
> SqlNodeConvertEngine.convert() parse SQL with subquery correctly. # 12581
> This issue could be related to task `Add sub-query in sqlNodeConvertEngine and unit tests for sub-query rules.`

@wgy8283335 I will support subquery convert today.

**Comment by TeslaCN** [comment]
Hi @wgy8283335 
Any update here? Could we finish this in 5.1.1?

**Comment by wgy8283335** [comment]
> Hi @wgy8283335 Any update here? Could we finish this in 5.1.1?

Not yet, maybe this issue should be delayed to the next version.

**Comment by TeslaCN** [comment]
> Not yet, maybe this issue should be delayed to the next version.

OK
