### ISSUE TITLE
support parse Function to a segment

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#13314]
Currently, if we have this sql
```
select date(creation_date) from t_order_item;
```
When we parse this sql, we only get this statement infomation
![image](https://user-images.githubusercontent.com/86938616/139038036-7bafcc10-8dc5-4762-8699-83159d958d63.png)
These are not enough. Refer to this #12973
So, I want to parse function as segment.
I'll create a FunctionSegment which can parse a function in sql. Like this.
```
/**
 * Function segment.
 */
@RequiredArgsConstructor
@Getter
public final class FunctionSegment implements ComplexExpressionSegment {
    
    private final int startIndex;
    
    private final int stopIndex;
    
    private final String methodName;
    
    private final Collection<ExpressionSegment> parameters = new LinkedList<>();
    
    private final String text;
    
}
```
In addition, there are currently some problems with the usage of `ExpressionProjectionSegment`.
`ExpressionProjectionSegment` should be used in just projection, but it occurs in `whereSegment` or `group by` and so on.
I plan to replace `ExpressionProjectionSegment` with right segment in the part of sql exclude projection.

## TASKS

- [x] parse mysql regular function
- [x] parse mysql special function
- [x] replace `ExpressionProjectionSegment` with right segment.
- [x] parse postgresql function
- [x] implement other dialect
