### ISSUE TITLE
[Proofread SQL Definition][PostgreSQL]Proofread the g4 files of SQL definitions

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#14104]
Hi community,

This issue is to proofread the SQL definitions of PostgreSQL. Therefore, we can support parsing more SQLs.
We need your interaction! If you

>Be familiar with g4 file of Antlr (The grammars are RegularExpression-like)
Understand the Oracle grammars 

then welcome!

#### How is a SQL parsed?
`SQL definition file`
->(Parse to)
`AST`
->(Visit it)
`SQLStatment`

### Process
Compare SQL definitions in [Oficial SQL Doc](https://www.postgresql.org/docs/14/sql-commands.html) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4/imports/postgresql)
If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc
You can also refer to [PostgreSql source code](https://github.com/postgres/postgres/blob/master/src/backend/parser/gram.y)
Run mvn install the current_file_module
Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class)
Add new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/sql/supported) and expected parsed result in[ Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-parser-test/src/main/resources/case)
Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) to make sure no exceptions.
### Notice
- Left recursion can not work well in Antlr4,
```
a
  : b
  | a b
  ;
b
  : a c
  ;
c
  : ...
  ;
```
- you can consider the following one,
```
a
  : b*
  ;
b
  : a c
  ;
c
  : ...
  ;
```
[Here](https://shimo.im/docs/WrgrCt9JR3JDjq8H/read) is a Chinese version for reference.
### subtask
 - [ ] [ABORT — abort the current transaction](https://www.postgresql.org/docs/14/sql-abort.html)
- [ ] [ALTER AGGREGATE — change the definition of an aggregate function]( https://www.postgresql.org/docs/14/sql-alteraggregate.html)
- [ ] [ALTER COLLATION — change the definition of a collation]( https://www.postgresql.org/docs/14/sql-altercollation.html)
- [ ] [ALTER CONVERSION — change the definition of a conversion]( https://www.postgresql.org/docs/14/sql-alterconversion.html)
- [ ] [ALTER DATABASE — change a database]( https://www.postgresql.org/docs/14/sql-alterdatabase.html)
- [ ] [ALTER DEFAULT PRIVILEGES — define default access privileges]( https://www.postgresql.org/docs/14/sql-alterdefaultprivileges.html)
- [ ] [ALTER DOMAIN — change the definition of a domain]( https://www.postgresql.org/docs/14/sql-alterdomain.html)
- [ ] [ALTER EVENT TRIGGER — change the definition of an event trigger]( https://www.postgresql.org/docs/14/sql-altereventtrigger.html)
- [ ] [ALTER EXTENSION — change the definition of an extension]( https://www.postgresql.org/docs/14/sql-alterextension.html)
- [ ] [ALTER FOREIGN DATA WRAPPER — change the definition of a foreign-data wrapper]( https://www.postgresql.org/docs/14/sql-alterforeigndatawrapper.html)
- [ ] [ALTER FOREIGN TABLE — change the definition of a foreign table]( https://www.postgresql.org/docs/14/sql-alterforeigntable.html)
- [ ] [ALTER FUNCTION — change the definition of a function]( https://www.postgresql.org/docs/14/sql-alterfunction.html)
- [ ] [ALTER GROUP — change role name or membership]( https://www.postgresql.org/docs/14/sql-altergroup.html)
- [ ] [ALTER INDEX — change the definition of an index]( https://www.postgresql.org/docs/14/sql-alterindex.html)
- [ ] [ALTER LANGUAGE — change the definition of a procedural language]( https://www.postgresql.org/docs/14/sql-alterlanguage.html)
- [ ] [ALTER LARGE OBJECT — change the definition of a large object]( https://www.postgresql.org/docs/14/sql-alterlargeobject.html)
- [ ] [ALTER MATERIALIZED VIEW — change the definition of a materialized view]( https://www.postgresql.org/docs/14/sql-altermaterializedview.html)
- [ ] [ALTER OPERATOR — change the definition of an operator]( https://www.postgresql.org/docs/14/sql-alteroperator.html)
- [ ] [ALTER OPERATOR CLASS — change the definition of an operator class]( https://www.postgresql.org/docs/14/sql-alteropclass.html)
- [ ] [ALTER OPERATOR FAMILY — change the definition of an operator family]( https://www.postgresql.org/docs/14/sql-alteropfamily.html)
- [ ] [ALTER POLICY — change the definition of a row-level security policy]( https://www.postgresql.org/docs/14/sql-alterpolicy.html)
- [ ] [ALTER PROCEDURE — change the definition of a procedure]( https://www.postgresql.org/docs/14/sql-alterprocedure.html)
- [ ] [ALTER PUBLICATION — change the definition of a publication]( https://www.postgresql.org/docs/14/sql-alterpublication.html)
- [ ] [ALTER ROLE — change a database role]( https://www.postgresql.org/docs/14/sql-alterrole.html)
- [ ] [ALTER ROUTINE — change the definition of a routine]( https://www.postgresql.org/docs/14/sql-alterroutine.html)
- [ ] [ALTER RULE — change the definition of a rule]( https://www.postgresql.org/docs/14/sql-alterrule.html)
- [ ] [ALTER SCHEMA — change the definition of a schema]( https://www.postgresql.org/docs/14/sql-alterschema.html)
- [ ] [ALTER SEQUENCE — change the definition of a sequence generator]( https://www.postgresql.org/docs/14/sql-altersequence.html)
- [ ] [ALTER SERVER — change the definition of a foreign server]( https://www.postgresql.org/docs/14/sql-alterserver.html)
- [ ] [ALTER STATISTICS — change the definition of an extended statistics object]( https://www.postgresql.org/docs/14/sql-alterstatistics.html)
- [ ] [ALTER SUBSCRIPTION — change the definition of a subscription]( https://www.postgresql.org/docs/14/sql-altersubscription.html)
- [ ] [ALTER SYSTEM — change a server configuration parameter]( https://www.postgresql.org/docs/14/sql-altersystem.html)
- [ ] [ALTER TABLE — change the definition of a table]( https://www.postgresql.org/docs/14/sql-altertable.html)
- [ ] [ALTER TABLESPACE — change the definition of a tablespace]( https://www.postgresql.org/docs/14/sql-altertablespace.html)
- [ ] [ALTER TEXT SEARCH CONFIGURATION — change the definition of a text search configuration]( https://www.postgresql.org/docs/14/sql-altertsconfig.html)
- [ ] [ALTER TEXT SEARCH DICTIONARY — change the definition of a text search dictionary]( https://www.postgresql.org/docs/14/sql-altertsdictionary.html)
- [ ] [ALTER TEXT SEARCH PARSER — change the definition of a text search parser]( https://www.postgresql.org/docs/14/sql-altertsparser.html)
- [ ] [ALTER TEXT SEARCH TEMPLATE — change the definition of a text search template]( https://www.postgresql.org/docs/14/sql-altertstemplate.html)
- [ ] [ALTER TRIGGER — change the definition of a trigger]( https://www.postgresql.org/docs/14/sql-altertrigger.html)
- [ ] [ALTER TYPE — change the definition of a type]( https://www.postgresql.org/docs/14/sql-altertype.html)
- [ ] [ALTER USER — change a database role]( https://www.postgresql.org/docs/14/sql-alteruser.html)
- [ ] [ALTER USER MAPPING — change the definition of a user mapping]( https://www.postgresql.org/docs/14/sql-alterusermapping.html)
- [ ] [ALTER VIEW — change the definition of a view]( https://www.postgresql.org/docs/14/sql-alterview.html)
- [ ] [ANALYZE — collect statistics about a database]( https://www.postgresql.org/docs/14/sql-analyze.html)
- [ ] [BEGIN — start a transaction block]( https://www.postgresql.org/docs/14/sql-begin.html)
- [ ] [CALL — invoke a procedure]( https://www.postgresql.org/docs/14/sql-call.html)
- [ ] [CHECKPOINT — force a write-ahead log checkpoint]( https://www.postgresql.org/docs/14/sql-checkpoint.html)
- [ ] [CLOSE — close a cursor]( https://www.postgresql.org/docs/14/sql-close.html)
- [ ] [CLUSTER — cluster a table according to an index]( https://www.postgresql.org/docs/14/sql-cluster.html)
- [ ] [COMMENT — define or change the comment of an object]( https://www.postgresql.org/docs/14/sql-comment.html)
- [ ] [COMMIT — commit the current transaction]( https://www.postgresql.org/docs/14/sql-commit.html)
- [ ] [COMMIT PREPARED — commit a transaction that was earlier prepared for two-phase commit]( https://www.postgresql.org/docs/14/sql-commit-prepared.html)
- [ ] [COPY — copy data between a file and a table]( https://www.postgresql.org/docs/14/sql-copy.html)
- [ ] [CREATE ACCESS METHOD — define a new access method]( https://www.postgresql.org/docs/14/sql-create-access-method.html)
- [ ] [CREATE AGGREGATE — define a new aggregate function]( https://www.postgresql.org/docs/14/sql-createaggregate.html)
- [ ] [CREATE CAST — define a new cast]( https://www.postgresql.org/docs/14/sql-createcast.html)
- [ ] [CREATE COLLATION — define a new collation]( https://www.postgresql.org/docs/14/sql-createcollation.html)
- [ ] [CREATE CONVERSION — define a new encoding conversion]( https://www.postgresql.org/docs/14/sql-createconversion.html)
- [ ] [CREATE DATABASE — create a new database]( https://www.postgresql.org/docs/14/sql-createdatabase.html)
- [ ] [CREATE DOMAIN — define a new domain]( https://www.postgresql.org/docs/14/sql-createdomain.html)
- [ ] [CREATE EVENT TRIGGER — define a new event trigger]( https://www.postgresql.org/docs/14/sql-createeventtrigger.html)
- [ ] [CREATE EXTENSION — install an extension]( https://www.postgresql.org/docs/14/sql-createextension.html)
- [ ] [CREATE FOREIGN DATA WRAPPER — define a new foreign-data wrapper]( https://www.postgresql.org/docs/14/sql-createforeigndatawrapper.html)
- [ ] [CREATE FOREIGN TABLE — define a new foreign table]( https://www.postgresql.org/docs/14/sql-createforeigntable.html)
- [ ] [CREATE FUNCTION — define a new function]( https://www.postgresql.org/docs/14/sql-createfunction.html)
- [ ] [CREATE GROUP — define a new database role]( https://www.postgresql.org/docs/14/sql-creategroup.html)
- [ ] [CREATE INDEX — define a new index]( https://www.postgresql.org/docs/14/sql-createindex.html)
- [ ] [CREATE LANGUAGE — define a new procedural language]( https://www.postgresql.org/docs/14/sql-createlanguage.html)
- [ ] [CREATE MATERIALIZED VIEW — define a new materialized view]( https://www.postgresql.org/docs/14/sql-creatematerializedview.html)
- [ ] [CREATE OPERATOR — define a new operator]( https://www.postgresql.org/docs/14/sql-createoperator.html)
- [ ] [CREATE OPERATOR CLASS — define a new operator class]( https://www.postgresql.org/docs/14/sql-createopclass.html)
- [ ] [CREATE OPERATOR FAMILY — define a new operator family]( https://www.postgresql.org/docs/14/sql-createopfamily.html)
- [ ] [CREATE POLICY — define a new row-level security policy for a table]( https://www.postgresql.org/docs/14/sql-createpolicy.html)
- [ ] [CREATE PROCEDURE — define a new procedure]( https://www.postgresql.org/docs/14/sql-createprocedure.html)
- [ ] [CREATE PUBLICATION — define a new publication]( https://www.postgresql.org/docs/14/sql-createpublication.html)
- [ ] [CREATE ROLE — define a new database role]( https://www.postgresql.org/docs/14/sql-createrole.html)
- [ ] [CREATE RULE — define a new rewrite rule]( https://www.postgresql.org/docs/14/sql-createrule.html)
- [ ] [CREATE SCHEMA — define a new schema]( https://www.postgresql.org/docs/14/sql-createschema.html)
- [ ] [CREATE SEQUENCE — define a new sequence generator]( https://www.postgresql.org/docs/14/sql-createsequence.html)
- [ ] [CREATE SERVER — define a new foreign server]( https://www.postgresql.org/docs/14/sql-createserver.html)
- [ ] [CREATE STATISTICS — define extended statistics]( https://www.postgresql.org/docs/14/sql-createstatistics.html)
- [ ] [CREATE SUBSCRIPTION — define a new subscription]( https://www.postgresql.org/docs/14/sql-createsubscription.html)
- [ ] [CREATE TABLE — define a new table]( https://www.postgresql.org/docs/14/sql-createtable.html)
- [ ] [CREATE TABLE AS — define a new table from the results of a query]( https://www.postgresql.org/docs/14/sql-createtableas.html)
- [ ] [CREATE TABLESPACE — define a new tablespace]( https://www.postgresql.org/docs/14/sql-createtablespace.html)
- [ ] [CREATE TEXT SEARCH CONFIGURATION — define a new text search configuration]( https://www.postgresql.org/docs/14/sql-createtsconfig.html)
- [ ] [CREATE TEXT SEARCH DICTIONARY — define a new text search dictionary]( https://www.postgresql.org/docs/14/sql-createtsdictionary.html)
- [ ] [CREATE TEXT SEARCH PARSER — define a new text search parser]( https://www.postgresql.org/docs/14/sql-createtsparser.html)
- [ ] [CREATE TEXT SEARCH TEMPLATE — define a new text search template]( https://www.postgresql.org/docs/14/sql-createtstemplate.html)
- [ ] [CREATE TRANSFORM — define a new transform]( https://www.postgresql.org/docs/14/sql-createtransform.html)
- [ ] [CREATE TRIGGER — define a new trigger]( https://www.postgresql.org/docs/14/sql-createtrigger.html)
- [ ] [CREATE TYPE — define a new data type]( https://www.postgresql.org/docs/14/sql-createtype.html)
- [ ] [CREATE USER — define a new database role]( https://www.postgresql.org/docs/14/sql-createuser.html)
- [ ] [CREATE USER MAPPING — define a new mapping of a user to a foreign server]( https://www.postgresql.org/docs/14/sql-createusermapping.html)
- [ ] [CREATE VIEW — define a new view]( https://www.postgresql.org/docs/14/sql-createview.html)
- [ ] [DEALLOCATE — deallocate a prepared statement]( https://www.postgresql.org/docs/14/sql-deallocate.html)
- [ ] [DECLARE — define a cursor]( https://www.postgresql.org/docs/14/sql-declare.html)
- [ ] [DELETE — delete rows of a table]( https://www.postgresql.org/docs/14/sql-delete.html)
- [ ] [DISCARD — discard session state]( https://www.postgresql.org/docs/14/sql-discard.html)
- [ ] [DO — execute an anonymous code block]( https://www.postgresql.org/docs/14/sql-do.html)
- [ ] [DROP ACCESS METHOD — remove an access method]( https://www.postgresql.org/docs/14/sql-drop-access-method.html)
- [ ] [DROP AGGREGATE — remove an aggregate function]( https://www.postgresql.org/docs/14/sql-dropaggregate.html)
- [ ] [DROP CAST — remove a cast]( https://www.postgresql.org/docs/14/sql-dropcast.html)
- [ ] [DROP COLLATION — remove a collation]( https://www.postgresql.org/docs/14/sql-dropcollation.html)
- [ ] [DROP CONVERSION — remove a conversion]( https://www.postgresql.org/docs/14/sql-dropconversion.html)
- [ ] [DROP DATABASE — remove a database]( https://www.postgresql.org/docs/14/sql-dropdatabase.html)
- [ ] [DROP DOMAIN — remove a domain]( https://www.postgresql.org/docs/14/sql-dropdomain.html)
- [ ] [DROP EVENT TRIGGER — remove an event trigger]( https://www.postgresql.org/docs/14/sql-dropeventtrigger.html)
- [ ] [DROP EXTENSION — remove an extension]( https://www.postgresql.org/docs/14/sql-dropextension.html)
- [ ] [DROP FOREIGN DATA WRAPPER — remove a foreign-data wrapper]( https://www.postgresql.org/docs/14/sql-dropforeigndatawrapper.html)
- [ ] [DROP FOREIGN TABLE — remove a foreign table]( https://www.postgresql.org/docs/14/sql-dropforeigntable.html)
- [ ] [DROP FUNCTION — remove a function]( https://www.postgresql.org/docs/14/sql-dropfunction.html)
- [ ] [DROP GROUP — remove a database role]( https://www.postgresql.org/docs/14/sql-dropgroup.html)
- [ ] [DROP INDEX — remove an index]( https://www.postgresql.org/docs/14/sql-dropindex.html)
- [ ] [DROP LANGUAGE — remove a procedural language]( https://www.postgresql.org/docs/14/sql-droplanguage.html)
- [ ] [DROP MATERIALIZED VIEW — remove a materialized view]( https://www.postgresql.org/docs/14/sql-dropmaterializedview.html)
- [ ] [DROP OPERATOR — remove an operator]( https://www.postgresql.org/docs/14/sql-dropoperator.html)
- [ ] [DROP OPERATOR CLASS — remove an operator class]( https://www.postgresql.org/docs/14/sql-dropopclass.html)
- [ ] [DROP OPERATOR FAMILY — remove an operator family]( https://www.postgresql.org/docs/14/sql-dropopfamily.html)
- [ ] [DROP OWNED — remove database objects owned by a database role]( https://www.postgresql.org/docs/14/sql-drop-owned.html)
- [ ] [DROP POLICY — remove a row-level security policy from a table]( https://www.postgresql.org/docs/14/sql-droppolicy.html)
- [ ] [DROP PROCEDURE — remove a procedure]( https://www.postgresql.org/docs/14/sql-dropprocedure.html)
- [ ] [DROP PUBLICATION — remove a publication]( https://www.postgresql.org/docs/14/sql-droppublication.html)
- [ ] [DROP ROLE — remove a database role]( https://www.postgresql.org/docs/14/sql-droprole.html)
- [ ] [DROP ROUTINE — remove a routine]( https://www.postgresql.org/docs/14/sql-droproutine.html)
- [ ] [DROP RULE — remove a rewrite rule]( https://www.postgresql.org/docs/14/sql-droprule.html)
- [ ] [DROP SCHEMA — remove a schema]( https://www.postgresql.org/docs/14/sql-dropschema.html)
- [ ] [DROP SEQUENCE — remove a sequence]( https://www.postgresql.org/docs/14/sql-dropsequence.html)
- [ ] [DROP SERVER — remove a foreign server descriptor]( https://www.postgresql.org/docs/14/sql-dropserver.html)
- [ ] [DROP STATISTICS — remove extended statistics]( https://www.postgresql.org/docs/14/sql-dropstatistics.html)
- [ ] [DROP SUBSCRIPTION — remove a subscription]( https://www.postgresql.org/docs/14/sql-dropsubscription.html)
- [ ] [DROP TABLE — remove a table]( https://www.postgresql.org/docs/14/sql-droptable.html)
- [ ] [DROP TABLESPACE — remove a tablespace]( https://www.postgresql.org/docs/14/sql-droptablespace.html)
- [ ] [DROP TEXT SEARCH CONFIGURATION — remove a text search configuration]( https://www.postgresql.org/docs/14/sql-droptsconfig.html)
- [ ] [DROP TEXT SEARCH DICTIONARY — remove a text search dictionary]( https://www.postgresql.org/docs/14/sql-droptsdictionary.html)
- [ ] [DROP TEXT SEARCH PARSER — remove a text search parser]( https://www.postgresql.org/docs/14/sql-droptsparser.html)
- [ ] [DROP TEXT SEARCH TEMPLATE — remove a text search template]( https://www.postgresql.org/docs/14/sql-droptstemplate.html)
- [ ] [DROP TRANSFORM — remove a transform]( https://www.postgresql.org/docs/14/sql-droptransform.html)
- [ ] [DROP TRIGGER — remove a trigger]( https://www.postgresql.org/docs/14/sql-droptrigger.html)
- [ ] [DROP TYPE — remove a data type]( https://www.postgresql.org/docs/14/sql-droptype.html)
- [ ] [DROP USER — remove a database role]( https://www.postgresql.org/docs/14/sql-dropuser.html)
- [ ] [DROP USER MAPPING — remove a user mapping for a foreign server]( https://www.postgresql.org/docs/14/sql-dropusermapping.html)
- [ ] [DROP VIEW — remove a view]( https://www.postgresql.org/docs/14/sql-dropview.html)
- [ ] [END — commit the current transaction]( https://www.postgresql.org/docs/14/sql-end.html)
- [ ] [EXECUTE — execute a prepared statement]( https://www.postgresql.org/docs/14/sql-execute.html)
- [ ] [EXPLAIN — show the execution plan of a statement]( https://www.postgresql.org/docs/14/sql-explain.html)
- [ ] [FETCH — retrieve rows from a query using a cursor]( https://www.postgresql.org/docs/14/sql-fetch.html)
- [ ] [GRANT — define access privileges]( https://www.postgresql.org/docs/14/sql-grant.html)
- [ ] [IMPORT FOREIGN SCHEMA — import table definitions from a foreign server]( https://www.postgresql.org/docs/14/sql-importforeignschema.html)
- [ ] [INSERT — create new rows in a table]( https://www.postgresql.org/docs/14/sql-insert.html)
- [ ] [LISTEN — listen for a notification]( https://www.postgresql.org/docs/14/sql-listen.html)
- [ ] [LOAD — load a shared library file]( https://www.postgresql.org/docs/14/sql-load.html)
- [ ] [LOCK — lock a table]( https://www.postgresql.org/docs/14/sql-lock.html)
- [ ] [MOVE — position a cursor]( https://www.postgresql.org/docs/14/sql-move.html)
- [ ] [NOTIFY — generate a notification]( https://www.postgresql.org/docs/14/sql-notify.html)
- [ ] [PREPARE — prepare a statement for execution]( https://www.postgresql.org/docs/14/sql-prepare.html)
- [ ] [PREPARE TRANSACTION — prepare the current transaction for two-phase commit]( https://www.postgresql.org/docs/14/sql-prepare-transaction.html)
- [ ] [REASSIGN OWNED — change the ownership of database objects owned by a database role]( https://www.postgresql.org/docs/14/sql-reassign-owned.html)
- [ ] [REFRESH MATERIALIZED VIEW — replace the contents of a materialized view]( https://www.postgresql.org/docs/14/sql-refreshmaterializedview.html)
- [ ] [REINDEX — rebuild indexes]( https://www.postgresql.org/docs/14/sql-reindex.html)
- [ ] [RELEASE SAVEPOINT — destroy a previously defined savepoint]( https://www.postgresql.org/docs/14/sql-release-savepoint.html)
- [ ] [RESET — restore the value of a run-time parameter to the default value]( https://www.postgresql.org/docs/14/sql-reset.html)
- [ ] [REVOKE — remove access privileges]( https://www.postgresql.org/docs/14/sql-revoke.html)
- [ ] [ROLLBACK — abort the current transaction]( https://www.postgresql.org/docs/14/sql-rollback.html)
- [ ] [ROLLBACK PREPARED — cancel a transaction that was earlier prepared for two-phase commit]( https://www.postgresql.org/docs/14/sql-rollback-prepared.html)
- [ ] [ROLLBACK TO SAVEPOINT — roll back to a savepoint]( https://www.postgresql.org/docs/14/sql-rollback-to.html)
- [ ] [SAVEPOINT — define a new savepoint within the current transaction]( https://www.postgresql.org/docs/14/sql-savepoint.html)
- [ ] [SECURITY LABEL — define or change a security label applied to an object]( https://www.postgresql.org/docs/14/sql-security-label.html)
- [ ] [SELECT — retrieve rows from a table or view]( https://www.postgresql.org/docs/14/sql-select.html)
- [ ] [SELECT INTO — define a new table from the results of a query]( https://www.postgresql.org/docs/14/sql-selectinto.html)
- [ ] [SET — change a run-time parameter]( https://www.postgresql.org/docs/14/sql-set.html)
- [ ] [SET CONSTRAINTS — set constraint check timing for the current transaction]( https://www.postgresql.org/docs/14/sql-set-constraints.html)
- [ ] [SET ROLE — set the current user identifier of the current session]( https://www.postgresql.org/docs/14/sql-set-role.html)
- [ ] [SET SESSION AUTHORIZATION — set the session user identifier and the current user identifier of the current session]( https://www.postgresql.org/docs/14/sql-set-session-authorization.html)
- [ ] [SET TRANSACTION — set the characteristics of the current transaction]( https://www.postgresql.org/docs/14/sql-set-transaction.html)
- [ ] [SHOW — show the value of a run-time parameter]( https://www.postgresql.org/docs/14/sql-show.html)
- [ ] [START TRANSACTION — start a transaction block]( https://www.postgresql.org/docs/14/sql-start-transaction.html)
- [ ] [TRUNCATE — empty a table or set of tables]( https://www.postgresql.org/docs/14/sql-truncate.html)
- [ ] [UNLISTEN — stop listening for a notification]( https://www.postgresql.org/docs/14/sql-unlisten.html)
- [ ] [UPDATE — update rows of a table]( https://www.postgresql.org/docs/14/sql-update.html)
- [ ] [VACUUM — garbage-collect and optionally analyze a database]( https://www.postgresql.org/docs/14/sql-vacuum.html)
- [ ] [VALUES — compute a set of rows]( https://www.postgresql.org/docs/14/sql-values.html)

**Comment by strongduanmu** [comment]
This issue has not been finished, so I will reopen it.

**Comment by strongduanmu** [comment]
Since this issue is too big, we will split it into new issues, so I will close it.
