### ISSUE TITLE
support encrypt config column data type

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#14987]
## Background
Currently, if we create a encrypt table like this
```
mysql> PREVIEW CREATE TABLE `t_encrypt` (`id` int(11) DEFAULT NULL, `user_id` varchar(100) DEFAULT NULL, `order_id` varchar(100) DEFAULT NULL) ENGINE=InnoDB;
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| data_source_name | sql                                                                                                                                                                                     |
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ds_0             | CREATE TABLE `t_encrypt` (`id` int(11) DEFAULT NULL, user_cipher varchar(100) DEFAULT NULL, user_plain varchar(100) DEFAULT NULL, order_cipher varchar(100) DEFAULT NULL) ENGINE=InnoDB |
+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
The cipher column's data type and length is same with the logic column.
But encrypt column will have some difference with logic column.
So, we think we need to add config for this.
## Task
- [x] Mete Data load encrypt table with config logic column data type
- [x] EncryptCreateTableTokenGenerator、EncryptAlterTableTokenGenerator support create token by config
- [x] DistSQL support creating encrypt rule with config

**Comment by lanchengx** [comment]
@tuichenchuxin DistSQL has been completed, can this issue be closed?

**Comment by tuichenchuxin** [comment]
@lanchengx Yes, I'll close it.
