### ISSUE TITLE
New syntax to support batch execution of DistSQL

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#15113]
## background

We can use DistSQL to create/drop/alter ... data sources and rules since 5.x, and these changes are effective immediately, so ShardingSphere has to refresh the meta data for each execution. In registry center, the configurations persisted in single node just as follows, once modified, they will be overwritten and there's no way to rollback.

```
namespace:
    metadata:
        sharding_db:
            dataSources
            rules
            tables
```

There are some problems for batch execution scenarios of DistSQL:

1. Batch execution  scenario involves frequent metadata refresh, which will greatly affect the performance, and without the support of distributed locks, the metadata may be incorrect
2. It is not friendly to scaling scenario. At present, modifying the configuration directly triggers the scaling task, batch execution will trigger scaling task frequently
3. Execution cannot be terminated

## design

Consider designing a new syntax to support delayed entry into force for  batch execution of DistSQL, the snapshot configuration will be persisted to registry center until apply it.

1. `PREPARE DISTSQL; `

Start a new version control for DistSQL, any DistSQL executed after this statement will not take effect immediately. If non-DistSQL is executed at this time, an exception will be thrown directly.

2. `APPLY DISTSQL; `

Apply all executed DistSQL and refresh meta data now.

3. `DISCARD DISTSQL; `

Discard all executed DistSQL before applying.

## task list

- [ ] support `PREPARE DISTSQL; `
- [ ] support `APPLY DISTSQL; `
- [ ] support  `DISCARD DISTSQL; `
- [x] provide API for above syntax, and refactor the registry center data structure

**Comment by TeslaCN** [comment]
Hi @menghaoranss @zjcnb 
Any update here? Could we finish this in 5.1.1?

**Comment by RaigorJiang** [comment]
> Hi @menghaoranss @zjcnb Any update here? Could we finish this in 5.1.1?

I think it's not done yet, maybe postpone to the next milestone.

**Comment by zjcnb** [comment]
> > Hi @menghaoranss @zjcnb Any update here? Could we finish this in 5.1.1?
> 
> I think it's not done yet, maybe postpone to the next milestone.

Yes, i agree.

**Comment by RaigorJiang** [comment]
Hi guys, in the investigation of transaction scenarios, it may be a more friendly way to manage DistSQL and standard SQL in the same transaction manager.
Therefore, the current issue will be updated to pending and new features will start in #16777 .

**Comment by RaigorJiang** [comment]
This solution cannot be advanced, I will close this issue.
