### ISSUE TITLE
Add the keyword `IF EXISTS` to all drop syntax in DistSQL

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#15623]
**Current status**: All drop syntaxes in current DistSQL will prompt an exception when the deleted target does not exist.

**Problem**: Not friendly enough when using script execution.

**Improvement measures:** Add the keyword `IF EXISTS` to all drop syntaxes. If the keyword is included in the statement, it is not checked whether the target to be dropped exists.

**Execution result:** if the target exists, drop it, even if it does not exist, no exception will be prompted

**Example**

> DROP RESOURCE IF EXISTS resource_0;
> DROP SHARDING TABLE RULES IF EXISTS t_order;

**Tasks**
- [x] `DROP RESOURCE IF EXISTS resource_0;`
- [x] #15637
- [x] #15638
- [x] Add `IF EXISTS` keyword to `DROP SHARDING TABLE RULE`
- [x] Add `IF EXISTS` keyword to `DROP DEFAULT SHARDING DATABASE STRATEGY IF EXISTS;`
- [x] Add `IF EXISTS` keyword to `DROP SHARDING BINDING TABLE RULES`
- [x] Add `IF EXISTS` keyword to `DROP SHARDING BROADCAST TABLE RULES`
- [x] Add `IF EXISTS` keyword to `DROP SHARDING SCALING RULE`
- [x] Add `IF EXISTS` keyword to `DROP DEFAULT SINGLE TABLE RULE`
- [x] Add `IF EXISTS` keyword to `DROP READWRITE_SPLITTING RULE`
- [x] Add `IF EXISTS` keyword to `DROP DB_DISCOVERY RULE`#15662
- [x] Add `IF EXISTS` keyword to `DROP DB_DISCOVERY TYPE`#15662
- [x] Add `IF EXISTS` keyword to `DROP DB_DISCOVERY HEARTBEAT`#15662
- [x] Add `IF EXISTS` keyword to `DROP ENCRYPT RULE`
- [x] Add `IF EXISTS` keyword to `DROP SHADOW RULE`
- [x] Add `IF EXISTS` keyword to `DROP SHADOW ALGORITHM`

**Comment by LeeGuoPing** [comment]
Can I do part of them?

**Comment by lanchengx** [comment]
> Can I do part of them?

Welcome, you can choose the task you want to do

**Comment by LeeGuoPing** [comment]
@lanchengx I want to do the below first. 
DROP SHARDING KEY GENERATOR IF EXISTS snowflake_key_generator;
DROP SHARDING ALGORITHM IF EXISTS t_order_hash_mod;

**Comment by lanchengx** [comment]
> @lanchengx I want to do the below first. DROP SHARDING KEY GENERATOR IF EXISTS snowflake_key_generator; DROP SHARDING ALGORITHM IF EXISTS t_order_hash_mod;

Thanks, two issues have been opened and assigned to you

**Comment by yx9o** [comment]
hi, can i join.

**Comment by lanchengx** [comment]
@yx9o Of course , Which task do you want to try ?

**Comment by yx9o** [comment]
> * Add `IF EXISTS` keyword to `DROP DB_DISCOVERY RULE`
>         
>       
>   
>       Create an issue with the title Add `IF EXISTS` keyword to `DROP DB_DISCOVERY RULE`. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [ ]  Add `IF EXISTS` keyword to `DROP DB_DISCOVERY TYPE`
>         
>       
>   
>       Create an issue with the title Add `IF EXISTS` keyword to `DROP DB_DISCOVERY TYPE`. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [ ]  Add `IF EXISTS` keyword to `DROP DB_DISCOVERY HEARTBEAT`

**Comment by yx9o** [comment]
> @yx9o Of course , Which task do you want to try ? You can turn it into an issue and assign it to yourself

I want :

**Comment by yx9o** [comment]
> @yx9o Of course , Which task do you want to try ? You can turn it into an issue and assign it to yourself

I want:
Add IF EXISTS keyword to DROP DB_DISCOVERY RULE.
Add IF EXISTS keyword to DROP DB_DISCOVERY TYPE.
Add IF EXISTS keyword to DROP DB_DISCOVERY HEARTBEAT.

**Comment by Swastyy** [comment]
Hi, I want to try `DROP ENCRYPT RULE`

**Comment by yx9o** [comment]
> Hi, I want to try `DROP ENCRYPT RULE`

@Swastyy Sorry, `DROP ENCRYPT RULE` is already working, maybe you can change one.

**Comment by Swastyy** [comment]
> > Hi, I want to try `DROP ENCRYPT RULE`
> 
> @Swastyy Sorry, `DROP ENCRYPT RULE` is already working, maybe you can change one.

Ohh, can I do SHADOW RULE?

**Comment by yx9o** [comment]
> > > Hi, I want to try `DROP ENCRYPT RULE`
> > 
> > 
> > @Swastyy Sorry, `DROP ENCRYPT RULE` is already working, maybe you can change one.
> 
> Ohh, but why it is not in the drop.xml file for if exist clause then

ref：https://github.com/apache/shardingsphere/pull/15635
