### ISSUE TITLE
Support get logic ddl sql 

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#17137]
## Summary
mysql has show create table statement, but i can only get the real sql, when we configed a logic table like sharding table, then we'll not get the logic ddl sql.
for example, I have a sharding table `t_order`, but the actual tables is `t_order_0`. Then we can't get ddl sql by execute `show create table t_order`.
And some database like postgres can't get ddl sql directly. So we need to get actual sql first, then we decorate the actual ddl sql
## Task
- [x] support get logic ddl sql for mysql
- [x] support get logic ddl sql for postgres
- [x] support get logic ddl sql for opengauss
### postgres
We can't get actual ddl sql directly from postgres, So we need to get the sql by metadata in postgres. Then we decorate the actual ddl sql.
### Mysql
Use `show create table` to get the actual sql, Then decoreate it.

**Comment by TeslaCN** [comment]
Hi @tuichenchuxin 
Have we finished this issue?
