### ISSUE TITLE
[WeOpen-Star] Support ShardingSphere parser of oracle sql. 

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#17635]
Hi community,

This issue is for [WeOpen-Star](https://github.com/apache/shardingsphere/issues/17502)
ref to #6480

### Background

**How is a SQL parsed?**
`SQL definition file` 
->(Parse to) 
`AST`
->(Visit it)  
`SQLStatment`  

### Process

1. Compare `SQL definitions` in [Oficial SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/plsql-language-elements.html#GUID-285DFAEE-1A34-4248-BA4B-2591476A0C3C) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc
3. Run `mvn install the current_file_module` 
4. Check whether there are any exceptions. If indeed, please fix them. (Especially `xxxVisitor.class`)
5. Add new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/supported) and expected parsed result in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/case)
6. Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) to make sure no exceptions.

### Notice
1.`Left recursion` can not work well in Antlr4, 
```
a
  : b
  | a b
  ;
b
  : a c
  ;
c
  : ...
  ;
```
you can consider the following one,
```
a
  : b*
  ;
b
  : a c
  ;
c
  : ...
  ;
```

2. [Here](https://shimo.im/docs/WrgrCt9JR3JDjq8H/read) is a Chinese version for reference.

### subtask
- [ ] ALTER PROCEDURE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-PROCEDURE.html#GUID-24A5796F-7D97-49D4-8448-7E541CB73AC6)
- [ ] CREATE PROCEDURE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-PROCEDURE.html#GUID-771879D8-BBFD-4D87-8A6C-290102142DA3)
- [ ] DROP PROCEDURE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/DROP-PROCEDURE.html#GUID-D7F2B5AD-DEEE-466B-B6D3-B765EB897DCB)

**Comment by complone** [comment]
I want to try this work

**Comment by terrymanu** [comment]
Hi community, this issue still keep open to pick up.

**Comment by tianhao960** [comment]
I would like to try

**Comment by strongduanmu** [comment]
@tianhao960 Welcome, I will assign this issue to you.

**Comment by tianhao960** [comment]
hi, @tuichenchuxin , I'm sorry that the pull request just fix the create procedure one; I'll post a new pr to fix the alter and drop statement. thanks
