### ISSUE TITLE
Support ShardingSphere parser of openGauss sql

### ISSUE THREAD

**Issue by chakkk309** [apache/shardingsphere#17736]
Hi, I think we can support parsing more SQLs for openGauss(version 3.0.0).

#### Background

How is a SQL parsed?
`SQL definition file`
->(Parse to)
`AST`
->(Visit it)
`SQLStatment`

#### Process

1. Compare `SQL definitions` in [Oficial SQL Doc](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/sql-syntax.html) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc
3. Run `mvn install the current_file_module`
4. Check whether there are any exceptions. If indeed, please fix them. (Especially `xxxVisitor.class`)
5. Add new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/supported) and expected parsed result in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/resources/case)
6. Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/main/java/org/apache/shardingsphere/test/sql/parser/parameterized/engine/SQLParserParameterizedTest.java) to make sure no exceptions.

#### Notice
1. `Left recursion` can not work well in Antlr4,
```
a
  : b
  | a b
  ;
b
  : a c
  ;
c
  : ...
  ;
```
you can consider the following one,
```
a
  : b*
  ;
b
  : a c
  ;
c
  : ...
  ;
```
2. [Here](https://shimo.im/docs/WrgrCt9JR3JDjq8H/read) is a Chinese version for reference.

#### Subtask

- [ ] [ABORT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/abort.html)
- [x] [ALTER AGGREGATE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-aggregate.html)
- [ ] [ALTER AUDIT POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-audit-policy.html)
- [ ] [ALTER DATABASE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-database.html)
- [ ] [ALTER DATA SOURCE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-data-source.html)
- [x] [ALTER DEFAULT PRIVILEGES](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-default-privileges.html)
- [x] [ALTER DIRECTORY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-directory.html)
- [x] [ALTER EXTENSION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-extension.html)
- [x] [ALTER FOREIGN TABLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-foreign-table.html)
- [ ] [ALTER FUNCTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-function.html)
- [x] [ALTER GROUP](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-group.html)
- [ ] [ALTER INDEX](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-index.html)
- [x] [ALTER LANGUAGE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-language.html)
- [x] [ALTER LARGE OBJECT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-large-object.html)
- [ ] [ALTER MASKING POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-masking-policy.html)
- [ ] [ALTER MATERIALIZED VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-materialized-view.html)
- [ ] [ALTER OPERATOR](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-operator.html)
- [ ] [ALTER PUBLICATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-publication.html)
- [x] [ALTER PACKAGE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-package.html)
- [ ] [ALTER RESOURCE LABEL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-resource-label.html)
- [x] [ALTER RESOURCE POOL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-resource-pool.html)
- [ ] [ALTER ROLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-role.html)
- [x] [ALTER ROW LEVEL SECURITY POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-row-level-security-policy.html)
- [ ] [ALTER SCHEMA](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-schema.html)
- [x] [ALTER SEQUENCE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-sequence.html)
- [ ] [ALTER SERVER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-server.html)
- [ ] [ALTER SESSION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-session.html)
- [ ] [ALTER SUBSCRIPTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-subscription.html)
- [x] [ALTER SYNONYM](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-synonym.html)
- [ ] [ALTER SYSTEM KILL SESSION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-system-kill-session.html)
- [x] [ALTER SYSTEM SET](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-system-set.html)
- [ ] [ALTER TABLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-table.html)
- [ ] [ALTER TABLE PARTITION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-table-partition.html)
- [x] [ALTER TABLE SUBPARTITION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-table-subpartition.html)
- [ ] [ALTER TABLESPACE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-tablespace.html)
- [ ] [ALTER TEXT SEARCH CONFIGURATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-text-search-configuration.html)
- [x] [ALTER TEXT SEARCH DICTIONARY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-text-search-dictionary.html)
- [ ] [ALTER TRIGGER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-trigger.html)
- [x] [ALTER TYPE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-type.html)
- [ ] [ALTER USER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-user.html)
- [x] [ALTER USER MAPPING](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-user-mapping.html)
- [ ] [ALTER VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-view.html)
- [ ] [ANALYZE | ANALYSE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/analyze-analyse.html)
- [ ] [BEGIN](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/begin.html)
- [ ] [CALL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/call.html)
- [x] [CHECKPOINT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/checkpoint.html)
- [ ] [CLEAN CONNECTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/clean-connection.html)
- [ ] [CLOSE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/close.html)
- [ ] [CLUSTER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/cluster.html)
- [ ] [COMMENT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/comment.html)
- [ ] [COMMIT | END](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/commit-end.html)
- [ ] [COMMIT PREPARED](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/commit-prepared.html)
- [ ] [COPY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/copy.html)
- [x] [CREATE AGGREGATE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-aggregate.html)
- [ ] [CREATE AUDIT POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-audit-policy.html)
- [x] [CREATE CAST](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-cast.html)
- [ ] [CREATE CLIENT MASTER KEY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-client-master-key.html)
- [ ] [CREATE COLUMN ENCRYPTION KEY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-column-encryption-key.html)
- [ ] [CREATE DATABASE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-database.html)
- [ ] [CREATE DATA SOURCE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-data-source.html)
- [x] [CREATE DIRECTORY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-directory.html)
- [ ] [CREATE EXTENSION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-extension.html)
- [ ] [CREATE FOREIGN TABLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-foreign-table.html)
- [ ] [CREATE FUNCTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-function.html)
- [x] [CREATE GROUP](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-group.html)
- [ ] [CREATE INCREMENTAL MATERIALIZED VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-incremental-materialized-view.html)
- [ ] [CREATE INDEX](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-index.html)
- [x] [CREATE LANGUAGE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-language.html)
- [ ] [CREATE MASKING POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-masking-policy.html)
- [ ] [CREATE MATERIALIZED VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-materialized-view.html)
- [ ] [CREATE MODEL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-model.html)
- [ ] [CREATE OPERATOR](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-operator.html)
- [x] [CREATE PACKAGE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-package.html)
- [ ] [CREATE PROCEDURE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-procedure.html)
- [x] [CREATE PUBLICATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-publication.html)
- [ ] [CREATE RESOURCE LABEL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-resource-label.html)
- [x] [CREATE RESOURCE POOL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-resource-pool.html)
- [ ] [CREATE ROLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-role.html)
- [ ] [CREATE ROW LEVEL SECURITY POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-row-level-security-policy.html)
- [x] [CREATE RULE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-rule.html)
- [ ] [CREATE SCHEMA](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-schema.html)
- [ ] [CREATE SEQUENCE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-sequence.html)
- [ ] [CREATE SERVER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-server.html)
- [ ] [CREATE SUBSCRIPTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-subscription.html)
- [x] [CREATE SYNONYM](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-synonym.html)
- [ ] [CREATE TABLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-table.html)
- [x] [CREATE TABLE AS](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-table-as.html)
- [ ] [CREATE TABLE PARTITION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-table-partition.html)
- [ ] [CREATE TABLESPACE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-tablespace.html)
- [x] [CREATE TABLE SUBPARTITION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-table-subpartition.html)
- [ ] [CREATE TEXT SEARCH CONFIGURATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-text-search-configuration.html)
- [ ] [CREATE TEXT SEARCH DICTIONARY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-text-search-dictionary.html)
- [ ] [CREATE TRIGGER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-trigger.html)
- [ ] [CREATE TYPE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-type.html)
- [ ] [CREATE USER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-user.html)
- [x] [CREATE USER MAPPING](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-user-mapping.html)
- [x] [CREATE VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-view.html)
- [ ] [CREATE WEAK PASSWORD DICTIONARY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/create-weak-password-dictionary.html)
- [ ] [CURSOR](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/cursor.html)
- [x] [DEALLOCATE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/deallocate.html)
- [ ] [DECLARE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/declare.html)
- [ ] [DELETE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/delete.html)
- [ ] [DO](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/do.html)
- [ ] [DROP AGGREGATE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-aggregate.html)
- [x] [DROP AUDIT POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-audit-policy.html)
- [x] [DROP CAST](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-cast.html)
- [ ] [DROP CLIENT MASTER KEY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-client-master-key.html)
- [ ] [DROP COLUMN ENCRYPTION KEY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-column-encryption-key.html)
- [ ] [DROP DATABASE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-database.html)
- [ ] [DROP DATA SOURCE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-data-source.html)
- [x] [DROP DIRECTORY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-directory.html)
- [ ] [DROP EXTENSION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-extension.html)
- [ ] [DROP FOREIGN TABLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-foreign-table.html)
- [ ] [DROP FUNCTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-function.html)
- [x] [DROP GROUP](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-group.html)
- [x] [DROP INDEX](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-index.html)
- [x] [DROP LANGUAGE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-language.html)
- [ ] [DROP MASKING POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-masking-policy.html)
- [ ] [DROP MATERIALIZED VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-materialized-view.html)
- [ ] [DROP MODEL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-model.html)
- [x] [DROP OPERATOR](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-operator.html)
- [x] [DROP OWNED](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-owned.html)
- [x] [DROP PACKAGE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-package.html)
- [ ] [DROP PROCEDURE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-procedure.html)
- [ ] [DROP RESOURCE LABEL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-resource-label.html)
- [ ] [DROP RESOURCE POOL](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-resource-pool.html)
- [x] [DROP ROLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-role.html)
- [x] [DROP ROW LEVEL SECURITY POLICY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-row-level-security-policy.html)
- [x] [DROP RULE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-rule.html)
- [x] [DROP PUBLICATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-publication.html)
- [x] [DROP SCHEMA](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-schema.html)
- [ ] [DROP SEQUENCE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-sequence.html)
- [x] [DROP SERVER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-server.html)
- [ ] [DROP SUBSCRIPTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-subscription.html)
- [x] [DROP SYNONYM](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-synonym.html)
- [ ] [DROP TABLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-table.html)
- [ ] [DROP TABLESPACE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-tablespace.html)
- [ ] [DROP TEXT SEARCH CONFIGURATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-text-search-configuration.html)
- [x] [DROP TEXT SEARCH DICTIONARY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-text-search-dictionary.html)
- [ ] [DROP TRIGGER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-trigger.html)
- [x] [DROP TYPE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-type.html)
- [ ] [DROP USER](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-user.html)
- [ ] [DROP USER MAPPING](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-user-mapping.html)
- [x] [DROP VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-view.html)
- [ ] [DROP WEAK PASSWORD DICTIONARY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-weak-password-dictionary.html)
- [ ] [EXECUTE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/execute.html)
- [ ] [EXPLAIN](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/explain.html)
- [ ] [EXPLAIN PLAN](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/explain-plan.html)
- [ ] [FETCH](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/fetch.html)
- [ ] [GRANT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/grant.html)
- [ ] [INSERT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/insert.html)
- [ ] [LOCK](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/lock.html)
- [x] [MERGE INTO](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/merge-into.html)
- [ ] [MOVE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/move.html)
- [ ] [PREDICT BY](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/predict-by.html)
- [ ] [PREPARE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/prepare.html)
- [ ] [PREPARE TRANSACTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/prepare-transaction.html)
- [ ] [PURGE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/purge.html)
- [x] [REASSIGN OWNED](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/reassign-owned.html)
- [ ] [REFRESH INCREMENTAL MATERIALIZED VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/refresh-incremental-materialized-view.html)
- [ ] [REFRESH MATERIALIZED VIEW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/refresh-materialized-view.html)
- [ ] [REINDEX](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/reindex.html)
- [x] [RELEASE SAVEPOINT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/release-savepoint.html)
- [x] [RESET](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/reset.html)
- [ ] [REVOKE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/revoke.html)
- [ ] [ROLLBACK](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/rollback.html)
- [ ] [ROLLBACK PREPARED](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/rollback-prepared.html)
- [x] [ROLLBACK TO SAVEPOINT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/rollback-to-savepoint.html)
- [ ] [SAVEPOINT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/savepoint.html)
- [ ] [SELECT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/select.html)
- [ ] [SELECT INTO](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/select-into.html)
- [ ] [SET](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/set.html)
- [x] [SET CONSTRAINTS](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/set-constraints.html)
- [ ] [SET ROLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/set-role.html)
- [ ] [SET SESSION AUTHORIZATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/set-session-authorization.html)
- [x] [SET TRANSACTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/set-transaction.html)
- [x] [SHOW](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/show.html)
- [x] [SHUTDOWN](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/shutdown.html)
- [ ] [SNAPSHOT](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/snapshot.html)
- [ ] [START TRANSACTION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/start-transaction.html)
- [ ] [TIMECAPSULE TABLE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/timecapsule-table.html)
- [ ] [TRUNCATE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/truncate.html)
- [ ] [UPDATE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/update.html)
- [ ] [VACUUM](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/vacuum.html)
- [ ] [VALUES](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/values.html)
- [x] [ALTER PROCEDURE](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-procedure.html)
- [ ] [ALTER GLOBAL CONFIGURATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/alter-global-configuration.html)
- [x] [DROP GLOBAL CONFIGURATION](https://opengauss.org/en/docs/3.0.0/docs/Developerguide/drop-global-configuration.html)

**Comment by strongduanmu** [comment]
@chakkk309 Great, let's start our openGauss SQL parsing journey.

**Comment by everly-gif** [comment]
Hi @strongduanmu @chakkk309  I would like to help out in this task as well 😊

**Comment by chakkk309** [comment]
> Hi @strongduanmu @chakkk309 I would like to help out in this task as well 😊

 @everly-gif very happy to work on this issue together~

**Comment by everly-gif** [comment]
I want to start with 

- [ ] `ALTER SYNONYM`

**Comment by everly-gif** [comment]
> > Hi @strongduanmu @chakkk309 I would like to help out in this task as well 😊
> 
> @everly-gif very happy to work on this issue together~

Please pardon me for my late reply, but really happy to work together as well 😊

**Comment by rajmunkhan** [comment]
Hey @strongduanmu, I also want to contribute to this task, can u also assign this to me? 😊

**Comment by strongduanmu** [comment]
@rajmunkhan Of course, if you are interested in the sub-tasks, please leave a message to claim it.

**Comment by rajmunkhan** [comment]
I want to start working on 

- [ ] `CREATE AGGREGATE`

**Comment by zihaoAK47** [comment]
- [DROP SERVER] 

Hello, I want to try the SQL parsing of DROP SERVER, I think I can do it, I have studied for a long time today, can I try.

**Comment by chakkk309** [comment]
> * [DROP SERVER]
> 
> Hello, I want to try the SQL parsing of DROP SERVER, I think I can do it, I have studied for a long time today, can I try.

@zihaoAK47 Of course and welcome!
