### ISSUE TITLE
[GSoC 2022] Solve Unsupported PostgreSQL Statements That Start With 'c' for Shardingsphere Parser

### ISSUE THREAD

**Issue by ThanoshanMV** [apache/shardingsphere#17844]
This issue is to solve unsupported PostgreSQL statements listed below for the Shardingsphere parser.

## Background
The ShardingSphere parser engine can handle various SQL dialects such as MySQL, PostgreSQL, SQLServer, openGauss, and Oracle. Although the parser engine supports numerous PostgreSQL statements, some important PostgreSQL statements that start with ‘c’ requires assistance in parsing and getting the SQLStatement (Java object). Therefore, this issue aims to support those specific PostgreSQL statements listed below for the ShardingSphere parser.

### Subtasks

- [x] CALL
- [x] CHECKPOINT
- [x] CLOSE
- [x] CLUSTER
- [x] COMMENT
- [x] COPY
- [x] CREATE ACCESS METHOD
- [x] CREATE AGGREGATE
- [x] CREATE CAST
- [x] CREATE COLLATION
- [x] CREATE EVENT TRIGGER
- [x] CREATE FOREIGN DATA WRAPPER
- [x] CREATE FOREIGN TABLE
- [x] CREATE GROUP
- [x] CREATE MATERIALIZED VIEW
- [x] CREATE OPERATOR
- [x] CREATE POLICY
- [x] CREATE PUBLICATION
- [x] DECLARE
- [x] FETCH
- [x] MOVE

Reference: please refer to PostgreSQL SQL commands [documentation](https://www.postgresql.org/docs/current/sql-commands.html).

**Comment by ThanoshanMV** [comment]
We have planned to support other PostgreSQL cursor statements as well. They are Declare, Fetch and Move statements.

**Comment by ThanoshanMV** [comment]
Hi @strongduanmu, I checked the statements `DECLARE`, `FETCH`, and `MOVE`. I think now they are visited. Do we need to change anything to these statements?

**Comment by strongduanmu** [comment]
Yes, another contributor @chakkk309  in the ShardingSphere community has completed the optimization of these statements, so you only need to mark it complete.

**Comment by ThanoshanMV** [comment]
Thank you @strongduanmu

**Comment by strongduanmu** [comment]
All subtasks has been finished, so I will close this issue.

**Comment by ThanoshanMV** [comment]
Thank you @strongduanmu, @tristaZero and my other mentors. 😃 🎉
