### ISSUE TITLE
Support view for openGauss

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#17915]
Support view for openGauss.
We can support view like supporting tables.
And view will use same rule as tables.
But in sharding, the query in view definition must simple enough. And ensure there's no merge.
For example, t_order is a logic table. actual is t_order_0, t_order_1.
This sql should be rejected to execute.
```
 create view order_view as select count(*) from t_order;
```
logic view and actual view should have the relationship like logic table and actual tables.
```
select * from view_0;
select * from view_1;
// should equal to 
select * from logic_view;
```
## tasks
- [x]  support g4 file for view in openGauss
- [x]  support readwrite-splitting for view in openGauss
- [x]  support sharding for view in openGauss
- [x]  add check for create view in sharding
- [x]  add test case

**Comment by tuichenchuxin** [comment]
ref #16771
