### ISSUE TITLE
[ OSPP 2022 ] Solve unsupported Oracle SQL about Alter Statement for ShardingSphere Parser

### ISSUE THREAD

**Issue by chakkk309** [apache/shardingsphere#18389]
This issue is created to better track my PRs for OSPP 2022, you can view more about my project [here](https://summer-ospp.ac.cn/#/org/prodetail/22ee10103).

## Background
ShardingSphere Parser Engine helps users parse SQL statements into AST and generate corresponding SQL Statement objects from it.

## Process
1. Compare SQL definitions in [Oficial SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/plsql-language-elements.html#GUID-285DFAEE-1A34-4248-BA4B-2591476A0C3C) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle).
2. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc.
3. Run `mvn install the current_file_module`.
4. Check whether there are any exceptions. If indeed, please fix them. (`Especially xxxVisitor.class`).
5. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statment XML.
6. Run SQLParserParameterizedTest to make sure no exceptions.

## Tasks
- [x] ALTER INDEXTYPE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-INDEXTYPE.html#GUID-BFA7E29C-7905-4811-9119-B20FD8EA18F2) 
- [x] ALTER INMEMORY JOIN GROUP [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-INMEMORY-JOIN-GROUP.html#GUID-AF24F413-BB14-4B5D-93BF-9EB31ACFEBEC) 
- [x] ALTER JAVA [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-JAVA.html#GUID-6B211750-3247-4D71-9533-3DD8F66640CD) 
- [x] ALTER LIBRARY [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-LIBRARY.html#GUID-BB90AF66-3B1F-46C4-9716-4578DE0AE1F3) 
- [x] ALTER LOCKDOWN PROFILE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-LOCKDOWN-PROFILE.html#GUID-B4029154-54A8-4B78-97C3-9CED416F1C34) 
- [x] ALTER MATERIALIZED VIEW [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-MATERIALIZED-VIEW.html#GUID-29EE5682-AE42-4879-ABAD-E34E66ADD233) 
- [x] ALTER MATERIALIZED VIEW LOG [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-MATERIALIZED-VIEW-LOG.html#GUID-4DAD5E6F-E30A-43D0-B023-634752E0E627) 
- [x] ALTER MATERIALIZED ZONEMAP [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-MATERIALIZED-ZONEMAP.html#GUID-9330FD16-28B6-4B22-8205-FF59AF250C1A) 
- [x] ALTER OPERATOR [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-OPERATOR.html#GUID-F00A0AC8-36C8-4EAC-A9BB-B3D42C5EEEDE) 
- [x] ALTER OUTLINE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-OUTLINE.html#GUID-49F25C82-0783-4407-88BB-613F986C2FEC) 
- [x] ALTER PACKAGE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-PACKAGE.html#GUID-47471C4C-03AB-4D78-A295-3D58C91102E0) 
- [x] ALTER PLUGGABLE DATABASE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-PLUGGABLE-DATABASE.html#GUID-A29491AD-8F0F-4E52-9D94-57FC3FF8FBC7)

This issue is a ref to https://github.com/apache/shardingsphere/issues/6480

**Comment by strongduanmu** [comment]
Great, all the subtasks have been completed. So I will close this issue.
