### ISSUE TITLE
Consider supporting PostgreSQL declare cursor, open, fetch, move, close statement

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#18414]
## Background

After we complete the cursor feature of openGauss in issue #17825, we need to adapt the cursor feature of PostgreSQL. In general, their logic are similar, and the logic of the existing kernel can be supported, but some adaptations are required in the part of SQL syntax parsing and sql statement context extraction.

## Subtasks

- [ ] support PostgreSQL declare cursor, open, fetch, move, close statement parse
- [ ] support declare cursor, open, fetch, move, close statement in read-write splitting scenario
- [ ] support declare cursor, open, fetch, close statement in sharding scenario
- [ ] add test case

**Comment by chakkk309** [comment]
Hi @strongduanmu, I want to try it.

**Comment by strongduanmu** [comment]
@chakkk309 Welcome, I will assign this issue to you.

**Comment by ThanoshanMV** [comment]
Hi @strongduanmu, shall I try this? 😄

**Comment by strongduanmu** [comment]
@ThanoshanMV Of course, I will assign this issue to you.

**Comment by ThanoshanMV** [comment]
Thank you @strongduanmu. I'll take this opportunity to learn read-write splitting and sharding scenarios of the SQL statements 😃
