### ISSUE TITLE
[ OSPP 2022 ] Solve unsupported Oracle SQL about Alter Statement for ShardingSphere Parser

### ISSUE THREAD

**Issue by Trydamere** [apache/shardingsphere#18431]
This issue is created to better track my PRs for OSPP 2022, you can view more about my project [here](https://summer-ospp.ac.cn/#/org/prodetail/22ee10102).

## Background
ShardingSphere Parser Engine helps users parse SQL statements into AST and generate corresponding SQL Statement objects from it.

## Process
1. Compare SQL definitions in [Oficial SQL Doc](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/plsql-language-elements.html#GUID-285DFAEE-1A34-4248-BA4B-2591476A0C3C) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-oracle/src/main/antlr4/imports/oracle?rgh-link-date=2022-06-16T08%3A46%3A30Z).
2. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc.
3. Run `mvn install the current_file_module`.
4. Check whether there are any exceptions. If indeed, please fix them. (`Especially xxxVisitor.class`).
5. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statment XML.
6. Run SQLParserParameterizedTest to make sure no exceptions.

## Tasks
* [x]  LOCK TABLE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LOCK-TABLE.html#GUID-4C00C6D9-C5C5-46CC-AD33-A64001744A4C)
* [x] ALTER ANALYTIC VIEW [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-ANALYTIC-VIEW.html#GUID-5256BE3A-F134-40D4-8E70-684E073574C8) 
* [x] ALTER ATTRIBUTE DIMENSION [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-ATTRIBUTE-DIMENSION.html#GUID-F345D0F9-8133-4257-9A07-EDCE558A1332) 
* [x] ALTER AUDIT POLICY (Unified Auditing) [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-AUDIT-POLICY-Unified-Auditing.html#GUID-CC41B5C2-09F4-40BC-B7FD-3B4C0A3F5437) 
* [x] ALTER CLUSTER [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-CLUSTER.html#GUID-A4E03C13-7690-4567-9B0A-DA6A21173B4D) 
* [x] ALTER DATABASE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-DATABASE.html#GUID-8069872F-E680-4511-ADD8-A4E30AF67986) 
* [x] ALTER DATABASE DICTIONARY [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-DATABASE-DICTIONARY.html#GUID-27DDB403-7E7F-40EC-9B48-5E3B475E27AE) 
* [x] ALTER DATABASE LINK [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-DATABASE-LINK.html#GUID-0259D771-9D04-4D86-A94D-61B621A3918A) 
* [x] ALTER DISKGROUP [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-DISKGROUP.html#GUID-22D73AB6-7063-4627-A2ED-18D521ED2557) 
* [x] ALTER FLASHBACK ARCHIVE [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-FLASHBACK-ARCHIVE.html#GUID-285814C9-06ED-4BDB-BB19-E2BA6505C850) 
* [x] ALTER FUNCTION [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-FUNCTION.html#GUID-6FB32876-2DB3-41EB-B0CA-91B163826AB2) 
* [x] ALTER HIERARCHY [doc](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-HIERARCHY.html#GUID-37A4E442-EE3A-4239-8228-F08A2F666D91)

This issue is a ref to #6480

**Comment by Trydamere** [comment]
`ALTER ANALYTIC VIEW` supported by #17538

**Comment by Trydamere** [comment]
`ALTER ATTRIBUTE DIMENSION` supported by #17601

**Comment by strongduanmu** [comment]
All subtasks has been finished.
