### ISSUE TITLE
Splitting the task of improving the Rule Definition documentation

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#19898]
About issue #16666 and #15604.

We now want to refine and refactor the documentation related to DistSQl.

Now I want the community to help improve the RDL documentation related to sharding.

This document refactoring has the following tasks
Task list (continuously added):
##### task 1:
- [ ] `DROP SHARDING TABLE RULE`

##### task 2:
- [ ] `ALTER DEFAULT SHARDING STRATEGY `
- [ ] `DROP DEFAULT SHARDING STRATEGY `

##### task 3:
- [ ] `ALTER  SHARDING ALGORITHM`
- [ ] `DROP SHARDING ALGORITHM`

##### task 4:
- [ ] `ALTER SHARDING KEY GENERATOR`
- [ ] `DROP SHARDING KEY GENERATOR`

##### task 5:
- [ ] `ALTER SHARDING BINDING TABLE RULE`
- [ ] `DROP SHARDING BINDING TABLE RULE`

##### task 6:
- [ ] `ALTER SHARDING BROADCAST TABLE RULE`
- [ ] `DROP SHARDING BROADCAST TABLE RULE`

You can refer to the following links:
[Old document](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/)
[Completed content](https://shardingsphere.apache.org/document/current/en/reference/distsql/syntax/rdl/rule-definition/sharding/)

If you encounter any problems in the process you can contact me.

**Comment by Swastyy** [comment]
Hi, I want to try some of them.

**Comment by strongduanmu** [comment]
@Swastyy Welcome, our new committer. 👍

**Comment by JiekerTime** [comment]
> Hi, I want to try some of them.

Hi ～ can you try task 1 first?

**Comment by RaigorJiang** [comment]
Completed, thank you!
