### ISSUE TITLE
Add ConnectionContext and QueryContext for kernel and remove thread local

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#20005]
## Feature Request
Kernel use thread local to handle some connection context and some request context. It's better to use `ConnectionContext` and `QueryContext` to hold context instead of threadlocal.
### task

- [x] add connectionContext for kernel
- [x] remove thread local for cursor
- [x] remove traffic context holder
- [x] remove sql statement database holder
- [x] refactor logicSQL to QueryContext

**Comment by strongduanmu** [comment]
Hi @tuichenchuxin , could we finish this issue in `5.1.3`?
