### ISSUE TITLE
Support SQL HINT

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#20736]
## Feature Request

We have `HintManager` for users to use for hint route, But it's depends on `ThreadLocal`.

We want to use SQL hint to replace HintManager for more convenient to use.

## replace `HintManager.setDatabaseShardingValue`
```
/* SHARDINGSPHERE_HINT: SHARDING_DATABASE_VALUE=1 */
SELECT * FROM t_order,t_order_item;
```
## replace `HintManager.addDatabaseShardingValue` `HintManager.addTableShardingValue`
```
/* SHARDINGSPHERE_HINT: t_order.SHARDING_DATABASE_VALUE=100,t_order.SHARDING_TABLE_VALUE=100 */
SELECT * FROM t_order,t_order_item;
```
## replace `HintManager.setWriteRouteOnly` mix sharding
```
/* SHARDINGSPHERE_HINT: t_order.SHARDING_DATABASE_VALUE=100,t_order.SHARDING_TABLE_VALUE=100,t_order_item.SHARDING_DATABASE_VALUE=100,WRITE_ROUTE_ONLY=true */
SELECT * FROM t_order,t_order_item;
```

## for better performance

Since we have SQL parse cache, shardingSphere have a good performance. But if we have same SQL with different comment, we can not use the parse cache. So it's better to extract hint in proxy and jdbc, and remove the hint message from sql before parsing sql.
 
## tasks

- [x] support sql hint for sharding
- [x] refactor sql hint for readwrite
- [x] move shadow comment extracted to sql hint
- [ ] better performance for sql hint

**Comment by dongzl** [comment]
I want to try it. If others are interested, we can do it together.

**Comment by strongduanmu** [comment]
Hi @tuichenchuxin @dongzl , could we finish this issue in 5.2.1?

**Comment by dongzl** [comment]
> Hi @tuichenchuxin @dongzl , could we finish this issue in 5.2.1?

Hi @strongduanmu ，what's the deadline for Release 5.2.1? I think only part of the work can be done.

**Comment by strongduanmu** [comment]
Since this task still has some subtasks unfinished, I will move it to 5.2.2.

**Comment by lanrenbulan** [comment]
Hi, In proxy5.2.1, I tested SQL hint, but it didn't work. #21437

**Comment by TeslaCN** [comment]
Hi @tuichenchuxin @dongzl 
Have we finished this?

**Comment by sandynz** [comment]
Hi @tuichenchuxin and @dongzl , could it be done totally on 5.3.1?
