### ISSUE TITLE
Add some integration test case for DistSQL RAL

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#20867]
Hi community,

## Aim : 

Add some integration test case for [RAL](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/ral/)

## How to do

1. You need to know about the integration test module [shardingsphere-integration-test-suite](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite)
2. Add test case in `ral-integration-test-cases.xml`
3. Add [expected data file ](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/ral/dataset/empty_rules)

## How to run 

1. You need have `docker` environment in your local.
2. Build IT image `./mvnw -B clean install -am -pl shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite -Pit.env.docker -DskipTests -Dspotless.apply.skip=true`.
3. Fill in `it.run.modes `with [it-env.properties](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/env/it-env.properties).
4. Run [GeneralRALIT.class](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/ral/GeneralRALIT.java).

## Task list : 
- [x] SHOW INSTANCE LIST
- [ ] SHOW READWRITE_SPLITTING READ RESOURCE
- [ ] SHOW AUTHORITY RULE
- [ ] SHOW TRANSACTION RULE
- [ ] SHOW SQL_PARSER RULE
- [ ] SHOW INSTANCE INFO @leedongyang 
- [ ] SHOW MODE INFO @leedongyang 
- [ ] COUNT DATABASE RULES
- [ ] SET VARIABLE sql_show = true
- [ ] SHOW ALL VARIABLES
- [ ] SHOW VARIABLE sql_show

**Comment by zhaojinchao95** [comment]
> I want have a try, such as SHOW INSTANCE INFO, SHOW MODE INFO.

Welcome

**Comment by TeslaCN** [comment]
Test is not included in release. I'm removing milestone for now.

**Comment by Qianyi951015** [comment]
Hi @zhaojinchao95, I have done the second, third, fourth, fifth, tenth, and eleventh tasks, would you mind having a review when you are free?

**Comment by Qianyi951015** [comment]
Hi, @zhaojinchao95 I have done the eighth and ninth tasks. Would you mind having a review?

BTW: the `COUNT DATABASE RULES` was split into `COUNT SINGLE_TABLE RULE`, `COUNT SHARDING RULE`, `COUNT READWRITE_SPLITTING RULE`, `COUNT DATABASE_DISCOVERY RULE`, `COUNT ENCRYPT RULE`, `COUNT SHADOW RULE` (Ref: #18583).    I have added these cases to RQL.

**Comment by zhaojinchao95** [comment]
This task are finished at `master` branch, close it
