### ISSUE TITLE
Add some integration test case for DistSQL RDL

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#21072]
Hi community,

## Aim : 

Add some integration test case for [RDL](https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/rdl/)

## How to do

1. You need to know about the integration test module [shardingsphere-integration-test-suite](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite)
2. Add test case in `rdl-integration-test-cases.xml`
3. Add [expected data file ](https://github.com/apache/shardingsphere/tree/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/cases/ral/dataset/rdl_empty_rules)

## How to run 

1. You need have `docker` environment in your local.
2. Build IT image `./mvnw -B clean install -am -pl shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite -Pit.env.docker -DskipTests -Dspotless.apply.skip=true`.
3. Fill in `it.run.modes `with [it-env.properties](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/resources/env/it-env.properties).
4. Run [GeneralRDLIT.class](https://github.com/apache/shardingsphere/blob/master/shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/src/test/java/org/apache/shardingsphere/test/integration/engine/rdl/GeneralRDLIT.java).

## Task list : 
- [ ] CREATE SHARDING BINDING TABLE RULES
- [ ] ALTER SHARDING BINDING TABLE RULES
- [ ] DROP SHARDING BINDING TABLE RULES
- [ ] CREATE SHARDING BROADCAST TABLE RULES
- [ ] ALTER SHARDING BROADCAST TABLE RULES
- [ ] DROP SHARDING BROADCAST TABLE RULES
- [ ] CREATE ENCRYPT RULE
- [ ] ALTER ENCRYPT RULE
- [ ] DROP ENCRYPT RULE
- [x] CREATE DEFAULT SINGLE TABLE RULE
- [x] ALTER DEFAULT SINGLE TABLE RULE
- [x] DROP DEFAULT SINGLE TABLE RULE

**Comment by tianhao960** [comment]
hi，I would like to try the last 3 tasks about DEFAULT SINGLE TABLE RULE

**Comment by zhaojinchao95** [comment]
> hi，I would like to try the last 3 tasks about DEFAULT SINGLE TABLE RULE

Welcome

**Comment by strongduanmu** [comment]
Hi @tianhao960 , could we finish this issue in 5.2.1?

**Comment by tianhao960** [comment]
> Hi @tianhao960 , could we finish this issue in 5.2.1?

hi, I am afraid I need some time to finish this and  before 5.2.2 release, it could be done. thanks.
