### ISSUE TITLE
Add ShardingSphere built-in database.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#21268]
## Feature Request

We need shardingsphere built-in database to persist some information. such as table statistics, charset, isolation and so on.
The design will be like this.
![image](https://user-images.githubusercontent.com/86938616/193012323-026f147d-60cf-4755-beca-e8e0a6e0ee56.png)

### tasks

- [x] use yaml to simulate ShardingSphere built in table
- [x] add ShardingSphere data and persist
- [x] add schedule thread or zk watch to trigger collect data
- [x] support to use federation to query shardingsphere data

**Comment by strongduanmu** [comment]
Hi @tuichenchuxin , could we finish this issue in 5.2.1?
