### ISSUE TITLE
Optimize the experience of using built-in algorithms in DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22456]
Hi community,

In 5.2.0, we added parameter specifications to DistSQL, such as requiring quotes for string parameters. (Ref: #18811)
<img width="722" alt="image" src="https://user-images.githubusercontent.com/5668787/204122887-dbf08cfb-735d-4dac-a2d3-974442bcb82e.png">

However, considering the user experience, other databases such as MySQL will also provide compatibility strategies for built-in options. 
![image](https://user-images.githubusercontent.com/5668787/204123167-b92c09c1-4810-4d9c-a2c1-7e761d6997db.png)

I suggest providing keyword support for built-in algorithms in DistSQL, so that when users use built-in algorithms such as `INLINE`, quotes do not need to be used. But if the user uses a custom algorithm, the name still needs quotes, because its type is STRING.

- example:
```sql
CREATE SHARDING TABLE RULE t_order (
STORAGE_UNITS(ds_0,ds_1),
SHARDING_COLUMN=order_id,TYPE(NAME=hash_mod, PROPERTIES("sharding-count"=4)),
);

CREATE SHARDING TABLE RULE t_order (
STORAGE_UNITS(ds_0,ds_1),
SHARDING_COLUMN=order_id,TYPE(NAME="custom_auto_algorithm", PROPERTIES("sharding-count"=4)),
);
```

### Tasks
- [x] Optimize sharding-distsql
- [x] Optimize encrypt-distsql
- [x] Optimize readwrite-splitting-distsql
- [x] Optimize db-discovery-distsql
- [x] Optimize shadow-distsql
- [ ] Optimize proxy-backend-distsql
- [ ] Optimize global-rule-distsql
- [ ] Update documents

**Comment by Qianyi951015** [comment]
Please assign to me

**Comment by RaigorJiang** [comment]
Hi @Qianyi951015, welcome!

**Comment by RaigorJiang** [comment]
Completed, thank you! @Qianyi951015
