### ISSUE TITLE
Add `IF NOT EXISTS` to all `CREATE` statements in DistSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#22844]
Hi community,

Previously, we had added the `IF EXISTS` option to the `DROP` statement in DistSQL. (#15623)
Correspondingly, we need to add the `IF NOT EXISTS` option to the `CREATE` statement, just like `CREATE TABLE [IF NOT EXISTS] tbl_name`.

E.g
- `CREATE SHARDING TABLE RULE IF NOT EXISTS xxx`
- `CREATE ENCRYPT RULE IF NOT EXISTS xxx`

### Tasks
- [x] REGISTER STORAGE UNIT
- [x] CREATE SHARDING TABLE RULE
- [x] CREATE SHARDING TABLE REFERENCE RULE
- [x] CREATE BROADCAST TABLE RULE
- [x] CREATE DEFAULT SHARDING [DATABASE | TABLE] STRATEGY
- [x] CREATE ENCRYPT RULE
- [x] CREATE DB_DISCOVERY RULE
- [x] CREATE READWRITE_SPLITTING RULE
- [x] CREATE SHADOW RULE
- [x] CREATE DEFAULT SHADOW ALGORITHM

Note: Both `docs` and `parser test cases` need to be updated.

**Comment by yx9o** [comment]
@RaigorJiang Hi, I want to participate.

**Comment by Qianyi951015** [comment]
Hi @RaigorJiang @yx9o can i pick these tasks?
 - REGISTER STORAGE UNIT
 - CREATE SHARDING TABLE RULE
 - CREATE SHARDING TABLE REFERENCE RULE
 - CREATE BROADCAST TABLE RULE
 - CREATE DEFAULT SHARDING [DATABASE | TABLE] STRATEGY

**Comment by RaigorJiang** [comment]
@Qianyi951015 Welcome, I think you can do it one by one :)

**Comment by Qianyi951015** [comment]
> @Qianyi951015 Welcome, I think you can do it one by one :)

sure

**Comment by RaigorJiang** [comment]
Hi @yx9o , 
I found that `RuleDefinitionUpdater` is declared as `SingletonSPI`, so please check for thread safety risks. 
Thank you!

**Comment by yx9o** [comment]
@RaigorJiang ok i will follow up.

**Comment by RaigorJiang** [comment]
Completed, thank you all @yx9o @Qianyi951015
