### ISSUE TITLE
Add new DistSQL for mask rule configuration

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23138]
Hi community,

this issue is for #22759.

I want to add new DistSQL for manage mask rule configuration.

### Syntax example
```sql
# CREATE
CREATE MASK TABLE? RULE (IF NOT EXISTS)? t_mask (
COLUMNS(
(NAME=telephone,TYPE(NAME='INDEX_BASED_REPLACE',PROPERTIES("start-index"=3,"stop-index"=8,"replace-char"="*"))),
(NAME=address,TYPE(NAME='MD5'))
));

# ALTER
ALTER MASK TABLE? RULE t_mask (
COLUMNS(
(NAME=telephone,TYPE(NAME='INDEX_BASED_REPLACE',PROPERTIES("start-index"=3,"stop-index"=8,"replace-char"="*"))),
(NAME=address,TYPE(NAME='MD5'))
));

# DROP
DROP MASK TABLE? RULE (IF EXISTS)? t_mask;

# SHOW
SHOW MASK TABLE? (RULE ruleName | RULES) (FROM databaseName)?
```

### Tasks
- [x] CREATE MASK RULE
- [x] ALTER MASK RULE 
- [x] DROP MASK RULE 
- [x] SHOW MASK RULES | SHOW MASK RULE ruleName
- [x] Add DistSQL documents
- [x] Add test cases
- [x] COUNT MASK RULE
- [x] Update ExportDatabaseConfigurationHandler
- [x] Update ImportDatabaseConfigurationHandler
- [x] Update ConvertYamlConfigurationHandler

**Comment by RaigorJiang** [comment]
Welcome @Qianyi951015
