### ISSUE TITLE
Some of DistSQL RQL cannot query for the specified rule

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#24158]
Hi Guys,
  I just found some DistSQL RQL that should support query specified rule with rule name but actually they do not.

### For example `SHOW READWRITE_SPLITTING RULES`
it should support `SHOW READWRITE_SPLITTING RULE rule_name` but actually not. So we need to fix it.
![image](https://user-images.githubusercontent.com/57847965/218688151-2ea8d577-5121-426a-a62f-7d80aaf95f70.png)

### Task Check List

- [x] SHOW DB_DISCOVERY RULE
- [x] SHOW READWRITE_SPLITTING RULE
- [x] SHOW SHARDING TABLE REFERENCE RULE

**Comment by Qianyi951015** [comment]
i will fix it

**Comment by Qianyi951015** [comment]
finished
