### ISSUE TITLE
[GSOC 2023] Enhance ComputeNode reconciliation

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere#24212]
This is a mirror issue of https://github.com/apache/shardingsphere-on-cloud/issues/208

# Apache ShardingSphere

Apache ShardingSphere is positioned as a Database Plus, and aims at building a standard layer and ecosystem above heterogeneous databases. It focuses on how to reuse existing databases and their respective upper layer, rather than creating a new database. The goal is to minimize or eliminate the challenges caused by underlying databases fragmentation.

Page: https://shardingsphere.apache.org/
Github: https://github.com/apache/shardingsphere 

# Background

There is a proposal about new CRD Cluster and ComputeNode as belows:
- #167 
- #166 

Currently we try to promote ComputeNode as major CRD to represent a special ShardingSphere Proxy deployment. And plan to use Cluster indicating a special ShardingSphere Proxy cluster.

# Task

This issue is to enhance ComputeNode reconciliation availability. The specific case list is as follows.

- [ ] Add IT test case for Deployment spec volume
- [ ] Add IT test case for Deployment spec template init containers
- [ ] Add IT test case for Deployment spec template spec containers
- [ ] Add IT test case for Deployment spec volume mounts
- [ ] Add IT test case for Deployment spec container ports
- [ ] Add IT test case for Deployment spec container image tag
- [ ] Add IT test case for Service spec ports
- [ ] Add IT test case for ConfigMap data serverconfig
- [ ] Add IT test case for ConfigMap data logback

You need to 
 
Notice, these issues can be a good example.
- [https://github.com/apache/shardingsphere-on-cloud/pull/203](https://github.com/apache/shardingsphere-on-cloud/pull/203)

# Relevant Skills

1. Master Go language, Ginkgo test framework
2. Have a basic understanding of Apache ShardingSphere Concepts
3. Be familiar with Kubernetes Operator, kubebuilder framework

# Targets files

ComputeNode IT - https://github.com/apache/shardingsphere-on-cloud/blob/main/shardingsphere-operator/pkg/reconcile/computenode/compute_node_test.go
