### ISSUE TITLE
Support mainstream database metadata table query

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#24378]
## Background

ShardingSphere has designed its own metadata database to simulate metadata queries that support various databases.

More details:

https://github.com/apache/shardingsphere/issues/21268
https://github.com/apache/shardingsphere/issues/22052

## Task
- [ ] Support query for MySQL metadata `parameters`
- [ ] Support query for MySQL metadata `routines`
- [ ] Support query for MySQL metadata `accounts`

Notice, these issues can be a good example.

https://github.com/apache/shardingsphere/pull/22053
https://github.com/apache/shardingsphere/pull/22057/
https://github.com/apache/shardingsphere/pull/22166/
https://github.com/apache/shardingsphere/pull/22182

**Comment by chakkk309** [comment]
Hi @tuichenchuxin, I want to have a try.

**Comment by tuichenchuxin** [comment]
> Hi @tuichenchuxin, I want to have a try.

@chakkk309 Welcome. Maybe you can try one subtask first.

**Comment by kanha-gupta** [comment]
@tuichenchuxin Hey Are there any PRs made to add support for MySql metadata already ?
Thanks for the Examples provided, one more example Would help a lot.

**Comment by tuichenchuxin** [comment]
this issue refer to some prs may give you some example.
https://github.com/apache/shardingsphere/issues/22052

**Comment by HardbassMafia** [comment]
after half years,is there any new example for this issue?

**Comment by HardbassMafia** [comment]
@tuichenchuxin

**Comment by JustRun98** [comment]
I am not pretty sure if it is what you guys really expected

**Comment by JustRun98** [comment]
@tuichenchuxin 
excuse me.can you just take a look at the pr?I just wanna make sure that I understand it correctly.
if so,i will finish the remaining task within days

**Comment by strongduanmu** [comment]
Since these tables are already supported via SQL passthrough, I think this issue can be closed now.
