### ISSUE TITLE
[New Feature] Support MySQL sys.host_summary system table query

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#26086]
# Background
This task is a subtask of issue #24662.

Hi community.
ShardingSphere is committed to providing a multi-source heterogeneous, enhanced database platform and further building an ecosystem around the upper layer of the platform.
So ShardingSphere needs to be compatible with the inquiries of the system database of various types of databases, such as MySQL, PostgreSQL, and OpenGauss.

So we want to mock all system database tables and views query, return to the empty result.

# Tasks
In this issue, we will support empty queries for the following tables/views in MySQL `sys` schema:

- [ ] host_summary
- [ ]  host_summary_by_file_io
- [ ]  host_summary_by_file_io_type
- [ ]  host_summary_by_stages
- [ ]  host_summary_by_statement_latency

# Refer PR
You can refer to the following similar PR to complete the task.
MySQL: #25076, #25256, PostgreSQL: #25752

**Comment by zihaoAK47** [comment]
@FlyingZC  Hi mentor, can this task be assigned to me

**Comment by FlyingZC** [comment]
The current task has been completed, please refer to the parent task #24662, I will close this issue.
