### ISSUE TITLE
[New Feature] Support MySQL sys.host_summary_by_statement_type view empty query

### ISSUE THREAD

**Issue by wbcfwbe** [apache/shardingsphere#26106]
# Background
This task is a subtask of issue #24662.

Hi community.
ShardingSphere is committed to providing a multi-source heterogeneous, enhanced database platform and further building an ecosystem around the upper layer of the platform.
So ShardingSphere needs to be compatible with the inquiries of the system database of various types of databases, such as MySQL, PostgreSQL, and OpenGauss.

So we want to mock all system database tables and views query, return to the empty result.

# Tasks
In this issue, we will implement the empty query of the following system tables/views:
- [ ] host_summary_by_statement_type
- [ ] innodb_buffer_stats_by_schema
- [ ] innodb_buffer_stats_by_table
- [ ] innodb_lock_waits
- [ ] io_by_thread_by_latency

# Refer PR
You can refer to the following similar PR to complete the task.
MySQL: #25076, #25256, PostgreSQL: #25752

**Comment by zihaoAK47** [comment]
Hi, I would like to try to solve this problem

**Comment by wbcfwbe** [comment]
> Hi, I would like to try to solve this problem

Hi! Glad to hear! Thank you for interesting in this and our group ShardingSphere.

**Comment by zihaoAK47** [comment]
@strongduanmu Hi, mentor, please assign this question to me.

**Comment by wbcfwbe** [comment]
> @strongduanmu Hi, mentor, please assign this question to me.

The tasks have been assigned to you and we are Looking forward to your innovative ideas!

**Comment by FlyingZC** [comment]
The current task has been completed, please refer to the parent task #24662, I will close this issue.
