### ISSUE TITLE
[New Feature] Support PostgreSQL information_schema.check_constraints view empty query

### ISSUE THREAD

**Issue by wbcfwbe** [apache/shardingsphere#26131]
# Background
This task is a subtask of issue #24662.

Hi community.
ShardingSphere is committed to providing a multi-source heterogeneous, enhanced database platform and further building an ecosystem around the upper layer of the platform.
So ShardingSphere needs to be compatible with the inquiries of the system database of various types of databases, such as MySQL, PostgreSQL, and OpenGauss.

So we want to mock all system database tables and views query, return to the empty result.

# Tasks
In this issue, we will implement the empty query of the following system tables/views:
- [ ] check_constraints
- [ ] collation_character_set_applicability
- [ ] collations
- [ ] column_column_usage
- [ ] column_domain_usage

# Refer PR
You can refer to the following similar PR to complete the task.
MySQL: #25076, #25256, PostgreSQL: #25752

**Comment by FlyingZC** [comment]
The current task has been completed, please refer to the parent task #24662, I will close this issue.
