### ISSUE TITLE
[New Feature] Support openGauss pg_cataglog.gs_total_nodegroup_memory_detail view empty query

### ISSUE THREAD

**Issue by wbcfwbe** [apache/shardingsphere#26279]
# Background
This task is a subtask of issue #24662.

Hi community.
ShardingSphere is committed to providing a multi-source heterogeneous, enhanced database platform and further building an ecosystem around the upper layer of the platform.
So ShardingSphere needs to be compatible with the inquiries of the system database of various types of databases, such as MySQL, PostgreSQL, and OpenGauss.

So we want to mock all system database tables and views query, return to the empty result.

# Tasks
In this issue, we will implement the empty query of the following system tables/views:
- [ ] gs_total_nodegroup_memory_detail
- [ ] gs_wlm_cgroup_info
- [ ] gs_wlm_ec_operator_history
- [ ] gs_wlm_ec_operator_statistics
- [ ] gs_wlm_operator_history

# Refer PR
You can refer to the following similar PR to complete the task.
MySQL: #25076, #25256, PostgreSQL: #25752

**Comment by Master-sudo-doct** [comment]
你好，我能报名这个feature吗？

**Comment by wbcfwbe** [comment]
> 
当然！在认领 issue 后，有任何问题，欢迎添加社区助手微信：Jialin953，加入群聊，获取实时帮助，添加时请备注：认领 issue 。

**Comment by wbcfwbe** [comment]
> 你好，我能报名这个feature吗？

当然！在认领 issue 后，有任何问题，欢迎添加社区助手微信：Jialin953，加入群聊，获取实时帮助，添加时请备注：认领 issue 。

**Comment by FlyingZC** [comment]
The current task has been completed, please refer to the parent task #24662, I will close this issue.
