### ISSUE TITLE
[OSPP 2023 ]Solve unsupported PostgreSQL about SQL dialect for ShardingSphere Parser

### ISSUE THREAD

**Issue by wang-qingyang** [apache/shardingsphere#26801]
This issue is created to better track my PRs for OSPP 2023, you can view more about my project [here](https://summer-ospp.ac.cn/org/prodetail/235930269?list=org&navpage=org)

### Background

ShardingSphere Parser Engine helps users parse SQL statements into AST and generate corresponding SQL Statement objects from it.

How is a SQL parsed?
SQL definition file`
->(Parse to)
`AST`
->(Visit it)
`SQLStatment

### Process

1. Compare SQL definitions in [Oficial SQL Doc](https://www.postgresql.org/docs/14/sql-commands.html) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/parser/sql/dialect/postgresql/src/main/antlr4/imports/postgresql)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc
3. refer to [PostgreSql source code](https://github.com/postgres/postgres/tree/master/src/backend/parser/gram.y)
4. Run mvn install the current_file_module
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class)
6. Add new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/test/it/parser/src/main/resources/sql/supported) and expected parsed result in[ Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/test/it/parser/src/main/resources/case)
7. Run [InternalPostgreSQLParserIT](https://github.com/apache/shardingsphere/tree/master/test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalSQLParserIT.java) and [InternalUnsupportedSQLParserIT](https://github.com/apache/shardingsphere/tree/master/test/it/parser/src/main/java/org/apache/shardingsphere/test/it/sql/parser/internal/InternalUnsupportedSQLParserIT.java)  to make sure no exceptions.

### Tasks

- [x] EXECUTE

- [ ] CREATE TEMPORARY

- [ ] CREATE TALBE AS SELECT
- [ ] CREATE TEMP TABLE AS SELECT
- [ ] INSERT INTO VALUES WITH SPECIAL FUNCTION
- [ ] SELECT PROJECTION WITH SPECIAL FUNCTION
- [ ] EXPLAIN
- [ ] CRATE FUNCTION
- [x] ALTER TYPE
- [ ] INSERT INTO SELECT
- [ ] MERGE INTO
- [ ] FUNCTION
- [ ] PROCEDURE
- [ ] CREATE TABLE
- [ ] CREATE TRIGGER
- [ ] CREATE USER
- [ ] CREATE VIEW

This issue is a ref to https://github.com/apache/shardingsphere/issues/14104 and https://github.com/apache/shardingsphere/issues/18496
