### ISSUE TITLE
[OSPP 2023 ]Enhance SQLNodeConverterEngine to support more MySQL/PostgreSQL/opengauss SQL statements.

### ISSUE THREAD

**Issue by cardigan1008** [apache/shardingsphere#26871]
This issue is created to track my PRs for OSPP 2023. 

### Background

 ShardingSphere SQL federation engine provides support for complex SQL statements, which can well support cross-database connection queries, subqueries, aggregate queries, and other statements. An important part of the SQL federation engine is to convert the SQL statements parsed by ShardingSphere into SqlNode and use Calcite to implement SQL optimization and federated queries.

### Task

Resolve issues that occur during the conversion process of  SQLNodeConverterEngine for MySQL/PostgreSQL/opengauss. The specific  exception case list is as follows.

- [x] select_extract_function
- [x] select_group_by_with_having_and_window
- [x] select_not_between_with_single_table
- [x] select_not_in_with_single_table
- [x] select_string_constant_type_cast
- [x] select_where_with_predicate_with_in_subquery
- [x] select_with_case_when_then_in_group_by_item_and_order_by_item
- [x] select_with_database_name_and_schema_name_in_table
- [x] select_with_dollar_parameter_for_postgresql
- [x] select_with_exists_sub_query_with_project
- [x] select_where_with_simple_expr_with_not
- [x] select_where_with_simple_expr_with_odbc_escape_syntax
- [x] select_where_with_simple_expr_with_row
- [x] select_where_with_simple_expr_with_tilde
- [x] select_where_with_simple_expr_with_variable
- [x] select_window_function
- [x] select_with_assignment_operator
- [x] select_with_assignment_operator_and_keyword
- [x] select_with_case_expression
- [x] select_with_collate_with_marker
- [x] select_with_date_format_function
- [x] select_with_exists_sub_query_with_project
- [x] select_with_function_name
- [x] select_with_json_value_return_type
- [x] select_with_match_against
- [x] select_with_regexp
- [x] select_with_schema_name_in_column_projection
- [x] select_with_schema_name_in_shorthand_projection
- [x] select_with_spatial_function
- [x] select_with_trim_expr
- [x] select_with_trim_expr_from_expr

####

**Comment by cardigan1008** [comment]
Hi @strongduanmu , could you please assign this issue to me? Thank you.

**Comment by strongduanmu** [comment]
> Hi @strongduanmu , could you please assign this issue to me? Thank you.

@cardigan1008 Assigned, welcome to ospp 2023.
