### ISSUE TITLE
Support MySQL insert statement convert to SqlInsert to improve sql federation support

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#27376]
## Background

On the master branch, [SQLNodeConverterEngine](https://github.com/apache/shardingsphere/blob/master/kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java) already supports the conversion of most SelectStatement statements, which provides a good foundation for sql federation. In order to improve the support of sql federation for INSERT statements and complex statements such as insert select, we need to support the conversion of InsertStatement in SQLNodeConverterEngine.

## Task

- [ ] add InsertStatementConverter implement, you can refer - https://github.com/polardb/polardbx-sql/blob/cdd976850bdfc3264dff279198b6b06eb8641fbe/polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/parse/visitor/FastSqlToCalciteNodeVisitor.java#L1001
- [ ] add InsertStatementConverter call logic in SQLNodeConverterEngine
- [ ] add insert statement convert test case in `resources/converter` directory

**Comment by boyjoy1127** [comment]
I'd like to take care of this issue.

**Comment by boyjoy1127** [comment]
> I'd like to take care of this issue.

@strongduanmu

**Comment by strongduanmu** [comment]
@boyjoy1127 Welcome, I just assign this issue to you.
