### ISSUE TITLE
Support MySQL delete statement convert to SqlDelete to improve sql federation support

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#27377]
## Background

On the master branch, [SQLNodeConverterEngine](https://github.com/apache/shardingsphere/blob/master/kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java) already supports the conversion of most SelectStatement statements, which provides a good foundation for sql federation. In order to improve the support of sql federation for DELETE statements and complex statements such as delete join, we need to support the conversion of DeleteStatement in SQLNodeConverterEngine.

MySQL delete statement doc - https://dev.mysql.com/doc/refman/8.0/en/delete.html

```
DELETE [LOW_PRIORITY] [QUICK] [IGNORE] FROM tbl_name [[AS] tbl_alias]
    [PARTITION (partition_name [, partition_name] ...)]
    [WHERE where_condition]
    [ORDER BY ...]
    [LIMIT row_count]

DELETE [LOW_PRIORITY] [QUICK] [IGNORE]
    tbl_name[.*] [, tbl_name[.*]] ...
    FROM table_references
    [WHERE where_condition]

DELETE [LOW_PRIORITY] [QUICK] [IGNORE]
    FROM tbl_name[.*] [, tbl_name[.*]] ...
    USING table_references
    [WHERE where_condition]
```

## Task

- [ ] add DeleteStatementConverter implement, you can refer - https://github.com/polardb/polardbx-sql/blob/cdd976850bdfc3264dff279198b6b06eb8641fbe/polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/parse/visitor/FastSqlToCalciteNodeVisitor.java#L1308
- [ ] add DeleteStatementConverter call logic in SQLNodeConverterEngine
- [ ] add delete statement convert test case in `resources/converter` directory

**Comment by kanha-gupta** [comment]
@strongduanmu assign it to me please :)

**Comment by strongduanmu** [comment]
@kanha-gupta Welcome.

**Comment by kanha-gupta** [comment]
@strongduanmu All test cases have been supported. Can we close this issue ?
There were few remaining for which I had created an issue https://github.com/apache/shardingsphere/issues/28328

**Comment by strongduanmu** [comment]
Hi @kanha-gupta, I have added support for oracle for this task, may I ask whether the implementation of oracle has been included?

**Comment by kanha-gupta** [comment]
@strongduanmu Thank you for notifying me with this. I will add support for it ASAP.
