### ISSUE TITLE
Support load unique key.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#28035]
## Feature Request

in ShardingSphereIndex ，we have added unique and columns field for mysql.
Ref to #27611

## Tasks

- [x] support load unique key for mysql 
- [x] support load unique key for oracle @dongzl (https://docs.oracle.com/cd/B13789_01/server.101/b10755/statviews_1061.htm)
- [x] support load unique key for postgres @dongzl (https://www.postgresql.org/docs/current/catalog-pg-index.html)
- [ ] support load unique key for opengauss @chakkk309 (https://docs.opengauss.org/zh/docs/1.1.0/docs/Developerguide/PG_INDEX.html)
- [x] support load unique key for h2 @sindhunaydu (https://www.h2database.com/html/systemtables.html#information_schema_indexes)
- [x] support load unique key for sqlserver @totalo (https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-indexes-transact-sql?view=sql-server-ver16)

## how to do this
- first, collect unique key in DialectMetaDataLoader
ref to https://github.com/apache/shardingsphere/pull/27611/files#diff-1215f61d9f15bbcac2b81993189ca23ee7b52be1769e8a0432f9a62a35b1faa4R58-R170 
- second, add test
ref to https://github.com/apache/shardingsphere/pull/27611/files#diff-1f10af74fe3812b21e842090741744d94629db1cd68942e63fba05a971d36906L56-L128

**Comment by dongzl** [comment]
I will try it, for `postgres`.

**Comment by totalo** [comment]
I want to solve the problem about sqlserver.

**Comment by sindhunaydu** [comment]
hi, I would like to work on adding support for H2.

**Comment by strongduanmu** [comment]
> hi, I would like to work on adding support for H2.

@sindhunaydu Of course, I will assign this sub task to you.

**Comment by chakkk309** [comment]
Hi, I want to support the `opengauss` one.

**Comment by dongzl** [comment]
I will do for `Oracle`.

**Comment by sindhunaydu** [comment]
Hi All, thanks for assigning this task to me, I'm very new to all of this and would like some guidance and suggestions. I have been looking into the documentation and have a some questions,

1. do I need to modify the existing INDEX_META_DATA_SQL or add a new String?
2. the [H2 documentation](https://www.h2database.com/html/systemtables.html#information_schema_indexes) shows that the name of the unique index is UNIQUE INDEX. I don't see any column field in the H2 docs. Do I need to only add UNIQUE INDEX?
3. do I also need to add new PreparedStatement logic in loadIndexMetaDataMap() as well?

Thanks!

**Comment by dongzl** [comment]
> Hi All, thanks for assigning this task to me, I'm very new to all of this and would like some guidance and suggestions. I have been looking into the documentation and have a some questions,
> 
> 1. do I need to modify the existing INDEX_META_DATA_SQL or add a new String?
> 2. the [H2 documentation](https://www.h2database.com/html/systemtables.html#information_schema_indexes) shows that the name of the unique index is UNIQUE INDEX. I don't see any column field in the H2 docs. Do I need to only add UNIQUE INDEX?
> 3. do I also need to add new PreparedStatement logic in loadIndexMetaDataMap() as well?
> 
> Thanks!

1. Don't need a new String, I think use `INDEX_META_DATA_SQL` directly.
2. use `UNIQUE INDEX` is OK.
3. no need, use `loadIndexMetaDataMap()` directly.

**Comment by sindhunaydu** [comment]
> > Hi All, thanks for assigning this task to me, I'm very new to all of this and would like some guidance and suggestions. I have been looking into the documentation and have a some questions,
> > 
> > 1. do I need to modify the existing INDEX_META_DATA_SQL or add a new String?
> > 2. the [H2 documentation](https://www.h2database.com/html/systemtables.html#information_schema_indexes) shows that the name of the unique index is UNIQUE INDEX. I don't see any column field in the H2 docs. Do I need to only add UNIQUE INDEX?
> > 3. do I also need to add new PreparedStatement logic in loadIndexMetaDataMap() as well?
> > 
> > Thanks!
> 
> 1. Don't need a new String, I think use `INDEX_META_DATA_SQL` directly.
> 2. use `UNIQUE INDEX` is OK.
> 3. no need, use `loadIndexMetaDataMap()` directly.

@dongzl thanks for the info. I made the changes and ran the H2MetaDataLoaderTest locally and the tests passed. when I ran the `./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e` command the `YamlEngineTest` tests (3 tests are failing) are failing with the following error message - 
`java.nio.file.NoSuchFileException: /../shardingsphere/infra/util/target/test-classes/yaml/shortcuts-fixture.yaml`

I do see the file in that specific location, yet the test is saying that file does not exist. Have you seen this error before? Am I missing anything? 
I was able to build the app locally using [this command](https://github.com/apache/shardingsphere/wiki#build-apache-shardingsphere) successfully - 
`./mvnw clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true -B`

**Comment by chakkk309** [comment]
Hi all, I haven't found the `OpenGaussMetaDataLoaderTest` file in the according directory. So should I create a new file and write the Test or do other things?

**Comment by tuichenchuxin** [comment]
> Hi all, I haven't found the `OpenGaussMetaDataLoaderTest` file in the according directory. So should I create a new file and write the Test or do other things?

I found `OpenGaussSchemaMetaDataLoaderTest`, you may use this.

**Comment by tuichenchuxin** [comment]
@chakkk309 what about this progress. we plan to release tomorrow。

**Comment by chakkk309** [comment]
> @chakkk309 what about this progress. we plan to release tomorrow。

still in progress and I need some time to check it. Please free to take this task away or put it in the next milestone.

**Comment by tuichenchuxin** [comment]
> > @chakkk309 what about this progress. we plan to release tomorrow。
> 
> still in progress and I need some time to check it. Please free to take this task away or put it in the next milestone.

@chakkk309 Since this task is related to some other dependent tasks, can you submit the draft? I will continue to do it together, or I will do it independently.

**Comment by chakkk309** [comment]
> > > @chakkk309 what about this progress. we plan to release tomorrow。
> > 
> > 
> > still in progress and I need some time to check it. Please free to take this task away or put it in the next milestone.
> 
> @chakkk309 Since this task is related to some other dependent tasks, can you submit the draft? I will continue to do it together, or I will do it independently.

SorryI dont have computer equipment around, so i think u can do it by your side it more better for the time limited.
