### ISSUE TITLE
Support MySQL/Oracle drop table statement convert to SqlDropTable to improve sql federation support

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#28753]
## Background

On the master branch, [SQLNodeConverterEngine](https://github.com/apache/shardingsphere/blob/master/kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java) already supports the conversion of most SelectStatement statements, which provides a good foundation for sql federation. In order to improve the support of sql federation for drop table statement, we need to support the conversion of DropTableStatement in SQLNodeConverterEngine.

MySQL drop table statement doc - https://dev.mysql.com/doc/refman/8.0/en/drop-table.html

```
DROP [TEMPORARY] TABLE [IF EXISTS]
    tbl_name [, tbl_name] ...
    [RESTRICT | CASCADE]
```

Oracle drop table statement doc - https://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_9003.htm

## Task

- [ ] add DropTableStatementConverter implement, you can refer - https://github.com/polardb/polardbx-sql/blob/cdd976850bdfc3264dff279198b6b06eb8641fbe/polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/parse/visitor/FastSqlToCalciteNodeVisitor.java#L786
- [ ] add DropTableStatementConverter call logic in SQLNodeConverterEngine
- [ ] add drop table statement convert test case in `resources/converter` directory

**Comment by chakkk309** [comment]
Hi, i would like to try it, plz assign to me~

**Comment by strongduanmu** [comment]
@chakkk309 Welcome back.

**Comment by strongduanmu** [comment]
Since Calcite has very low support for DDL, this task is difficult to complete and I will close it.
