### ISSUE TITLE
Support Oracle merge statement convert to SqlMerge to improve sql federation support

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#28754]
## Background

On the master branch, [SQLNodeConverterEngine](https://github.com/apache/shardingsphere/blob/master/kernel/sql-federation/core/src/main/java/org/apache/shardingsphere/sqlfederation/compiler/converter/SQLNodeConverterEngine.java) already supports the conversion of most SelectStatement statements, which provides a good foundation for sql federation. In order to improve the support of sql federation for merge statement, we need to support the conversion of MergeStatement in SQLNodeConverterEngine.

Oracle merge statement doc - https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/MERGE.html#GUID-5692CCB7-24D9-4C0E-81A7-A22436DC968F

## Task

- [ ] add DropTableStatementConverter implement, you can refer - https://github.com/polardb/polardbx-sql/blob/cdd976850bdfc3264dff279198b6b06eb8641fbe/polardbx-optimizer/src/main/java/com/alibaba/polardbx/optimizer/parse/visitor/FastSqlToCalciteNodeVisitor.java#L786
- [ ] add DropTableStatementConverter call logic in SQLNodeConverterEngine
- [ ] add drop table statement convert test case in `resources/converter` directory

**Comment by kanha-gupta** [comment]
@strongduanmu Please assign :)

**Comment by strongduanmu** [comment]
@kanha-gupta Welcome, I just assign this issue to you.
