### ISSUE TITLE
Consider removing sqlCommentParseEnabled config in SQLParser rule

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#29535]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

In #20736, ShardingSphere provides support for SQL hints. Currently, there are two ways to extract SQLHint syntax, one is using SQL Parser and the other is using SQLHintUtils. If both methods are supported at the same time, the processing logic of SQL Hint is too complicated, and HintValueContext may already be used before props are extracted. This affects the SQL Hint use experience.

<img width="1148" alt="image" src="https://github.com/apache/shardingsphere/assets/10829171/71226d1a-1c86-4118-8a86-e009ae953102">

Considering that SQLHintUtils has been used as the default method for a long time, SQLHint has better functionality and performance than SQL Parser, so consider removing the sqlCommentParseEnabled parameter. And remove the way SQL Parser extracts SQL Hint syntax.

The current configuration of SQL Parser Rule:

```yaml
#sqlParser:
#  sqlCommentParseEnabled: false
#  sqlStatementCache:
#    initialCapacity: 2000
#    maximumSize: 65535
#  parseTreeCache:
#    initialCapacity: 128
#    maximumSize: 1024
```

And the new SQL Parser Rule configuration:

```yaml
#sqlParser:
#  sqlStatementCache:
#    initialCapacity: 2000
#    maximumSize: 65535
#  parseTreeCache:
#    initialCapacity: 128
#    maximumSize: 1024
```

### Tasks

- [x] remove sqlCommentParseEnabled in SQL Parser Rule and kernel
- [x] remove sqlCommentParseEnabled in DistSQL
- [ ] remove sqlCommentParseEnabled in doc, and update SQL Hint usage description - https://shardingsphere.apache.org/document/current/en/user-manual/common-config/sql-hint/

**Comment by strongduanmu** [comment]
@TherChenYang Welcome, I will assign it to you.

**Comment by strongduanmu** [comment]
> Hello, it seems that I couldn't find how to use SQLParser to parse SHARDINGSPHERE_HINT in comments, Many places are parsed using SQLHintUtils. Could you please guide me?

You can try to remove sqlCommentParseEnabled first. And you will find the logic in SQL Parser module.

**Comment by strongduanmu** [comment]
@TherChenYang There are two types of annotations, ShardingSphere annotations, which are extracted using SQLHintUtils and then removed from the SQL. The second is native SQL comments, which need to be skipped instead of parsed into CommentSegment, because the ShardingSphere does not process native SQL comments.

**Comment by strongduanmu** [comment]
Perhaps we could also preserve the parsing of native SQL annotations, which might be required for sql federation queries.

**Comment by strongduanmu** [comment]
Since the document has not been updated, I will reopen the issue.
