### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31458]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
CREATE RESOURCE "remote_s3" PROPERTIES (    "type" = "s3",    "s3.endpoint" = "bj.s3.com",    "s3.region" = "bj",    "s3.access_key" = "bbb",    "s3.secret_key" = "aaaa",    -- the followings are optional    "s3.connection.maximum" = "50",    "s3.connection.request.timeout" = "3000",    "s3.connection.timeout" = "1000" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE/)

```
CREATE RESOURCE "remote_s3" PROPERTIES (    "type" = "s3",    "s3.endpoint" = "bj.s3.com",    "s3.region" = "bj",    "s3.access_key" = "bbb",    "s3.secret_key" = "aaaa",    -- required by cooldown    "s3.root.path" = "/path/to/root",    "s3.bucket" = "test-bucket" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE/)

```
CREATE RESOURCE mysql_resource PROPERTIES (    "type"="jdbc",    "user"="root",    "password"="123456",    "jdbc_url" = "jdbc:mysql://127.0.0.1:3316/doris_test?useSSL=false",    "driver_url" = "https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/jdbc_driver/mysql-connector-java-8.0.25.jar", "driver_class" = "com.mysql.cj.jdbc.Driver" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE/)

```
CREATE RESOURCE hdfs_resource PROPERTIES (    "type"="hdfs",    "username"="user",    "password"="passwd",    "dfs.nameservices" = "my_ha",    "dfs.ha.namenodes.my_ha" = "my_namenode1, my_namenode2",    "dfs.namenode.rpc-address.my_ha.my_namenode1" = "nn1_host:rpc_port",    "dfs.namenode.rpc-address.my_ha.my_namenode2" = "nn2_host:rpc_port",    "dfs.client.failover.proxy.provider" = "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE/)

```
CREATE RESOURCE hms_resource PROPERTIES (    'type'='hms',    'hive.metastore.uris' = 'thrift://127.0.0.1:7004',    'dfs.nameservices'='HANN',    'dfs.ha.namenodes.HANN'='nn1,nn2',    'dfs.namenode.rpc-address.HANN.nn1'='nn1_host:rpc_port',    'dfs.namenode.rpc-address.HANN.nn2'='nn2_host:rpc_port',    'dfs.client.failover.proxy.provider.HANN'='org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider' )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE/)

```
CREATE RESOURCE es_resource PROPERTIES (    "type"="es",    "hosts"="http://127.0.0.1:29200",    "nodes_discovery"="false",    "enable_keyword_sniff"="true" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE/)

```
CREATE, RESOURCE
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE/)

```
LOAD DATA LOCAL INFILE 'testData' INTO TABLE testDb.testTbl PROPERTIES ("timeout"="100")
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/MYSQL-LOAD/)

```
LOAD DATA INFILE '/root/testData' INTO TABLE testDb.testTbl PROPERTIES ("timeout"="100")
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/MYSQL-LOAD/)

```
LOAD DATA LOCAL INFILE 'testData' INTO TABLE testDb.testTbl PROPERTIES ("max_filter_ratio"="0.2")
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/MYSQL-LOAD/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by Kiritsgu** [comment]
@iamhucong Hi, please assign it to me. Thank you!

**Comment by terrymanu** [comment]
Due to prolonged inactivity, I have reclaimed the task assignment. This issue is now reopened and available for contributors to claim.

**Comment by terrymanu** [comment]
Hi @iamhucong, all SQL cases listed in this issue are now supported on the current master, so we can close it as completed.

- The 6 `CREATE RESOURCE` cases are supported by #39552, which adds the `CREATE [EXTERNAL] RESOURCE ... PROPERTIES` grammar rule, `DorisCreateResourceStatement`, and parser IT cases covering double-quoted, unquoted, and back-quoted resource names, single/double-quoted properties, and the optional `EXTERNAL` prefix.
- The `LOAD DATA ... PROPERTIES` cases are supported by #38368, which adds `dorisLoadDataStatement` with the trailing `PROPERTIES` clause, including the exact IT case `LOAD DATA LOCAL INFILE 'testData' INTO TABLE testDb.testTbl PROPERTIES ("timeout"="100")` and the non-`LOCAL` / `max_filter_ratio` variants.
- The `CREATE, RESOURCE` snippet is a scraping artifact of the Doris docs page rather than a valid SQL statement, so no grammar change is needed for it.

Closing this issue as completed. Thanks for everyone's contribution!
