### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31462]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
DROP, FILE
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Drop/DROP-FILE/)

```
WINDOW,FUNCTION,ROW_NUMBER
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-row-number/)

```
DOUBLE ST_Area_Square_Meters(GEOMETRY geo) DOUBLE ST_Area_Square_Km(GEOMETRY geo)
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/spatial-functions/st-area/)

```
SELECT   row_number() OVER (ORDER BY date_and_time) AS id,   c1, c2, c3, c4   FROM events
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/window-functions/WINDOW-FUNCTION/)

```
ROWS BETWEEN [ { m | UNBOUNDED } PRECEDING | CURRENT ROW] [ AND [CURRENT ROW | { UNBOUNDED | n } FOLLOWING] ]
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/window-functions/WINDOW-FUNCTION/)

```
WINDOW,FUNCTION
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/window-functions/WINDOW-FUNCTION/)

```
ADMIN CLEAN TRASH
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-CLEAN-TRASH/)

```
ADMIN CLEAN TRASH ON ("192.168.0.1:9050","192.168.0.2:9050")
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-CLEAN-TRASH/)

```
BACKUP SNAPSHOT example_db.snapshot_label1 TO example_repo ON (example_tbl) PROPERTIES ("type" = "full")
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Backup-and-Restore/BACKUP/)

```
BACKUP SNAPSHOT example_db.snapshot_label2 TO example_repo ON (     example_tbl PARTITION (p1,p2),     example_tbl2 )
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Backup-and-Restore/BACKUP/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by daguimu** [comment]
Quick triage note while working on related Doris parsing items — several of the unchecked entries on this list appear to already be covered by merged PRs on current master, which may help clean up the checklist:

- `DROP, FILE` — covered by #38050 ("Support parsing Doris CREATE/DROP FILE syntax", merged).
- `ADMIN CLEAN TRASH ON ("ip:port", ...)` — the existing `adminCleanTrash` rule in `DALStatement.g4` already allows the optional `ON LP_ string_ (COMMA_ string_)* RP_` clause, so both the base form and the `ON (...)` variant parse.
- `BACKUP SNAPSHOT example_db.snapshot_label TO example_repo ON (example_tbl) PROPERTIES (...)` and the partitioned variant — the `backup` rule in `DALStatement.g4` already handles `GLOBAL? SNAPSHOT (databaseName DOT_)? identifier TO repositoryName backupScope? propertiesClause?` with `backupScope` supporting `ON LP_ backupTableSpec ... RP_` (including `PARTITION (...)` on each spec).
- `ST_Area_Square_Meters(GEOMETRY)` / `ST_Area_Square_Km(GEOMETRY)` — these are Doris spatial *functions*, not standalone statements, so they already parse through the generic `functionCall → regularFunction` path without a dedicated grammar rule.

If that matches maintainers' reading, these boxes can likely be ticked off as done. Let me know if I am missing any nuance on any of them. I am happy to do a similar triage sweep on the other Doris umbrella issues (#31470, #31472, #31473, #31474, #31475, ...) in follow-up comments if that would be useful.

**Comment by terrymanu** [comment]
Hi @daguimu, thanks for the triage — your reading is correct.

I verified the remaining items against current master:

- `DROP FILE` is supported since #38050, with test cases in `sql/supported/ddl/drop-file.xml`.
- `ADMIN CLEAN TRASH ON ("ip:port", ...)` is supported since #38379; the `adminCleanTrash` rule in `DALStatement.g4` covers the optional `ON (...)` clause and `admin-clean-trash.xml` contains the exact backend-list case.
- Both `BACKUP SNAPSHOT` variants are supported since #38293; `backupScope`/`backupTableSpec` handle `ON (...)`, `PARTITION (...)` and `PROPERTIES`, with exact cases in `backup.xml`.
- `ST_Area_Square_Meters()` / `ST_Area_Square_Km()` are regular function calls parsed through the generic `functionCall` path, so no dedicated grammar rule is needed.

All ten items in this list are now covered on master. I am ticking the remaining checkboxes and closing this issue as completed. A similar sweep on the other Doris umbrella issues (#31470, #31472, #31473, #31474, #31475) would be welcome.
