### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31472]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
CREATE ROUTINE LOAD example_db.test1 PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "20",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200",     "strict_mode" = "false" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "property.group.id" = "xxx",     "property.client.id" = "xxx",     "property.kafka_default_offsets" = "OFFSET_BEGINNING" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test1 ON example_tbl COLUMNS(k1, k2, k3, v1, v2, v3 = k1 * 100), PRECEDING FILTER k1 = 1, WHERE k1 > 100 and k2 like "%doris%" PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "20",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200",     "strict_mode" = "true" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "kafka_partitions" = "0,1,2,3",     "kafka_offsets" = "101,0,0,200" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test1 ON example_tbl COLUMNS(k1, k2, k3, v1, v2, v3 = k1 * 100), WHERE k1 > 100 and k2 like "%doris%" PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "20",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200",     "strict_mode" = "false",     "timezone" = "Africa/Abidjan" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "property.security.protocol" = "ssl",     "property.ssl.ca.location" = "FILE:ca.pem",     "property.ssl.certificate.location" = "FILE:client.pem",     "property.ssl.key.location" = "FILE:client.key",     "property.ssl.key.password" = "abcdefg",     "property.client.id" = "my_client_id" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test_json_label_1 ON table1 COLUMNS(category,price,author) PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "20",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200",     "strict_mode" = "false",     "format" = "json" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "kafka_partitions" = "0,1,2",     "kafka_offsets" = "0,0,0" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test1 ON example_tbl COLUMNS(category, author, price, timestamp, dt=from_unixtime(timestamp, '%Y%m%d')) PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "20",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200",     "strict_mode" = "false",     "format" = "json",     "jsonpaths" = "[\"$.category\",\"$.author\",\"$.price\",\"$.timestamp\"]",     "json_root" = "$.RECORDS"     "strip_outer_array" = "true" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "kafka_partitions" = "0,1,2",     "kafka_offsets" = "0,0,0" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test1 ON example_tbl WITH MERGE COLUMNS(k1, k2, k3, v1, v2, v3), WHERE k1 > 100 and k2 like "%doris%", DELETE ON v3 >100 PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "20",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200",     "strict_mode" = "false" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "kafka_partitions" = "0,1,2,3",     "kafka_offsets" = "101,0,0,200" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test_job ON example_tbl COLUMNS TERMINATED BY ",", COLUMNS(k1,k2,source_sequence,v1,v2), ORDER BY source_sequence PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "30",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "kafka_partitions" = "0,1,2,3",     "kafka_offsets" = "101,0,0,200" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test_job ON example_tbl PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "30",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092",     "kafka_topic" = "my_topic",     "kafka_default_offsets" = "2021-05-21 10:00:00" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE, ROUTINE, LOAD, CREATE LOAD
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
 select `n_nationkey`, `n_name`, `n_regionkey` from `nation`
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/aggregate-functions/bitmap_agg/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for reporting this.

All Doris ROUTINE LOAD parsing cases in this issue have been completed and merged via #38137, #38144 and #38149, and the corresponding parser test cases are already in the repository.

The only unchecked case (`select \`n_nationkey\`, \`n_name\`, \`n_regionkey\` from \`nation\``, linked to the Doris bitmap_agg page) is a plain backtick-quoted SELECT that parses successfully with the MySQL dialect without any code change, and its source link is no longer valid. Per the issue rules, no test assert file is needed for such cases.

I am closing this issue as completed. Feel free to reopen it if you find any Doris SQL that still fails to parse.
