### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31479]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
CREATE, FILE
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-FILE/)

```
DROP DATABASE [IF EXISTS] db_name [FORCE];
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Drop/DROP-DATABASE/)

```
DROP DATABASE db_test
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Drop/DROP-DATABASE/)

```
DROP, DATABASE
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Drop/DROP-DATABASE/)

```
DESC[RIBE] [db_name.]table_name [ALL]
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Utility-Statements/DESCRIBE/)

```
DESC table_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Utility-Statements/DESCRIBE/)

```
DESC db1.table_name ALL
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Utility-Statements/DESCRIBE/)

```
DESCRIBE, DESC
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Utility-Statements/DESCRIBE/)

```
SYNC
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Utility-Statements/SYNC/)

```
SYNC
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Utility-Statements/SYNC/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by byp411426** [comment]
Hi, I would like to work on the remaining Doris **DROP DATABASE** parser cases, including the optional **FORCE** clause. I plan to submit a draft PR by August 12, 2026.

I will first verify the current Doris syntax and ShardingSphere parser behavior, then make the smallest grammar/visitor and parser-test changes required.

AI assistance disclosure: I will use OpenAI Codex for code navigation, implementation support, and test orchestration. I will review, understand, and validate every change before submitting it.

**Comment by byp411426** [comment]
Update after checking the current master branch: the remaining Doris **DROP DATABASE** cases were already implemented by #38443, merged on March 15, 2026 for #31470.

The merged change:
- added the optional **FORCE** clause to `dropDatabase` in `parser/sql/engine/dialect/doris/src/main/antlr4/imports/doris/DDLStatement.g4`;
- added parser cases for `DROP DATABASE db_test FORCE`, `DROP DATABASE IF EXISTS db_test FORCE`, and `DROP DATABASE db_test` in `test/it/parser/src/main/resources/sql/supported/ddl/drop-database.xml`.

I will not open a duplicate PR. Please disregard my claim above; this issue appears stale for the **DROP DATABASE** portion.

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for initiating this Doris SQL parsing tracking issue. All the SQL cases listed here are now supported on the current master, so this issue can be closed as completed.

- The remaining `DROP DATABASE [IF EXISTS] db_name [FORCE]` cases were implemented by #38443 (for #31470): `dropDatabase` in `parser/sql/engine/dialect/doris/src/main/antlr4/imports/doris/DDLStatement.g4` now accepts `IF EXISTS` and the optional `FORCE` clause, with the parser cases `drop_database_doris_force`, `drop_database_doris_if_exists_force`, and `drop_database_doris_without_force` in `test/it/parser/src/main/resources/sql/supported/ddl/drop-database.xml`.
- `CREATE FILE` is covered by the Doris cases in `sql/supported/ddl/create-file.xml`.
- `DESC[RIBE] [db_name.]table_name [ALL]` is covered by the `explain` rule in `doris/DALStatement.g4` and the `desc_table_all_doris` case in `sql/supported/dal/describe.xml`.
- `SYNC` is covered by `sql/supported/dal/sync.xml`.

Closing this issue as completed. Thanks to everyone who contributed to these cases.
