### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31477]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
SELECT DATE('2003-12-31 01:02:03')
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-types/Data-Types/DATE/)

```
DATE
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-types/Data-Types/DATE/)

```
MySQL [(none)]> select null_or_empty(null)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/string-functions/null-or-empty/)

```
ALTER SQL_BLOCK_RULE test_rule PROPERTIES("sql"="select \\* from test_table","enable"="true")
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-SQL-BLOCK-RULE/)

```
ALTER SQL_BLOCK_RULE test_rule2 PROPERTIES("partition_num" = "10","tablet_num"="300","enable"="true")
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-SQL-BLOCK-RULE/)

```
ALTER,SQL_BLOCK_RULE
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-SQL-BLOCK-RULE/)

```
Only supported in vectorized engine
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/aggregate-functions/collect-set/)

```
TaskId: d67ce537f1be4b86-abf47530b79ab8e6                TxnId: 4            TxnStatus: UNKNOWN                JobId: 10280           CreateTime: 2020-12-12 20:29:48     ExecuteStartTime: 2020-12-12 20:29:48              Timeout: 20                 BeId: 10002 DataSourceProperties: {"0":19}
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Show-Statements/SHOW-ROUTINE-LOAD-TASK/)

```
The final filename will consist of `my_file_`, the file number and the file format suffix. The file serial number starts from 0, and the number is the number of files to be divided. Such as: my_file_abcdefg_0.csv my_file_abcdefg_1.csv my_file_abcdegf_2.csv
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/OUTFILE/)

```
FORMAT AS CSV
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/OUTFILE/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for initiating this Doris SQL parsing tracking issue. We have verified all the remaining unchecked cases against the current master, and each one is either already supported or an invalid scraped fragment, so this issue can be closed as completed.

**Already supported (verified with the current Doris parser):**

- `select null_or_empty(null)` parses successfully. Any regular identifier is accepted as a function name by `regularFunctionName` in `BaseRule.g4` of the Doris dialect, and `NULL` is a valid argument literal.
- `ALTER SQL_BLOCK_RULE test_rule PROPERTIES("sql"="select \\* from test_table","enable"="true")` was already covered by PR #37817, which added the identical sql-case `alter_sql_block_rule_with_sql` with its assertion in the parser test resources. This checkbox was simply not ticked.
- The `SELECT ... INTO OUTFILE ... FORMAT AS ...` syntax is already supported by the Doris `DMLStatement.g4` grammar, and `SHOW ROUTINE LOAD TASK` was also implemented in PR #37817.

**Invalid fragments produced by the web scraper (not SQL statements):**

- `DATE` — a type name extracted from the DATE data-type documentation page.
- The `TaskId: ... TxnStatus: UNKNOWN ...` block — output of `SHOW ROUTINE LOAD TASK`, not a statement itself.
- `The final filename will consist of ...` — documentation prose from the OUTFILE page.
- `FORMAT AS CSV` — a clause fragment of `OUTFILE`, not a standalone statement.

Since every remaining case is either already supported or not valid SQL, no further code change is required. We are closing this issue as completed. Thanks again to everyone who contributed to Doris SQL parsing.
