### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31471]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
CANCEL, MATERIALIZED, VIEW, TASK
```

- [x] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Utility-Statements/CANCEL-MATERIALIZED-VIEW-TASK/)

```
KeysType: AGG_KEY Columns: tag varchar, date datetime, user_id bitmap bitmap_union
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/bitmap-functions/bitmap-intersect/)

```
Find the retention of users between 2020-05-18 and 2020-05-19 under different tags.  select tag, bitmap_intersect(user_id) from (select tag, date, bitmap_union(user_id) user_id from table where date in ('2020-05-18', '2020-05-19') group by tag, date) a group by tag
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/bitmap-functions/bitmap-intersect/)

```
Who are the users retained under different tags between 2020-05-18 and 2020-05-19?  select tag, bitmap_to_string(bitmap_intersect(user_id)) from (select tag, date, bitmap_union(user_id) user_id from table where date in ('2020-05-18', '2020-05-19') group by tag, date) a group by tag
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/bitmap-functions/bitmap-intersect/)

```
Note: 1000, 20000, 30000 plastic tags represent different labels of users
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/bitmap-functions/orthogonal-bitmap-expr-calculate/)

```
Note: 'A:a/b', 'B:2-4', etc. are string types tag, representing different labels of users, where 'B:2-4' needs to be escaped as'B:2\\-4'
```

- [x] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/bitmap-functions/orthogonal-bitmap-expr-calculate/)

```
CREATE ROUTINE LOAD [db.]job_name [ON tbl_name] [merge_type] [load_properties] [job_properties] FROM data_source [data_source_properties] [COMMENT "comment"]
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
PROPERTIES (     "key1" = "val1",     "key2" = "val2" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
FROM KAFKA (     "key1" = "val1",     "key2" = "val2" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

```
CREATE ROUTINE LOAD example_db.test1 ON example_tbl COLUMNS TERMINATED BY ",", COLUMNS(k1, k2, k3, v1, v2, v3 = k1 * 100) PROPERTIES (     "desired_concurrent_number"="3",     "max_batch_interval" = "20",     "max_batch_rows" = "300000",     "max_batch_size" = "209715200",     "strict_mode" = "false" ) FROM KAFKA (     "kafka_broker_list" = "broker1:9092,broker2:9092,broker3:9092",     "kafka_topic" = "my_topic",     "property.group.id" = "xxx",     "property.client.id" = "xxx",     "property.kafka_default_offsets" = "OFFSET_BEGINNING" )
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for tracking these Doris parsing cases. All of them are now supported on master, so we can close this issue as completed.

- `CREATE ROUTINE LOAD` (including the `PROPERTIES (...)` and `FROM KAFKA (...)` clauses and the full example) is supported since #38137.
- `CANCEL MATERIALIZED VIEW TASK` is supported since #38646.
- The two `bitmap_intersect` SELECT cases are already parsed by the existing SELECT grammar, as checked above.
- The remaining unchecked items (`KeysType: AGG_KEY ...` and the two `Note: ...` lines) are descriptive text scraped from the Doris docs rather than SQL statements, so there is nothing to parse.

Closing this issue as completed. Feel free to reopen it if any Doris case still fails to parse on the latest master.
