### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31481]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
LAG(expr, offset, default) OVER (partition_by_clause order_by_clause)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-lag/)

```
WINDOW,FUNCTION,LAG
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-lag/)

```
BITXOR
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/bitwise-functions/bitxor/)

```
ALTER WORKLOAD GROUP  "rg_name" PROPERTIES (     property_list )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-WORKLOAD-GROUP/)

```
ALTER, WORKLOAD , GROUP
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-WORKLOAD-GROUP/)

```
ALTER DATABASE db_name SET DATA QUOTA quota
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE db_name RENAME new_db_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE db_name SET REPLICA QUOTA quota
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE example_db SET DATA QUOTA 10995116277760
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE example_db SET DATA QUOTA 100G
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by divyankshah** [comment]
Hi, would like to contribute to this issue. Can it be assigned?

Below is my Approach: I verified against the current Doris docs that LAG/BITXOR and most of the listed ALTER DATABASE variants (RENAME, SET DATA/REPLICA QUOTA) already parse correctly in the current grammar and are covered by existing tests. 

**The remaining gaps are:**
1) ALTER WORKLOAD GROUP "rg_name" PROPERTIES(...) where I added a new grammar rule modeled on the existing ALTER STORAGE POLICY ... PROPERTIES(...) pattern, plus the corresponding statement/segment classes and visitor logic.
2) ALTER DATABASE ... SET DATA QUOTA 100G (unit-suffixed quota values) I have wired the QUOTA clause to reuse the grammar's existing fileSizeLiteral rule (already used elsewhere for SIZE 100M-style literals) instead of a bare number, and convert the K/M/G/T suffix to bytes in the visitor.
3) Adding .sql/expected-output test cases for both and verified it end to end. 

Will open a PR shortly.

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for reporting this, and thanks @divyankshah for the follow-up work in #39333.

All the SQL cases listed in this issue are now supported on master:

- `LAG(expr, offset, default) OVER (PARTITION BY ... ORDER BY ...)` and the `LAG` keyword are covered by the window function rule in `doris/BaseRule.g4`, with the `select_window_frame_lag_doris` sql-case.
- `BITXOR` is registered as a Doris function and keyword, with the `select_bitxor` sql-case.
- `ALTER WORKLOAD GROUP ... PROPERTIES(...)` is covered by the `alterWorkloadGroup` rule added in #39333, with sql-cases and assertions in `alter-workload-group.xml`.
- `ALTER DATABASE ... SET DATA QUOTA` accepts both plain numbers (`10995116277760`) and unit-suffixed values (`100G`, `1GB`, `1P`) via the `dataQuotaValue` rule, and `ALTER DATABASE ... RENAME` / `SET REPLICA QUOTA` are covered by the existing `alterDatabase` rules, all with Doris sql-cases in `alter-database.xml`.

Since #39333 has been merged into master and the remaining cases were already covered, we are closing this issue as completed. Feel free to reopen it if any listed case still fails to parse on the latest master.
