### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31482]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
ALTER DATABASE example_db SET DATA QUOTA 200M
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE example_db RENAME example_db2
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE example_db SET REPLICA QUOTA 102400
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE example_db SET PROPERTIES("replication_allocation" = "tag.location.default:2")
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER DATABASE example_db SET PROPERTIES("replication_allocation" = "")
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
ALTER,DATABASE,RENAME
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-DATABASE/)

```
CREATE TABLE windowfunnel_test (                 `xwho` varchar(50) NULL COMMENT 'xwho',                 `xwhen` datetime COMMENT 'xwhen',                 `xwhat` int NULL COMMENT 'xwhat'                 ) DUPLICATE KEY(xwho) DISTRIBUTED BY HASH(xwho) BUCKETS 3 PROPERTIES (     "replication_num" = "1" )
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-window-funnel/)

```
INSERT into windowfunnel_test (xwho, xwhen, xwhat) values ('1', '2022-03-12 10:41:00', 1),                                                    ('1', '2022-03-12 13:28:02', 2),                                                    ('1', '2022-03-12 16:15:01', 3),                                                    ('1', '2022-03-12 19:05:04', 4)
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-window-funnel/)

```
WINDOW,FUNCTION,WINDOW_FUNNEL
```

- [x] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-window-funnel/)

```
LENGTH
```

- [x] [link](https://doris.apache.org/docs/1.2/sql-manual/sql-functions/string-functions/length/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by terrymanu** [comment]
### Result

**Review Result: Mergeable**

PR head `1f6311216e82` (local HEAD matches the GitHub head) contains three behavior clusters, all verified against official documentation and existing repository patterns, with no blocking issues found. One non-blocking suggestion: the PR title and description only cover WINDOW_FUNNEL (#31482), but the change also includes the BITMAP data type and the SHOW DATA SKEW statement fixing #31502 (that issue is already closed); consider mentioning the second part in the PR description for post-squash-merge traceability.

### Evidence

**Cluster 1: OVER clause after regular function calls (WINDOW_FUNNEL, #31482)**
- `parser/sql/engine/dialect/doris/src/main/antlr4/imports/doris/BaseRule.g4:1316` appends `overClause?` to `completeRegularFunction` inside the existing `// DORIS CHANGED` block, consistent with the PostgreSQL `funcApplication ... overClause?` precedent and Doris's own `aggregationFunction ... overClause?`; zero trunk (MySQL) file changes and branch diff markers fully preserved.
- Syntax basis: Doris 3.x official documentation defines WINDOW_FUNNEL as an aggregate function `WINDOW_FUNNEL(window, mode, timestamp, event_1...)` that can be combined with OVER as a window function (https://doris.apache.org/docs/3.x/sql-manual/sql-functions/aggregate-functions/window-funnel/). The legacy two-phase syntax from the issue links is the deprecated Doris 1.2 form; excluding it is the right call.
- `visitCompleteRegularFunction` needs no change; the `FunctionSegment` text automatically includes OVER, and the assertion shape matches the existing `select_window_partition_order_doris` case.

**Cluster 2: SHOW DATA SKEW statement (#31502)**
- The new `showDataSkew` rule in `DALStatement.g4` matches the official syntax item by item: `SHOW DATA SKEW FROM [<db_name>.]<table_name> [PARTITION (<partition_name> [, ...])]`; official example 2 is exactly the comma-separated multi-partition form (https://doris.apache.org/docs/2.1/sql-manual/sql-statements/table-and-view/data-and-status-management/SHOW-DATA-SKEW/).
- The four attributes on `DorisShowDataSkewStatement`, the coexistence of the manual `Optional<SimpleTableSegment> getTable()` with Lombok, and the `(FromTableSegment) visit(ctx.fromTable())` cast in `visitShowDataSkew` all follow the established patterns of the sibling `DorisShowQueryStatsStatement`/`visitShowIndex`.
- No adjacent-behavior regression: the `showData` alternative is unaffected (`SHOW DATA`, `SHOW DATA FROM t`, and `... ORDER BY col` all verified as passing).

**Cluster 3: BITMAP data type (#31502)**
- `dataType` gains `dataTypeName = BITMAP`; the new `BITMAP`/`SKEW` lexer rules are also added to `identifierKeywordsUnambiguous` (with the `BITMAP_UNION` precedent), all with DORIS markers; `BIT` vs `BITMAP` resolves safely by longest match.

**Tests and runtime verification (measured on the PR head)**
- 8 new sql-cases (4 `show_data_skew_*`, 1 `create_table_with_bitmap_type_doris`, 2 `select_window_funnel*`) plus the `select_length` extension to Doris; all case ids are unique, and assertion indices were re-verified character by character (including owner qualification, multiple partitions, and binary-operation parameters).
- `./mvnw -pl parser/sql/engine/dialect/doris -DskipITs -Dspotless.skip=true test` exit 0 (6/6).
- `./mvnw -pl test/it/parser -Dtest=...doris.InternalDorisParserIT test` exit 0 (1302/1302, including all new cases).
- `./mvnw -pl test/it/parser -Dtest=...mysql.InternalMySQLParserIT test` exit 0 (1901/1901, shared-resource regression).
- Direct parse probes: all four SHOW DATA SKEW forms (db-qualified, single/multiple partitions), the BITMAP CREATE TABLE statement, and the existing SHOW DATA statements pass.

### Coverage

- Reviewed candidate: PR #39522 head `1f6311216e8285da7123ed46de0692b637bb64f7`, merge-base `7bf39a9c37b`; the local triple-dot file list exactly matches the 18 files from GitHub `/pulls/39522/files`, with no related dirty working-tree changes.
- Behavior-cluster mapping: all 18 files are mapped into the three clusters above (`BaseRule.g4` belongs to clusters 1/3 and `DorisKeyword.g4` to clusters 2/3), with no churn-only files; the completion-gate ledger marked 18/18 files and passed validation.
- All three discovery lenses (root cause and behavior, blast radius and contracts, tests and runtime) plus the final convergence pass completed, with zero new findings in the convergence pass.
- Dialect family check: Doris is a branch dialect of the MySQL trunk; this PR touches no trunk files; the MariaDB branch is unaffected; the MySQL IT regression passed.
- Official documentation basis: the two Doris documentation links above; linked issues #31482 (open, whose 4 remaining checklist items are all covered by this PR: WINDOW_FUNNEL ×2 via grammar plus cases, LENGTH ×2 via case extension, INSERT via existing parsing and existing case coverage) and #31502 (closed).
- Unresolved gaps: none. CI was neither queried nor reviewed; this conclusion is a code-scope readiness judgment only.
