### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31487]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
Note: 'A:a/b', 'B:2-4', etc. are string types tag, representing different labels of users, where 'B:2-4' needs to be escaped as'B:2\\-4'
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/bitmap-functions/orthogonal-bitmap-expr-calculate-count/)

```
UCASE
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/string-functions/ucase/)

```
ALTER TABLE [database.]table alter_clause
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

```
RENAME new_table_name
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

```
RENAME ROLLUP old_rollup_name new_rollup_name
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

```
RENAME PARTITION old_partition_name new_partition_name
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

```
RENAME COLUMN old_column_name new_column_name
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

```
ALTER TABLE table1 RENAME table2
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

```
ALTER TABLE example_table RENAME ROLLUP rollup1 rollup2
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

```
ALTER TABLE example_table RENAME PARTITION p1 p2
```

- [x] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-TABLE-RENAME/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by Rahulyadav4** [comment]
Hi @iamhucong,
 this would be my first open-source contribution — I'd love to work on this issue. Could you please assign it to me? I'll start with one of the unchecked SQL cases (e.g. UCASE) and follow the procedure you outlined. 
Thank you!

**Comment by Rahulyadav4** [comment]
Hi @iamhucong 
I verified "SELECT UCASE(name) FROM t" locally. The SQL parses successfully, "visitFunctionCall()" is reached, and "assertDoesNotThrow" passes without any code changes. It appears that UCASE is already supported in the current parser implementation, so I couldn't reproduce an issue for this case.

**Comment by terrymanu** [comment]
Hi @iamhucong, all SQL cases listed in this issue are already supported on the current master, so I think we can close it as completed.

- The `ALTER TABLE ... RENAME` family (`RENAME new_table_name`, `RENAME ROLLUP a b`, `RENAME PARTITION a b`, `RENAME COLUMN a b`, and `ALTER TABLE table1 RENAME table2`) was implemented in #37537, including the grammar rules, visitor segments, and assertion cases (`alter_table_rename_table_doris`, `alter_table_rename_column_doris`, `alter_table_rename_rollup`, `alter_table_rename_partition` in `sql/supported/ddl/alter-table.xml`).
- `UCASE` is covered by the existing case `select_ucase` (`SELECT UCASE('hello')`, db-types `MySQL,Doris`), which @Rahulyadav4 also verified locally.
- `ORTHOGONAL_BITMAP_EXPR_CALCULATE_COUNT` parses through the generic function-call rule, since the Doris grammar accepts any qualified identifier as a function name; sibling bitmap-function cases such as `BITMAP_OR_COUNT` already exist, and I verified the exact SQL from the docs parses successfully on master.

I re-checked every remaining unchecked case on master and all of them parse without code changes, so there is nothing left to implement here. Thanks @Rahulyadav4 for the verification. I'll close this issue as completed; feel free to reopen if any listed SQL still fails on the latest master.
