### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31494]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
) [types: [DATE]
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
‥types: [DATE]
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
) [types: [DATE]
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
‥types: [DATE]
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE example_db.dynamic_partition (     k1 DATE,     k2 INT,     k3 SMALLINT,     v1 VARCHAR(2048),     v2 DATETIME DEFAULT "2014-02-04 15:36:00" ) DUPLICATE KEY(k1, k2, k3) PARTITION BY RANGE (k1) () DISTRIBUTED BY HASH(k2) BUCKETS 32 PROPERTIES(     "dynamic_partition.time_unit" = "DAY",     "dynamic_partition.start" = "-3",     "dynamic_partition.end" = "3",     "dynamic_partition.prefix" = "p",     "dynamic_partition.buckets" = "32" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE example_db.rolup_index_table (     event_day DATE,     siteid INT DEFAULT '10',     citycode SMALLINT,     username VARCHAR(32) DEFAULT '',     pv BIGINT SUM DEFAULT '0' ) AGGREGATE KEY(event_day, siteid, citycode, username) DISTRIBUTED BY HASH(siteid) BUCKETS 10 ROLLUP (     r1(event_day,siteid),     r2(event_day,citycode),     r3(event_day) ) PROPERTIES("replication_num" = "3")
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE example_db.table_hash (     k1 TINYINT,     k2 DECIMAL(10, 2) DEFAULT "10.5" ) DISTRIBUTED BY HASH(k1) BUCKETS 32 PROPERTIES (     "replication_allocation"="tag.location.group_a:1, tag.location.group_b:2" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE example_db.dynamic_partition (     k1 DATE,     k2 INT,     k3 SMALLINT,     v1 VARCHAR(2048),     v2 DATETIME DEFAULT "2014-02-04 15:36:00" ) PARTITION BY RANGE (k1) () DISTRIBUTED BY HASH(k2) BUCKETS 32 PROPERTIES(     "dynamic_partition.time_unit" = "DAY",     "dynamic_partition.start" = "-3",     "dynamic_partition.end" = "3",     "dynamic_partition.prefix" = "p",     "dynamic_partition.buckets" = "32",     "dynamic_partition.replication_allocation" = "tag.location.group_a:3"  )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
```sql     CREATE TABLE IF NOT EXISTS create_table_use_created_policy     (         k1 BIGINT,         k2 LARGEINT,         v1 VARCHAR(2048)     )     UNIQUE KEY(k1)     DISTRIBUTED BY HASH (k1) BUCKETS 3     PROPERTIES(         "storage_policy" = "test_create_table_use_policy",         "replication_num" = "1"     ); ```
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by ilyasahsan123** [comment]
hi @iamhucong, could you please assign this issue to me? thanks

**Comment by terrymanu** [comment]
Hi @iamhucong, all valid SQL cases in this issue are now supported on master, so this issue can be closed as completed.

Most of the unchecked items are invalid fragments produced by the web crawler (for example `) [types: [DATE]`), which are not executable SQL statements. The five real CREATE TABLE cases are all covered on master:

- `PARTITION BY RANGE (k1) ()` with an empty partition list and `DISTRIBUTED BY HASH ... PROPERTIES(...)` — supported by making the partition definition list optional inside the parentheses in `parser/sql/engine/dialect/doris/src/main/antlr4/imports/doris/DDLStatement.g4` (#39566);
- `AGGREGATE KEY ... ROLLUP (...)` — supported by the new `rollupClause` in the Doris `createTable` rule (#39566);
- `PROPERTIES("replication_allocation" = ...)` and `PROPERTIES("storage_policy" = ...)` — supported by the Doris CREATE TABLE enhancements in #39566 and #39568.

All five SQL statements from this issue were also added as Doris sql-cases with assertions in `test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml` and `test/it/parser/src/main/resources/case/ddl/create-table.xml`, and each one parses and visits successfully on current master. Thanks for reporting and for everyone's contributions.
