### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31495]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
```sql     CREATE TABLE create_table_partion_use_created_policy     (         k1 DATE,         k2 INT,         V1 VARCHAR(2048) REPLACE     ) PARTITION BY RANGE (k1) (         PARTITION p1 VALUES LESS THAN ("2022-01-01") ("storage_policy" = "test_create_table_partition_use_policy_1" ,"replication_num"="1"),         PARTITION p2 VALUES LESS THAN ("2022-02-01") ("storage_policy" = "test_create_table_partition_use_policy_2" ,"replication_num"="1")     ) DISTRIBUTED BY HASH(k2) BUCKETS 1
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
```
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE create_table_multi_partion_date     (         k1 DATE,         k2 INT,         V1 VARCHAR(20)     ) PARTITION BY RANGE (k1) (         FROM ("2000-11-14") TO ("2021-11-14") INTERVAL 1 YEAR,         FROM ("2021-11-14") TO ("2022-11-14") INTERVAL 1 MONTH,         FROM ("2022-11-14") TO ("2023-01-03") INTERVAL 1 WEEK,         FROM ("2023-01-03") TO ("2023-01-14") INTERVAL 1 DAY,         PARTITION p_20230114 VALUES [('2023-01-14'), ('2023-01-15'))     ) DISTRIBUTED BY HASH(k2) BUCKETS 1     PROPERTIES(         "replication_num" = "1"     )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE create_table_multi_partion_date_hour     (         k1 DATETIME,         k2 INT,         V1 VARCHAR(20)     ) PARTITION BY RANGE (k1) (         FROM ("2023-01-03 12") TO ("2023-01-14 22") INTERVAL 1 HOUR     ) DISTRIBUTED BY HASH(k2) BUCKETS 1     PROPERTIES(         "replication_num" = "1"     )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE create_table_multi_partion_integer     (         k1 BIGINT,         k2 INT,         V1 VARCHAR(20)     ) PARTITION BY RANGE (k1) (         FROM (1) TO (100) INTERVAL 10     ) DISTRIBUTED BY HASH(k2) BUCKETS 1     PROPERTIES(         "replication_num" = "1"     )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE example_db.table_hash (     k1 DATE,     k2 DECIMAL(10, 2) DEFAULT "10.5",     k3 CHAR(10) COMMENT "string column",     k4 INT NOT NULL DEFAULT "1" COMMENT "int column" ) COMMENT "duplicate without keys" PARTITION BY RANGE(k1) (     PARTITION p1 VALUES LESS THAN ("2020-02-01"),     PARTITION p2 VALUES LESS THAN ("2020-03-01"),     PARTITION p3 VALUES LESS THAN ("2020-04-01") ) DISTRIBUTED BY HASH(k1) BUCKETS 32 PROPERTIES (     "replication_num" = "1",     "enable_duplicate_without_keys_by_default" = "true" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE, TABLE
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
ARRAY<T> array_with_constant(n, T) ARRAY<T> array_repeat(T, n)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/1.2/sql-manual/sql-functions/array-functions/array_with_constant/)

```
STRING
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-types/Data-Types/STRING/)

```
DOUBLE l2_distance(ARRAY<T> array1, ARRAY<T> array2)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/distance-functions/l2-distance/)




## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by ealeonraz** [comment]
Hello, I'd like to work on this issue. I'll follow the process in the description: run each SQL case through the current Doris parser, leave a comment to ignore any that already parse successfully, and add grammar/visitor support plus test assert files for the ones that fail. I'll open a PR against master shortly.

**Comment by ealeonraz** [comment]
PR submitted: #39201

Status of the SQL cases in this issue:
- The storage-policy partition case, the three multi-range `FROM (...) TO (...) INTERVAL` cases (date / hour / integer), and the fixed-range `VALUES [(..), (..))` partition all failed to parse and are now supported, with SQL cases + assert cases added (`InternalDorisParserIT`: 1261 tests, 0 failures).
- The `example_db.table_hash` (duplicate without keys) case already parses successfully on current master, so per the issue guidance no code change or assert file was added for it.
- The remaining scraped fragments (`CREATE, TABLE`, the `array_with_constant`/`array_repeat`/`l2_distance` function signatures, and `STRING`) are not valid standalone SQL statements — ignoring them per the issue process.
