### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31492]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
ARRAY<T> array_filter(lambda, ARRAY<T> arr) ARRAY<T> array_filter(ARRAY<T> arr, ARRAY<Bool> filter_column)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/2.0/sql-manual/sql-functions/array-functions/array-filter/)

```
CREATE TABLE [IF NOT EXISTS] [database.]table (     column_definition_list     [, index_definition_list] ) [engine_type] [keys_type] [table_comment] [partition_info] distribution_desc [rollup_list] [properties] [extra_properties]
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
INDEX index_name (col_name) [USING INVERTED] COMMENT 'xxxxxx'
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
`ENGINE=olap`
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
DUPLICATE KEY(col1, col2), AGGREGATE KEY(k1, k2, k3), UNIQUE KEY(k1, k2)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
``` COMMENT "This is my first DORIS table" ```
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
PARTITION BY RANGE(col) (    FROM ("2000-11-14") TO ("2021-11-14") INTERVAL 1 YEAR,    FROM ("2021-11-14") TO ("2022-11-14") INTERVAL 1 MONTH,    FROM ("2022-11-14") TO ("2023-01-03") INTERVAL 1 WEEK,    FROM ("2023-01-03") TO ("2023-01-14") INTERVAL 1 DAY )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
PARTITION BY RANGE(int_col) (     FROM (1) TO (100) INTERVAL 10 )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
ROLLUP (     r1 (k1, k3, v1, v2),     r2 (k1, v1) )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

```
CREATE TABLE example_db.table_hash (     k1 TINYINT,     k2 DECIMAL(10, 2) DEFAULT "10.5",     k3 CHAR(10) COMMENT "string column",     k4 INT NOT NULL DEFAULT "1" COMMENT "int column" ) COMMENT "my first table" DISTRIBUTED BY HASH(k1) BUCKETS 32
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by darwvin-dev** [comment]
Hi, please assign this issue to me. I’d like to work on the Doris SQL parser cases listed here.

I’ll first verify which SQL cases still fail on current master, then keep the PR focused on the remaining unsupported Doris syntax and add parser assertion tests for the fixed cases.

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for reporting this. All Doris SQL cases listed in this issue now parse successfully on current master, so this issue can be closed as completed.

The four unticked cases are already covered:

- `ENGINE=olap` and the full `CREATE TABLE ... DISTRIBUTED BY HASH(k1) BUCKETS 32` example are covered by existing cases such as `create_table_with_comment_doris` and `create_table_hash_distributed_with_replication_allocation_doris` in `test/it/parser/src/main/resources/sql/supported/ddl/create-table.xml`.
- The numeric multi-range partition `PARTITION BY RANGE(int_col) (FROM (1) TO (100) INTERVAL 10)` is covered by `create_table_multi_range_partition_integer_doris` in the same file.
- `array_filter(lambda, arr)` and `array_filter(arr, filter_column)` parse without code changes: lambda expressions were added to the Doris grammar in #39523, and array functions with lambda arguments (for example `array_first(x -> x >= 3, [1.1, 2.2])`) already have passing parser cases. Per the issue description, cases that parse successfully without code changes only need a comment and no new assert file.

I will close this issue as completed. Thanks to everyone who contributed to Doris SQL parsing.
