### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31508]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
BITXOR
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-functions/bitwise-functions/bitxor/)

```
INSTR
```

- [ ] [link](https://doris.apache.org/docs/1.2/sql-manual/sql-functions/string-functions/instr/)

```
RIGHT
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/string-functions/right/)

```
EXTRACT URL PARAMETER
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/string-functions/extract-url-parameter/)

```
BITSHIFT, BITSHIFTRIGHT
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/bitwise-functions/bitshiftright/)

```
LTRIM
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/string-functions/ltrim/)

```
RANK() OVER(partition_by_clause order_by_clause)
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-rank/)

```
WINDOW,FUNCTION,RANK
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/sql-manual/sql-functions/window-functions/window-function-rank/)

```
ALTER RESOURCE 'spark0' PROPERTIES ("working_dir" = "hdfs://127.0.0.1:10000/tmp/doris_new")
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-RESOURCE/)

```
ALTER RESOURCE 'remote_s3' PROPERTIES ("s3.connection.maximum" = "100")
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-RESOURCE/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by danigiri** [comment]
I could look at this (and some of the rest of Doris issues) as part of hacktoberfest

**Comment by danigiri** [comment]
In the meantime I will look into setting up the environment and getting master to build (it doesn't)

**Comment by danigiri** [comment]
I can't get it to build in MacOS but in Linux it does build first try. I am trying to copy the generated .class files and this seems to be a workaround. 

Feel free to assign this to me, in the meantime I am giving it a try.

**Comment by danigiri** [comment]
Thank you, at the moment working on a PoC for a single operation to get the hang of it.

**Comment by iamhucong** [comment]
You are welcome. Feel free to ask if you have any questions at all.

**Comment by danigiri** [comment]
First PR ready and managed to compile doris (by increasing heap size)

**Comment by danigiri** [comment]
looking at `EXTRACT_URL_PARAMETER` next

**Comment by linghengqian** [comment]
> No worries, I have the first PR ready, but I need to try the SQL in Apache Doris to verify it. Doris requires a AVX2 CPU and I do not have that hardware available. It asks to recompile, and after 24h of CPU time using 2 cores it still has not finished :)

- I just opened https://github.com/apache/doris-operator/issues/286 by the way.

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for reporting this. All Doris SQL cases listed in this issue are now supported on the current master, so we can close it.

- `BITXOR`, `INSTR`, `STRRIGHT` (the `RIGHT` function), and `EXTRACT_URL_PARAMETER` were added by #33258, #33289, #33393 and #33571, with dedicated grammar rules and parser test cases (`select_bitxor`, `select_instr`, `select_strright`, `select_extract_url_parameter`).
- `BITSHIFTLEFT`/`BITSHIFTRIGHT` and `LTRIM` are parsed through the regular-function fallback in the Doris grammar (`regularFunctionName` accepts a plain identifier), and `LTRIM` already has a Doris test case (`select_ltrim_function`). Per the issue convention, no extra assert file is needed when a case parses without code changes.
- `RANK() OVER (PARTITION BY ... ORDER BY ...)` is covered by the window-function rule, with Doris test case `select_window_rank_doris`.
- Both `ALTER RESOURCE ... PROPERTIES (...)` statements are covered by the `alterResource` rule, with test case `alter_resource_properties`.

I verified all the above SQLs parse successfully on the latest master. Closing this issue as completed; feel free to reopen if any Doris case still fails on a current version.
