### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31509]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
ALTER RESOURCE "showPolicy_1_resource" PROPERTIES("s3.connection.maximum" = "1111")
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-RESOURCE/)

```
ALTER, RESOURCE
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-statements/Data-Definition-Statements/Alter/ALTER-RESOURCE/)

```
SELECT split_by_string('1, 2 3, 4,5, abcde', ', ')
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/string-functions/split-by-string/)

```
SUBSTR
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/string-functions/substr/)

```
BITOR
```

- [ ] [link](https://doris.apache.org/docs/1.2/sql-manual/sql-functions/bitwise-functions/bitor/)

```
ADMIN COPY TABLET tablet_id PROPERTIES("xxx")
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-COPY-TABLET/)

```
TabletId: 10020         BackendId: 10003                Ip: 192.168.10.1              Path: /path/to/be/storage/snapshot/20220830101353.2.3600 ExpirationMinutes: 60   CreateTableStmt: CREATE TABLE `tbl1` (   `k1` int(11) NULL,   `k2` int(11) NULL ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`) DISTRIBUTED BY HASH(k1) BUCKETS 1 PROPERTIES ( "replication_num" = "1", "version_info" = "2" )
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-COPY-TABLET/)

```
ADMIN COPY TABLET 10010 PROPERTIES("backend_id" = "10001")
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-COPY-TABLET/)

```
ADMIN COPY TABLET 10010 PROPERTIES("backend_id" = "10001", "version" = "10")
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-COPY-TABLET/)

```
ADMIN, COPY, TABLET
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/ADMIN-COPY-TABLET/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by samarth-jain28** [comment]
Hi, i want to work on it.

**Comment by strongduanmu** [comment]
@samarth-jain28 Welcome, I just assign this issue to you.

**Comment by danigiri** [comment]
As part of hacktoberfest, I was looking into contributing, @samarth-jain28 do you mind dividing the different tasks between us? (happy to code review PRs as well) cc @strongduanmu

**Comment by hosnaml** [comment]
@strongduanmu , @iamhucong Is it possible for me to work on this issue?

**Comment by strongduanmu** [comment]
> [@strongduanmu](https://github.com/strongduanmu) , [@iamhucong](https://github.com/iamhucong) Is it possible for me to work on this issue?

Of course, I just assign it to you

**Comment by hosnaml** [comment]
Hi,
I just wanted to mention that the links for SQL cases are broken in the issue's description.

**Comment by ccxxxyy** [comment]
@iamhucong @strongduanmu  Hi, I have a question regarding the ADMIN COPY TABLET command mentioned in the task. Since ADMIN COPY TABLET is a specialized Doris-specific administrative statement for cluster-level maintenance—such as managing Tablet/BE nodes and other OLAP-specific components—it's categorized in the official [documentation](https://doris.apache.org/zh-CN/docs/4.x/sql-manual/sql-statements/table-and-view/data-and-status-management/ADMIN-COPY-TABLET) as a system administration statement, which falls outside the standard SQL classification framework. Would you kindly let me know which G4 file under the existing path:parser/sql/engine/dialect/doris/src/main/antlr4/imports/doris  I should modify in order to add support for parsing ADMIN COPY TABLET? Thank you so much for your guidance!

**Comment by ilyasahsan123** [comment]
hi @iamhucong @strongduanmu, 

Could you please take a look at the following pull request?
https://github.com/apache/shardingsphere/pull/39056

Thanks

**Comment by javasigma** [comment]
Hi, please assign it if it is possibe, i will do my best
