### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31503]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
ALTER, SYSTEM, ADD, FOLLOWER, ALTER SYSTEM
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/2.0/sql-manual/sql-reference/Cluster-Management-Statements/ALTER-SYSTEM-ADD-FOLLOWER/)

```
Array<T> array_cum_sum(Array<T>)
```

- [x] [link](https://doris.apache.org/zh-CN/docs/2.0/sql-manual/sql-functions/array-functions/array-cum-sum/)

```
RECOVER DATABASE db_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
RECOVER TABLE [db_name.]table_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
RECOVER PARTITION partition_name FROM [db_name.]table_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
RECOVER DATABASE db_name db_id
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
RECOVER TABLE [db_name.]table_name table_id
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
RECOVER PARTITION partition_name partition_id FROM [db_name.]table_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
RECOVER DATABASE db_name AS new_db_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
RECOVER TABLE [db_name.]table_name table_id AS new_db_name
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by Yoofin** [comment]
Hi, I'd like to work on this issue.

**Comment by PDGGK** [comment]
Hi @terrymanu @iamhucong,

  I noticed this issue was recently unassigned. I'd like to work on it.

  **Background:**
  - I'm a student preparing for GSoC 2026
  - I have experience with Java and ANTLR4
  - I'm familiar with the SQL parsing workflow in ShardingSphere

  **Plan:**
  - Study Doris official documentation for ALTER SYSTEM and RECOVER statements
  - Implement ANTLR grammar rules in the Doris dialect module
  - Add visitor implementations for new statement types
  - Add test cases and run InternalDorisParserIT

  Could you please assign this issue to me? Thank you!

**Comment by SankeerthNara** [comment]
Could you assign this to me

**Comment by PDGGK** [comment]
@SankeerthNara it's yours as far as I'm concerned — please go ahead.

I asked to be assigned back in January and then never started; nothing was ever assigned and I have written no code for it. Explicitly withdrawing so my stale comment above doesn't leave you wondering whether the issue is taken. Good luck with it.

**Comment by terrymanu** [comment]
Hi @SankeerthNara, thanks for picking this up — the issue is yours.

For anyone checking the current status: this issue should stay open. Of the linked PRs, only #37552 was merged, and it covers the already checked-off `ALTER SYSTEM` item. #38660 attempted the `RECOVER` syntax but was closed without merging, because `RECOVER PARTITION ... AS <new_partition_name>` support and the matching parser IT coverage were still missing.

Still to be done on current master:

- All `RECOVER DATABASE` / `RECOVER TABLE` / `RECOVER PARTITION` variants listed in the issue; none of them are parseable today (only the unrelated `XA RECOVER` exists in the Doris grammar)
- `Array<T> array_cum_sum(Array<T>)`

Please follow the procedure in the issue description: verify the syntax against the Doris official docs and a real Doris instance first, then add the grammar rules, visitor logic, and parser IT cases. Submitting one PR per syntax group is preferred. Thanks!

**Comment by SankeerthNara** [comment]
Hi @terrymanu, still actively working this — apologies for the quiet spell. I've implemented and verified the RECOVER DATABASE/TABLE/PARTITION grammar, visitor, and parser IT cases locally (I see this scope also landed via #39512 in the meantime, referenced against #31505 — happy to defer to that implementation since it's already merged). I'm now moving on to the remaining array_cum_sum(Array<T>) item from this issue and will open a PR for that shortly.

**Comment by SankeerthNara** [comment]
Hi @terrymanu @iamhucong,

Went through the full task list on this issue and everything appears resolved now:

ALTER SYSTEM ADD/DROP FOLLOWER/OBSERVER — merged via #37552
RECOVER DATABASE/TABLE/PARTITION (all variants, with and without <id>/AS <new_name>) — merged via #39512
array_cum_sum(Array<T>) — no code changes needed. Verified by parsing all four example cases from the [official docs](https://doris.apache.org/docs/2.1/sql-manual/sql-functions/scalar-functions/array-functions/array-cum-sum/) against current master using the ANTLR grammar directly:
SELECT array_cum_sum(int_array) FROM array_cum_sum_test;
SELECT array_cum_sum(double_array) FROM array_cum_sum_test;
SELECT array_cum_sum(['a', 1, 'b', 2, 'c', 3]);
The accompanying CREATE TABLE array_cum_sum_test (...) setup statement
All four parse cleanly — array_cum_sum falls through the existing generic completeRegularFunction → regularFunctionName → identifier path, and array literals are already handled by the existing arrayExpression rule. No grammar, visitor, or test changes required (per this issue's own note: "If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file").

I don't see any remaining scope from the original task list. Would it be OK to close this one out?
