### ISSUE TITLE
Support parsing Doris sql

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#31505]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for Doris SQL parsing in ShardingSphere.

More details:
<https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/>  

## Issue Background Explanation

The current issue involves using a custom web scraping script to fetch SQL cases from the official website of a corresponding database. These SQL cases are then passed to ShardingSphere's parsing engine for analysis. For SQL cases that fail to be parsed successfully, every 3 to 5 SQL cases are grouped together as an issue.
1. Since  SQL cases are obtained through web scraping, it cannot be guaranteed that all SQL cases are correct. Please follow the following process to handle this pull request (PR).
2. Some SQL cases may have already been fixed in other PRs. For cases that can already be executed successfully, simply leave a comment to ignore them.
3. If a SQL case can be executed successfully without any code changes, there is no need to add a corresponding test assert file.  

## Task

This issue is to support more Doris sql parsing, as follows:

```
RECOVER
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Database-Administration-Statements/RECOVER/)

```
TransactionId: 4005              Label: insert_8d807d5d-bcdd-46eb-be6d-3fa87aa4952d        Coordinator: FE: 10.74.167.16  TransactionStatus: VISIBLE  LoadJobSourceType: INSERT_STREAMING        PrepareTime: 2020-01-09 14:59:07         CommitTime: 2020-01-09 14:59:09         FinishTime: 2020-01-09 14:59:09             Reason: ErrorReplicasCount: 0         ListenerId: -1          TimeoutMs: 300000
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/dev/sql-manual/sql-statements/Show-Statements/SHOW-TRANSACTION/)

```
WINDOW,FUNCTION,ROW_NUMBER
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-functions/window-functions/window-function-row-number/)

```
ELT
```

- [ ] [link](https://doris.apache.org/docs/1.2/sql-manual/sql-functions/string-functions/elt/)

```
ARRAY<T> array_shuffle(ARRAY<T> array1, [INT seed]) ARRAY<T> shuffle(ARRAY<T> array1, [INT seed])
```

- [ ] [link](https://doris.apache.org/zh-CN/docs/2.0/sql-manual/sql-functions/array-functions/array-shuffle/)

```
MySQL [(none)]> select null_or_empty(null)
```

- [ ] [link](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/string-functions/null-or-empty/)

```
BITSHIFT, BITSHIFTRIGHT
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-functions/bitwise-functions/bitshiftright/)

```
DOUBLE l2_distance(ARRAY<T> array1, ARRAY<T> array2)
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-functions/distance-functions/l2-distance/)

```
L2_DISTANCE,DISTANCE,L2,ARRAY
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-functions/distance-functions/l2-distance/)

```
LTRIM
```

- [ ] [link](https://doris.apache.org/docs/dev/sql-manual/sql-functions/string-functions/ltrim/)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by terrymanu** [comment]
Hi, I checked the remaining cases on the current master:

- `ROW_NUMBER() OVER (...)` is already supported by the existing window function rule.
- `ELT`, `LTRIM`, `null_or_empty`, `BITSHIFTLEFT/BITSHIFTRIGHT`, `array_shuffle/shuffle`, `l2_distance/DISTANCE` are regular function calls that already parse through the generic function-name rule, so no code change is needed for them (some entries are doc fragments rather than SQL).

I'll submit a PR for the remaining `RECOVER` and `SHOW TRANSACTION` statements.

**Comment by terrymanu** [comment]
Hi @iamhucong, thanks for reporting this. All cases tracked in this issue are now fully supported on the current master, so we can close it as completed.

- `RECOVER DATABASE/TABLE/PARTITION` and `SHOW TRANSACTION` were implemented in #39512 (merged into master on 2026-08-19), including grammar rules, `DorisRecoverStatement` / `DorisShowTransactionStatement`, visitors, and parser test cases.
- `ROW_NUMBER() OVER (...)` is covered by the existing window function rule, with Doris-specific sql-cases such as `select_window_partition_order_doris`.
- `ELT` and `LTRIM` already have `MySQL,Doris` sql-cases (`select_elt`, `select_ltrim_function`).
- `null_or_empty`, `BITSHIFTLEFT`/`BITSHIFTRIGHT`, `l2_distance`/`DISTANCE`, `array_shuffle`/`shuffle` are regular function calls that parse through the generic function-name rule without code changes.

I verified every case above parses successfully against the current master Doris parser. @shamilv, thanks for your interest — the remaining open PR #39505 is now redundant since #39512 covers the same `RECOVER` syntax, so I'll close it too.
