### ISSUE TITLE
Improve the parsing of methods in MySQL

### ISSUE THREAD

**Issue by TherChenYang** [apache/shardingsphere#31547]
## Background

Hi community.\
The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). 

Currently, we are planning to enhance the support for MySQL SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

## Issue Background Explanation
In the original parsing work, it may have overlooked the parsing of method parameters. For ShardingSphere, we need to pay attention to the table name or field name in method parameters. If there are issues with parsing method parameters, it will cause problems in subsequent binding and rewriting tasks.

For the verification work, we need to complete the following items.
1. Find the example SQL of this method in the official website.[Built-In Function and Operator Reference](https://dev.mysql.com/doc/refman/8.0/en/built-in-function-reference.html)
2. verify if the SQL itself can be parsed by the parser
3. Check if the parsed SQLStatement can correctly capture the parameters in the method.

## Task

```
BIN()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bin)

```
BIN_TO_UUID()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_bin-to-uuid)
```
BIT_AND()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_bit-and)
```
BIT_COUNT()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/bit-functions.html#function_bit-count)
```
BIT_LENGTH()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bit-length)
```
BIT_OR()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_bit-or)
```
BIT_XOR()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_bit-xor)
```
CAST()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast)
```
CEIL()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_ceil)
```
CEILING()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_ceiling)
```
CHAR()
```
- [ ] [link](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_char)

## Overall Procedure

If you intend to participate in fixing this issue, please feel free to leave a comment below the issue. Community members will assign the issue accordingly.  

><u>For example, you can leave a comment like this: "Hi, please assign this issue to me. Thank you!"</u>

Once you have claimed the issue, please review the syntax of the SQL on the official website of the corresponding database. Execute the SQL on the respective database to ensure the correctness of the SQL syntax.

><u>You can check the corresponding source of each SQL case on the official database website by clicking on the link provided below each case.</u> 

Next, execute the problematic SQL cases mentioned above in the database (you can quickly start the                     corresponding database using the Docker image for that database, and then connect to it using 
a client you are  familiar with), to ensure that the SQL syntax itself is correct.  

## Fixing ANTLR Grammar Parsing Issue

Once you have confirmed the correctness of the SQL syntax, you can validate and fix the grammar parsing issue in ShardingSphere. 

>If you are using IntelliJ IDEA, you will need to install the ANTLR plugin before proceeding.

If it is an ANTLR parsing error message, try to repair the `.g4` file by comparing it with the official database syntax until the SQL can be correctly parsed by ANTLR.

When there is no error message in the ANTLR Preview window, it means that ANTLR can correctly parse the SQL.  

## Visitor problem fix

After ANTLR parses SQL into an abstract syntax tree, ShardingSphere will access the abstract syntax tree through Visitor and extract the required information.
If you need to extract Segments, you need to first execute:
 ```
 mvn -T 2C clean install -DskipTests
 ```  
 Under the shardingsphere-parser module to compile the entire parser module.\
Then rewrite the corresponding visit method in SQLStatementVisitorr as needed to extract the corresponding Segment.

## Add assertion test file  

After the above SQL parsing problem is repaired, the corresponding Test needs to be added. 
The steps are as follows:
1. Add the corresponding `sql-case` in the `sql/supported` directory.
2. Add case assertions in the case directory of the `shardingsphere-test-it-parser` module.
3.  Run `org.apache.shardingsphere.test.it.sql.parser.internal.InternalSQLParserIT`\
 After SQL Parser IT runs successfully, you can submit a PR.   

## Relevant Skills

1. Master JAVA language
2. Have a basic understanding of Antlr g4 file
3. Be familiar with Doris SQLs

**Comment by AbnerHuang2** [comment]
Hi @TherChenYang , please assign this issue to me. Thank you!
