### ISSUE TITLE
Support federated query mysql LOCATE function

### ISSUE THREAD

**Issue by zihaoAK47** [apache/shardingsphere#31899]
# Background

Hi Community,

Federated queries help users perform cross-database join queries, subqueries, and aggregate queries. Currently, we plan to enhance MySQL functions in the federated query environment to support more SQL execution scenarios in federated query contexts.

For more details, please refer to: [Apache ShardingSphere Documentation on SQL Federation](https://shardingsphere.apache.org/document/current/cn/features/sql-federation/).

Function document: https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_locate

# Task

- [ ] `SELECT LOCATE(x'64', _utf8mb4'abcdef');`

Run log:
```
expected:
+-----------------------------------+
|   LOCATE(x'64', _utf8mb4'abcdef') |
+===================================+
|                                 4 |
+-----------------------------------+

actual:
SQL federation does not support SQL 'SELECT LOCATE(x'64', _utf8mb4'abcdef');\n'.\nMore details: Unsupported SQL operation: unsupported CommonExpressionSegment.
```

- [ ] `select locate("a","b",2),locate("","a",1);`

Run log:
```
expected:
+---------------------+--------------------+
|   locate("a","b",2) |   locate("","a",1) |
+=====================+====================+
|                   0 |                  1 |
+---------------------+--------------------+

actual:
SQL federation does not support SQL \'select locate("a","b",2),locate("","a",1);\n\'.\nMore details: At line 0, column 0: No match found for function signature locate(<CHARACTER>, <CHARACTER>, <NUMERIC>)
```

- [ ] `select locate('he','hello',-2);`

Run log:
```
expected:
+---------------------------+
|   locate('he','hello',-2) |
+===========================+
|                         0 |
+---------------------------+

actual:
SQL federation does not support SQL 'select locate('he','hello',-2);\n'.\nMore details: At line 0, column 0: No match found for function signature locate(<CHARACTER>, <CHARACTER>, <NUMERIC>)
```

- [ ] `select locate('he','hello'),locate('he','hello',2),locate('lo','hello',2) ;`

Run log:
```
expected:
+------------------------+--------------------------+--------------------------+
|   locate('he','hello') |   locate('he','hello',2) |   locate('lo','hello',2) |
+========================+==========================+==========================+
|                      1 |                        0 |                        4 |
+------------------------+--------------------------+--------------------------+

actual:
SQL federation does not support SQL 'select locate('he','hello'),locate('he','hello',2),locate('lo','hello',2) ;\n'.\nMore details: At line 0, column 0: No match found for function signature locate(<CHARACTER>, <CHARACTER>)

```

- [ ] TODO Test cases for nested function calls

**Comment by terrymanu** [comment]
Hi @zihaoAK47, thanks for the report. This enhancement is not planned for the open-source SQL Federation engine.

Calcite does not natively provide the complete MySQL `LOCATE(str, substr[, pos])` semantics, including the optional position argument and MySQL-specific boundary behavior. Supporting it correctly would require a ShardingSphere-specific implementation.

The MySQL SQL Federation provider now explicitly classifies `LOCATE()` as unsupported. We are closing this issue as not planned.
