### ISSUE TITLE
Support federated query mysql length function

### ISSUE THREAD

**Issue by zihaoAK47** [apache/shardingsphere#31897]
# Background

Hi Community,

Federated queries help users perform cross-database join queries, subqueries, and aggregate queries. Currently, we plan to enhance MySQL functions in the federated query environment to support more SQL execution scenarios in federated query contexts.

For more details, please refer to: [Apache ShardingSphere Documentation on SQL Federation](https://shardingsphere.apache.org/document/current/cn/features/sql-federation/).

Function document:  https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_length

# Task

- [ ]  `select length('\n\t\r\b\0\_\%\\');`

Run log:
```
expected:
+------------------------------+
|   length('\n\t\r\b\0\_\%\\') |
+==============================+
|                           10 |
+------------------------------+

actual:
SQL federation does not support SQL 'select length('\\n\\t\\r\\b\\0\\_\\%\\\\');\n'.\nMore details: At line 0, column 0: No match found for function signature length(<CHARACTER>)
```

- [ ] `select length(_latin1'\n\t\n\b\0\\_\\%\\');`

Run log:
```
expected:
+---------------------------------------+
|   length(_latin1'\n\t\n\b\0\\_\\%\\') |
+=======================================+
|                                    10 |
+---------------------------------------+

actual:
SQL federation does not support SQL 'select length(_latin1'\\n\\t\\n\\b\\0\\\\_\\\\%\\\\');\n'.\nMore details: At line 0, column 0: No match found for function signature length(<CHARACTER>)
```

- [ ] `SELECT LENGTH(code), code FROM t1 WHERE code='A12';`
- [ ] `SELECT LENGTH(code), code FROM t1 WHERE code='A12' AND LENGTH(code)=5;`

Run log:
```
CREATE TABLE t1 (code varchar(10)) charset utf8mb4;
INSERT INTO t1 VALUES ('a12'), ('A12'), ('a13');
INSERT INTO t1 VALUES (_utf16 0x0061003100320007), (_utf16 0x00410031003200070007);

SELECT LENGTH(code), code FROM t1 WHERE code='A12';
expected:
+----------------+--------+
|   LENGTH(code) | code   |
+================+========+
|              3 | a12    |
+----------------+--------+
|              3 | A12    |
+----------------+--------+
|              4 | a12   |
+----------------+--------+
|              5 | A12  |
+----------------+--------+

actual:
SQL federation does not support SQL 'SELECT LENGTH(code), code FROM t1 WHERE code='A12';\n'.\nMore details: At line 0, column 0: No match found for function signature LENGTH(<CHARACTER>)

SELECT LENGTH(code), code FROM t1 WHERE code='A12' AND LENGTH(code)=5;
expected:
+----------------+--------+
|   LENGTH(code) | code   |
+================+========+
|              5 | A12  |
+----------------+--------+

actual:
SQL federation does not support SQL 'SELECT LENGTH(code), code FROM t1 WHERE code='A12' AND LENGTH(code)=5;\n'.\nMore details: At line 0, column 0: No match found for function signature LENGTH(<CHARACTER>)
```

- [ ] TODO Test cases for nested function calls

**Comment by terrymanu** [comment]
Hi @zihaoAK47, thanks for the report. This enhancement is not planned for the open-source SQL Federation engine.

MySQL `LENGTH()` returns the length in bytes, while Calcite's native length handling follows character-length semantics. Supporting the MySQL behavior correctly would therefore require ShardingSphere-specific compatibility logic rather than relying on Calcite's native implementation.

The MySQL SQL Federation provider now explicitly classifies `LENGTH()` as unsupported. We are closing this issue as not planned.
