### ISSUE TITLE
Improve the federated query MySQL function

### ISSUE THREAD

**Issue by zihaoAK47** [apache/shardingsphere#31912]
# Background

Hi Community,

Federated queries help users perform cross-database join queries, subqueries, and aggregate queries. Currently, we plan to enhance MySQL functions in the federated query environment to support more SQL execution scenarios in federated query contexts.

For more details, please refer to: [Apache ShardingSphere Documentation on SQL Federation](https://shardingsphere.apache.org/document/current/cn/features/sql-federation/).

# Task

- [x] NOT [link](https://dev.mysql.com/doc/refman/8.4/en/logical-operators.html#operator_not)
- [x] ATAN [link](https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html#function_atan)  @zihaoAK47 
- [ ] BENCHMARK [link](https://dev.mysql.com/doc/refman/8.4/en/information-functions.html#function_benchmark)
- [ ] BIN [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_bin) @zihaoAK47 
- [ ] CRC32 [link](https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html#function_crc32)
- [ ] SUBSTRING_INDEX [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_substring-index)
- [ ] FORMAT [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_format)
- [ ] CONV [link](https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html#function_conv)
- [ ] SUBSTRING [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_substring)
- [ ] CHAR [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_char)
- [ ] ELT [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_elt)
- [ ] EXPORT_SET [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_export-set)
- [ ] FIELD [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_field)
- [ ] FIND_IN_SET [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_find-in-set)
- [ ] HEX [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_hex)
- [ ] INSERT [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_insert)
- [ ] LCASE [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_lcase)
- [ ] LOAD_FILE [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_load-file)
- [ ] LPAD [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_lpad)
- [ ] LTRIM [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_ltrim)
- [ ] MAKE_SET [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_make-set)
- [ ] MID [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_mid)
- [ ] OCT [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_oct)
- [ ] OCTET_LENGTH [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_char)
- [ ] ORD [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_ord)
- [ ] QUOTE [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_quote)
- [ ] REGEXP_INSTR [link](https://dev.mysql.com/doc/refman/8.4/en/regexp.html#function_regexp-instr)
- [ ] REGEXP_LIKE [link](https://dev.mysql.com/doc/refman/8.4/en/regexp.html#function_regexp-like)
- [ ] REGEXP_SUBSTR [link](https://dev.mysql.com/doc/refman/8.4/en/regexp.html#function_regexp-substr)
- [ ] RPAD [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_rpad)
- [ ] AES_ENCRYPT [link](https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html#function_aes-encrypt)
- [ ] AES_DECRYPT [link](https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html#function_aes-decrypt)
- [ ] RTRIM [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_rtrim)
- [ ] UNHEX [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_unhex)
- [ ] UCASE [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_ucase)
- [ ] WEIGHT_STRING [link](https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_weight-string)
- [ ] CHARSET [link](https://dev.mysql.com/doc/refman/8.4/en/information-functions.html#function_charset)
- [ ] COERCIBILITY [link](https://dev.mysql.com/doc/refman/8.4/en/information-functions.html#function_coercibility)
- [ ] FROM_UNIXTIME [link](https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html#function_from-unixtime)
- [ ] CEILING [link](https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html#function_ceiling)
- [ ] LOG [link](https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html#function_log)
- [ ] LOG2 [link](https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html#function_log2)
- [ ] POW [link](https://dev.mysql.com/doc/refman/8.4/en/mathematical-functions.html#function_pow)
- [ ] TIMEDIFF [link](https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html#function_timediff)
- [ ] LEAST [link](https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html#function_least)
- [ ] SHA [link](https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html#function_sha1)

TODO other function

**Comment by strongduanmu** [comment]
This is an exciting task that will greatly improve the compatibility of federation queries.

**Comment by terrymanu** [comment]
Hi @zihaoAK47, thanks for tracking these MySQL SQL Federation functions.

After reviewing the support boundary, we do not plan to implement the remaining functions in the open-source SQL Federation engine. They have been explicitly added to the MySQL unsupported-function list, so SQL Federation reports a consistent unsupported-operation error instead of relying on incomplete or incompatible semantics.

The already completed `NOT` and `ATAN` support remains unchanged.

We are closing this issue as not planned.
