### ISSUE TITLE
Add like support for DistSQL `show storage units`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#32387]
When a large number of storage units are registered in a logical database, it becomes difficult to find specific storage units information. We should make it support like clause, similar to `show tables` and `show dist variables`.

Reference: #25870

### Tasks
- [x] Update g4, visitor and executor
- [x] Update syntax doc
- [x] Add test cases
