### ISSUE TITLE
Parse `Top(expression)` query of SQLServer with ANTLR

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#4867]
**Content:** To support `Top(expression)` of SQLServer query SQL, the first step is to parse this grammar through Sharding-Parser.

**Difficulty Rating:**  ★★★☆☆

**Requirements:** 
    - Understand `g4 file` of `ANTLR`
    - Understand `Visitor` mechanism of `ANTLR`
    - Can modify `xml` file

**Comment by tristaZero** [comment]
### TODO list to handle this issue
- [ ] Correct the `TOP` definition in `DMLStatement.g4` of `SQLServer` referring to [DOC](https://www.sqlservertutorial.net/sql-server-basics/sql-server-select-top/).
- [ ] Add function `visitTop()` of `SQLServerDMLVisitor` to parse out `TopProjectionSegment`
- [ ] Modify `visitProjection()` of `SQLServerDMLVisitor`
- [ ] Check those sql test case[1] are correct or not. 
    * If correct, remove the comments from them, and delete the relative sentences in `isPassedSqlCase()` of `SQLParserParameterizedTest` 
    * If incorrect, revise them, and delete the relative sentences in `isPassedSqlCase()` of `SQLParserParameterizedTest` 
- [ ] Modify the corresponding parsed results in [2] to make `SQLParserParameterizedTest` run well.

[1] All the SQL cases containing `TOP` located in `./incubator-shardingsphere/sharding-sql-test/src/main/resources/sql/supported/dml/select-pagination.xml` and `./incubator-shardingsphere/sharding-sql-test/src/main/resources/sql/supported/dml/select-pagination-group-by-order-by.xml`

[2] ./incubator-shardingsphere/sharding-sql-test/src/main/resources/sql/supported

**Comment by tristaZero** [comment]
The prerequisite Issue of this one is #4885

**Comment by tristaZero** [comment]
@SteNicholas 
Hi, maybe you can try this issue. This task not easy, so it is needed that you split this issue into many little PRs, which will help reduce conflicts with others and help me review it quickly. You can refer to the todo list.

**Comment by tristaZero** [comment]
Hi, @SteNicholas  is there any progress during the past month?  I believe you are working hard on it, but my suggestion is to split this massive PR into small ones, which can make the community know how it is going. :-）

Best,
Trista

**Comment by tristaZero** [comment]
@SteNicholas Hi is there any progress?

**Comment by tristaZero** [comment]
@SteNicholas #5782 is duplicate with this one. This feature is in high demand. Hope see it finished ASAP.

**Comment by strongduanmu** [comment]
@tristaZero The 1-3 sub-tasks of this issue have been completed by @SteNicholas, and I will be responsible for the remaining three 4-6 sub-tasks.😊

**Comment by Afsalmc** [comment]
Hey still not able to use SELECT top X from tablexxx. Is this an ongoing task ?
