### ISSUE TITLE
 The task summary of SQL parse module

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5001]
Remaining todo list for SQL parse module
- [x] Parse `joinTable` Query SQL(#4885) @jingshanglu 
- [x] Support pagination (#4887) @jingshanglu 
- [x] Make subquery parsing test work well (#4696) @tristaZero 
- [x] Move predicateBuilder from `Parser module` to `Bind module`
- [x] Collate SQL grammar definitions (#4683)

**Comment by tristaZero** [comment]
@jingshanglu Hi This issue is a summary of the remaining tasks for sharding parser, which needs your hand, our veteran. :)

**Comment by SteNicholas** [comment]
@tristaZero Could u please assign some subtask to me?

**Comment by tristaZero** [comment]
Welcome @SteNicholas 
Currently, @jingshanglu is doing the first one. When it completes, two of you can process the following item parallelly. AFAIK, there is a bit of work for the first one. So let us leave him one or two days to finish.
