### ISSUE TITLE
[DISCUSS] Brand new sharding configuration API of Release 5.x

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5017]
Hi community,

Our 4.1.0 release is on the way. Moreover, I received plenty of feedback and complaints that our configuration is complicated and tedious. When trying it by myself, I convinced it is time to make some changes.
I propose to simplify the configuration API for sharding rule since release 5.x.
#### Pros
1. Through much Straightforward sharding configuration, users do not need to understand too many sharding strategies[1] for their scenarios since sharding strategies decreases from 5 to 2. The next comment will show you the initial design for new API.

2. ShardingSphere will provide many default sharding strategies for users, which means 80% of users could adopt default sharding strategies rather than write by themselves. No code, no compile, no redundant setting. 

#### Cons
1. New configuration API does not have a great compatibility across 4.x and 5.x, i.e., it is a brand new API since release 5.x (I guess it will become our argument).

Therefore, I sincerely welcome your opinion and comment to develop this proposal better and better.

[1] https://shardingsphere.apache.org/document/current/en/manual/sharding-jdbc/configuration/config-yaml/

Cheers,
Trista

**Comment by tristaZero** [comment]
Looking forward to your suggestions and comments for brand new sharding configuration API. :)
Here is the initial design for API.

**The old one**
```
shardingRule:
  tables: 
    t_order:  
      databaseStrategy: 
        standard:  
          shardingColumn:  
            preciseAlgorithmClassName: 
            rangeAlgorithmClassName: 
          complex:  
            shardingColumns:  
            algorithmClassName: 
          inline:  
            shardingColumn:  
            algorithmInlineExpression:  
          hint:  
            algorithmClassName: 
           none:  
      tableStrategy:
```
**The new one**
```
shardingRule:
  tables: 
    t_order: 
      databaseStrategy: 
        standard: 
          shardingColumn: order_id
          shardingAlgorithm:
            type: Inline
            props:
              ShardingDBVolume: 2
              ShardingTBVolume: 4
        complex: 
          shardingColumns: year, month
          shardingAlgorithm:
            type: complex
      tableStrategy:
```

**Comment by tristaZero** [comment]
### TODO
- [ ] Optimize metadata module to route none-sharding tables correctly
- [ ] New API for standard sharding strategy
- [ ] New API for complex sharding strategy
- [ ] Implement Inline algorithm for standard sharding strategy
- [ ] Implement range algorithm for standard sharding strategy
- [ ] Delete Inline sharding strategy
- [ ] Delete Hint sharding strategy
- [ ] Modify sharding config 
- [ ] Modify yaml config
- [ ] Modify springboot config
- [ ] Modify spring name config
- [ ] Modify sharding proxy config

**Comment by yu199195** [comment]
very good idea, simplified configuration.

**Comment by terrymanu** [comment]
The yaml rule file may like this:

```yaml
shardingRule:
  tables: 
    t_order: 
      databaseStrategy: 
        standard: 
          shardingColumn: order_id
          shardingAlgorithm:
            type: INLINE
            props:
              expression: t_order_$->{order_id % 8}
        standard: 
          shardingColumn: order_id
          shardingAlgorithm:
            type: CLASS
            props:
              precise-class-name: xxxx
              range-class-name: xxxx
        standard: 
          shardingColumn: order_id
          shardingAlgorithm:
            type: HASH
            props:
              sharding-count: 8
              
        complex: 
          shardingColumns: year, month
          shardingAlgorithm:
            type: complex
        hint: 
          shardingAlgorithm:
            type: hint
        None:
          shardingAlgorithm:
            type: none
      tableStrategy:
```
