### ISSUE TITLE
Optimize MetaData Center #MetaDataCenter-phase-3

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5128]
According to #4896/#5008/#5049 , we will optimize metadata center:
- [x] 1.add refresh metadata event after executing ddlstatement @yu199195  #5138
- [x] 2.add metadata center tests @menghaoranss #5142
- [x] 3.add metadata center examples @yu199195  #5143
- [x] 4.add metadata center documents to docs5.x branch #5166 
- [ ] 5.optimize metadata structure in center
- [ ] 6.optimize metadata refresh mechanism during bootstrap
- [ ] 7.optimize using eventbus instead of static metadata-center instance

**Comment by yu199195** [comment]
I will fix  1,3

**Comment by ssxlulu** [comment]
I will fix 5,6,7, and what's more, I think each one should add unit tests after coding.

**Comment by kimmking** [comment]
@yu199195 @ssxlulu 
ok，we can discuss about details here.

**Comment by menghaoranss** [comment]
Unit tests and documents may need to be continuously updated, we can give priority to process other tasks together.

**Comment by menghaoranss** [comment]
@kimmking ，about task 5, does the metadata structure in center have to be consistent with the metadata in the memory? 
I have some suggestions: 
```
configuredSchemaMetaData:
  tables:
  - columns:
    - caseSensitive: false
      dataType: 0
      generated: false
      name: id
      primaryKey: true
    name: t_order
unconfiguredSchemaMetaDataMap:
  ds_0:
    tables:
    - columns:
      - caseSensitive: false
        dataType: 0
        generated: false
        name: id
        primaryKey: true
      - caseSensitive: false
        dataType: 0
        generated: false
        name: user_id
        primaryKey: false
      - caseSensitive: false
        dataType: 0
        generated: false
        name: order_id
        primaryKey: false
      indexes:
      - name: PRIMARY
      - name: t_user_order_id_index
      - name: t_user_user_id_index
      name: t_user
```
And this is the previous config：
```
configuredSchemaMetaData:
  tables:
    t_order:
      columns:
        id:
          caseSensitive: false
          dataType: 0
          generated: false
          name: id
          primaryKey: true
unconfiguredSchemaMetaDataMap:
  ds_0:
    tables:
      t_user:
        columns:
          user_id:
            caseSensitive: false
            dataType: 0
            generated: false
            name: user_id
            primaryKey: false
          id:
            caseSensitive: false
            dataType: 0
            generated: false
            name: id
            primaryKey: true
          order_id:
            caseSensitive: false
            dataType: 0
            generated: false
            name: order_id
            primaryKey: false
        indexes:
          t_user_order_id_index:
            name: t_user_order_id_index
          t_user_user_id_index:
            name: t_user_user_id_index
          primary:
            name: PRIMARY
```

**Comment by menghaoranss** [comment]
I will process task 2 first.

**Comment by kimmking** [comment]
task 5/6/7 we should make a design before do it.

**Comment by kimmking** [comment]
optimize is pending for cluster design.

**Comment by kimmking** [comment]
I will close this issue, and sometimes create a new for optimizing.
