### ISSUE TITLE
We started the sharding-metrics module，It makes sharding-proxy have better observability.

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#5393]
## sharding-metrics
It is sharding-proxy module with observability,will be an implementation of spi, We can use
`Prometheus Metrics`, `CodaHale Metrics` or other.

## Fetrue List

- [x] Design of the new feature   #5382 

- [x]  Complete the basic Project setup, Design SPI and API .  #5382 

- [x] Check notice and license file   #5382 

- [x]  Complete  Config in Sharding-Proxy .  #5441 

- [x]  Collect metrics and xin Sharding-Proxy  #5496 

- [x] Add test cases.  #5456 #5463

- [x] Integrate third-party  UI  and show metrics.

- [x] Use asynchronous threads to optimize the writing of metrics  #5534

- [x] other optimize  #5539

**Comment by yu199195** [comment]
this is metrics process chart.
![sharding-metrics-pr](https://user-images.githubusercontent.com/9673503/80696594-30083700-8b0a-11ea-89ad-89916a87de45.png)

**Comment by yu199195** [comment]
In `Sharding-Proxy`  server.yml   we should config like it.

```yml
metrics :
    name: prometheus  //Spi type config，Currently the default imp is prometheus.（required）
    host:  127.0.0.1  //http server host, If do not fill is local IP。When your service IP address changes, it is recommended to specify, for example docker .
    port:  9190 // http server port ，if you not fill， is 9190.

props:
    proxy.metrics.enabled: true  // Turn on the metrics  switch.

```
