### ISSUE TITLE
Add clustermanagement for document

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5867]
According to our recent improvement of control panel, we should add clustermanagement for document.

- [x] Add clustermanagement menu @kimmking  #5877
- [x] Add clusterstate for cn document [1] @menghaoranss  #5987
- [x] Add heartbeat for cn document [2] @menghaoranss  #5987
- [ ] Add clusterstate for en document @wubingting  
- [ ] Add heartbeat for en document @menghaoranss 

[1] https://github.com/apache/shardingsphere/blob/master/docs/document/content/features/governance/clusterstate/clusterstate.cn.md
[2] 
https://github.com/apache/shardingsphere/blob/master/docs/document/content/features/governance/clusterstate/heartbeat.cn.md

**Comment by menghaoranss** [comment]
I will follow up the second part.
