### ISSUE TITLE
Verify dev-4.x functionality&bugfix

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#5884]
For 4.1.1 release, we will verify the dev-4.x functionality for several days. 

There are some functionality tasks:
- [x] F1.sharding-proxy+mysql+sharding/master-slave/encrypt via workshop1 case @menghaoranss
- [x] F2.sharding-ui+mysql+sharding/master-slave/encrypt via workshop1 case @menghaoranss  
- [x] F3.sharding-scaling+mysql+sharding/master-slave/encrypt via workshop1 case @menghaoranss  
- [x] F4.sharding-proxy+pgsql+sharding/master-slave/encrypt via workshop1 case @kimmking
- [x] F5.sharding-ui+pgsql+sharding/master-slave/encrypt via workshop1 case @kimmking 
- [x] F6.sharding-jdbc+mysql+sharding/master-slave/encrypt via example case @menghaoranss
- [x] F7.sharding-jdbc+pgsql+sharding/master-slave/encrypt via example case @kimmking
- [x] F8.sharding-jdbc+oracle+sharding/master-slave/encrypt via example case @yu199195 
- [x] F9.sharding-jdbc+sqlserver+sharding/master-slave/encrypt via example case @yu199195 

There are some bugfix tasks:
- [x] B1.fix scaling task NPE for mysql #5679
- [x] B2.update mysql & postgresql version for proxy #5721
- [x] B3.(Proxy) Receive error response for postgres JDBC client #5731
- [x] B4.(Proxy) Response num of update is Zero for postgres JDBC client #5733
- [x] B5.fix syntax rule of SUBSTRING and CONVERT #5754
- [x] B6.sharding-jdbc parse sql NPE in postgresql #5758
- [x] B7.fix TableMetaData load error when use oracle #5787
- [x] B8.fix ColumnSegment ClassCastException #5826

**Comment by menghaoranss** [comment]
Got it.

**Comment by kimmking** [comment]
We will fix ui bug later.
