### ISSUE TITLE
metrics, opentracing,cluster pluggable design in Sharding-Proxy

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#6250]
## Fetrue List
- [x]  metrics spi pluggable design in Sharding-Proxy.  @yu199195  #6245 

- [x] opentracing spi pluggable design in Sharding-Proxy. @yu199195  #6254 

- [x] cluster spi pluggable design in Sharding-Proxy. @menghaoranss #6280 

Please answer these questions before submitting your issue. Thanks!

**Comment by menghaoranss** [comment]
Good job, i will follow up.
