### ISSUE TITLE
[SQL Definition Collation][SQLServer]Collate the g4 files of SQL definitions

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#6478]
Hi community,

This issue is to collate the SQL definitions of SQLServer. **Therefore, we can support parsing more SQLs**. 
We need your interaction! If you 

> 1. Be familiar with `g4 file` of Antlr (The grammars are RegularExpression-like)
> 2. Understand the `SQLServer grammars`

then welcome!

### Background

**How is a SQL parsed?**
`SQL definition file` 
->(Parse to) 
`AST`
->(Visit it)  
`SQLStatment`  

### Process

1. Compare `SQL definitions` in [Oficial SQL Doc](https://docs.microsoft.com/zh-cn/sql/t-sql/queries/select-transact-sql?view=sql-server-ver15) and [ShardingSphere SQL Doc](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-sqlserver/src/main/antlr4/imports/sqlserver)
2. If there is any difference in ShardingSphere SQL Doc, please correct them referring to Official SQL Doc
3. Run `mvn install the current_file_module` 
4. Check whether there are any exceptions. If indeed, please fix them. (Especially `xxxVisitor.class`)
5. Add new corresponding SQL case in [SQL Cases](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/sql/supported) and expected parsed result in [Expected Statment XML](https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/resources/case)
6. Run [SQLParserParameterizedTest](https://github.com/apache/shardingsphere/blob/master/shardingsphere-sql-parser/shardingsphere-sql-parser-test/src/test/java/org/apache/shardingsphere/sql/parser/integrate/engine/SQLParserParameterizedTest.java) to make sure no exceptions.

### Notice
1.`Left recursion` can not work well in Antlr4, 
```
a
  : b
  | a b
  ;
b
  : a c
  ;
c
  : ...
  ;
```
you can consider the following one,
```
a
  : b*
  ;
b
  : a c
  ;
c
  : ...
  ;
```

2. [Here](https://shimo.im/docs/WrgrCt9JR3JDjq8H/read) is a Chinese version for reference.

### subtask
1、DML
  - [ ] select   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?view=sql-server-ver15)
  - [ ] insert   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/insert-transact-sql?view=sql-server-ver15)
  - [ ] update   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15)
  - [ ] delete   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/delete-transact-sql?view=sql-server-ver15)
  - [ ] merge    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15)

2、DDL-ALTER

  - [x] alter table       [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15)
  - [x] alter database    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql?view=sql-server-ver15&tabs=sqlpool)
  - [x] alter procedure   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-procedure-transact-sql?view=sql-server-ver15)
  - [x] alter function    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-function-transact-sql?view=sql-server-ver15)
  - [x] alter view        [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-view-transact-sql?view=sql-server-ver15)
  - [x] alter index       [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-index-transact-sql?view=sql-server-ver15)
  - [ ] alter schema      [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-schema-transact-sql?view=sql-server-ver15)
  - [x] alter trigger     [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-trigger-transact-sql?view=sql-server-ver15)
  - [x] alter sequence    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-sequence-transact-sql?view=sql-server-ver15)
  - [ ] alter service     [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-service-transact-sql?view=sql-server-ver15)

3、DDL-CREATE

  - [x] create table      [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15)
  - [x] create index      [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15)
  - [x] create database   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=sql-server-ver15&tabs=sqlpool)
  - [x] create function   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver15)
  - [x] create procedure  [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver15)
  - [ ] create service    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-service-transact-sql?view=sql-server-ver15)
  - [x] create view       [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-view-transact-sql?view=sql-server-ver15)
  - [x] create trigger    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15)
  - [ ] create schema     [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-schema-transact-sql?view=sql-server-ver15)
  - [x] create sequence   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-sequence-transact-sql?view=sql-server-ver15)

 4、DDL-DROP

  - [x] drop table      [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-table-transact-sql?view=sql-server-ver15)
  - [x] drop index      [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-index-transact-sql?view=sql-server-ver15)
  - [x] drop database   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-database-transact-sql?view=sql-server-ver15&tabs=sqlpool)
  - [x] drop function   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-function-transact-sql?view=sql-server-ver15)
  - [x] drop procedure  [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-procedure-transact-sql?view=sql-server-ver15)
  - [ ] drop service    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-service-transact-sql?view=sql-server-ver15)
  - [x] drop view       [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-view-transact-sql?view=sql-server-ver15)
  - [x] drop trigger    [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-trigger-transact-sql?view=sql-server-ver15)
  - [ ] drop schema     [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-schema-transact-sql?view=sql-server-ver15)
  - [x] drop sequence   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-sequence-transact-sql?view=sql-server-ver15)

5、DCL

  - [x] grant          [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-transact-sql?view=sql-server-ver15)
  - [x] revoke         [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/revoke-transact-sql?view=sql-server-ver15)
  - [x] deny           [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/deny-transact-sql?view=sql-server-ver15)
  - [x] revert         [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/revert-transact-sql?view=sql-server-ver15)
  - [x] setuser        [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/statements/setuser-transact-sql?view=sql-server-ver15)
  - [x] alter user     [offical doc](   https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-user-transact-sql?view=sql-server-ver15)
  - [x] alter role     [offical doc](   https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-role-transact-sql?view=sql-server-ver15)
  - [x] alter login    [offical doc](   https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-login-transact-sql?view=sql-server-ver15)
  - [x] create user    [offical doc](   https://docs.microsoft.com/en-us/sql/t-sql/statements/create-user-transact-sql?view=sql-server-ver15)
  - [x] create role    [offical doc](   https://docs.microsoft.com/en-us/sql/t-sql/statements/create-role-transact-sql?view=sql-server-ver15)
  - [x] create login   [offical doc](   https://docs.microsoft.com/en-us/sql/t-sql/statements/create-login-transact-sql?view=sql-server-ver15)
  - [x] drop user      [offical doc]( https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-user-transact-sql?view=sql-server-ver15)
  - [x] drop role      [offical doc]( https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-role-transact-sql?view=sql-server-ver15)
  - [x] drop login     [offical doc]( https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-login-transact-sql?view=sql-server-ver15)

6、TCL

  - [x] tranction            [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/transactions-transact-sql?view=sql-server-ver15)
  - [x] rollback tranction   [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/rollback-transaction-transact-sql?view=sql-server-ver15)
  - [x] commit tranction     [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/commit-transaction-transact-sql?view=sql-server-ver15)
  - [x] save tranction       [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/save-transaction-transact-sql?view=sql-server-ver15)
  - [x] commit work          [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/commit-work-transact-sql?view=sql-server-ver15)
  - [x] rollback work        [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/rollback-work-transact-sql?view=sql-server-ver15)

7、DAL

  - [x] explain         [offical doc](https://docs.microsoft.com/en-us/sql/t-sql/queries/explain-transact-sql?view=azure-sqldw-latest)

**Comment by dongzl** [comment]
I will do it.

**Comment by jingshanglu** [comment]
> I will do it.

@dongzl select,update,insert and delete are used more often, you can start from this `subtasks`.

**Comment by dongzl** [comment]
> > I will do it.
> 
> @dongzl select,update,insert and delete are used more often, you can start from this `subtasks`.

Hi @jingshanglu , OK, I will be familiar with the work.

**Comment by tristaZero** [comment]
Welcome @dongzl come back!
It is long-term work, so I suggest you split a huge PR into many small ones and look forward to a flow of PRs from you. :-)

**Comment by dongzl** [comment]
> Welcome @dongzl come back!
> It is long-term work, so I suggest you split a huge PR into many small ones and look forward to a flow of PRs from you. :-)

Hi @tristaZero , Thank you for your reminder, I'm not familiar with the SQL parse, I think this is a good opportunity, I will often communicate with jingshang and you about this work.

**Comment by tristaZero** [comment]
Hi @ThanoshanMV Welcome!
Could you comment something here so I can assign to U？

**Comment by ThanoshanMV** [comment]
Hi @tristaZero, I'll try this one.

**Comment by tristaZero** [comment]
Hi @jingshanglu  and @Icesource 
I saw your activities on this issue, and @ThanoshanMV still wan to be part of this one. Could you update which parts of this issue you are working on? So that we can take charge of the remaining ones.

**Comment by Icesource** [comment]
> Hi @jingshanglu and @Icesource
> I saw your activities on this issue, and @ThanoshanMV still wan to be part of this one. Could you update which parts of this issue you are working on? So that we can take charge of the remaining ones.

@tristaZero  I'm working on DDL statements. Maybe you can start with other SQL statements.

**Comment by ThanoshanMV** [comment]
Thank you @Icesource. First, I'll start with TCL and DAL.

**Comment by ThanoshanMV** [comment]
Hi @jingshanglu, @tristaZero, @Icesource

I completed TCL and DAL statements. Please refer to the submitted PRs. If there is anything to be changed, please let me know.

1. For TCL statements:

- [proofread SQLServer TCL statements](https://github.com/apache/shardingsphere/pull/12826)

2. For DAL statements:

- [Add SQLServer EXPLAIN statement](https://github.com/apache/shardingsphere/pull/13546)
- [Add SQLServer CREATE TABLE AS SELECT statement](https://github.com/apache/shardingsphere/pull/13628)
- [Add SQLServer CREATE REMOTE TABLE AS SELECT statement](https://github.com/apache/shardingsphere/pull/13709)
- [Complete SQLServer EXPLAIN statement](https://github.com/apache/shardingsphere/pull/13743)

Next, I'll try to work on DCL statements.

**Comment by giorgiozoppi** [comment]
There is a a query parser in Apache already, the name of the project is Calcite.

**Comment by ThanoshanMV** [comment]
Hi @strongduanmu. In `WITH dept_costs AS (SELECT department_name, SUM(salary) dept_total FROM departments d GROUP BY department_name) SELECT * FROM dept_costs WHERE dept_total > 304500 ORDER BY department_name` SQL statement, `SubquerySegment`'s startIndex should begin with parenthesis or from the character 'S'?

**Comment by strongduanmu** [comment]
Hi @ThanoshanMV, I don't think the startIndex of SubquerySegment should contain parentheses, it's just a simple wrapper around the select statement to identify the subquery.

**Comment by ThanoshanMV** [comment]
> Hi @ThanoshanMV, I don't think the startIndex of SubquerySegment should contain parentheses, it's just a simple wrapper around the select statement to identify the subquery.

Thank you @strongduanmu.

**Comment by zrsaber** [comment]
Hi @ThanoshanMV , I want to work on this first:

 drop schema

**Comment by ThanoshanMV** [comment]
Sure @zrsaber.

**Comment by strongduanmu** [comment]
This issue has not been finished, so I will reopen it.

**Comment by terrymanu** [comment]
Close because of staled.
