### ISSUE TITLE
Consider about structure of Orchestration&Control-Panel projects

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere#6653]
Consider about structure of Orchestration projects and Control-Panel projects.
Make a design for new structure and then refactor them.
According our disscussion about Orchestration&Control-Panel module, cluster module should be pending for the next version release, and observablity module should be an independent project, so we adjust them now.

### Phase 0--prepare 

- [x] create branch orchestration-dev for shardingsphere&shardingsphere-ui  @kimmking 

### Phase 1--adjust cluster

- [x] delete cluster in shardingsphere module @kimmking #7089
- [x] check & remove all references(jdbc/proxy/spring ns/boot) @kimmking #7089
- [x] delete cluster in all configurations @kimmking  #7089
- [x] delete cluster in shardingsphere-ui module @menghaoranss 
- [x] revise document for cluster @menghaoranss 
- [x] revise examples for cluster @menghaoranss 
- [x] check & reduction configurations of cluster in zk @menghaoranss 

### Phase 2--adjust observablity 

- [x] delete metrics module @kimmking #7100
- [x] move opentracing module to independent project observablity @kimmking #7116
- [x] delete all metrics configurations @kimmking #7100
- [x] revise document for metrics @menghaoranss
- [x] revise examples for metrics @menghaoranss 

### Phase 3--adjust orchestration

- [x] remove control-panel SPI @kimmking #7131
- [x] move orchestration module to a level 1 sub-project governance @kimmking #7139
- [x] adjust all related name for governance instead of orchestration @kimmking #7139
- [x] adjust all related docs for governance instead of orchestration @menghaoranss 
- [x] adjust all related ui for governance instead of orchestration @menghaoranss 
- [x] adjust all related examples for governance instead of orchestration @kimmking #7184
- [x] revise shardingsphere-ui for new governance registry configuration @menghaoranss 

### Phase 4 - integate with java agent

make an investigation with sw-agent for metrics @yu199195 
integration with sw-agent for metrics @yu199195 
remove all references for metrics @yu199195 

### Phase 5--adjust API&SPI

This phase will be pending for uniforming scaling & cluster configurations via an abstract configuration.

**Comment by kimmking** [comment]
According our disscussion about Orchestration&Control-Panel module, cluster module should be pending for the next version release, and observablity module should be an independent project, so we adjust them now.

### Phase 0--prepare 

- [x] create branch orchestration-dev for shardingsphere&shardingsphere-ui  @kimmking 

### Phase 1--adjust cluster

- [ ] delete cluster in shardingsphere module @kimmking 
- [ ] delete cluster in shardingsphere-ui module @menghaoranss 
- [ ] delete cluster in all configurations @kimmking 
- [ ] revise document for cluster @menghaoranss 
- [ ] revise examples for cluster @menghaoranss 

### Phase 2--adjust observablity 

- [ ] move metrics and opentracing module to independent project observablity @kimmking 
- [ ] delete all metrics configurations @menghaoranss 
- [ ] revise document for cluster @menghaoranss
- [ ] make an investigation with sw-agent for metrics @yu199195 
- [ ] integration with sw-agent for metrics @yu199195 
- [ ] remove all references for metrics @yu199195 
- [ ] revise examples for metrics @menghaoranss 

### Phase 3--adjust orchestration

- [ ] move orchestration  module to a level 1 sub-project named governance @kimmking 
- [ ] adjust all related name for governance instead of orchestration @kimmking 
- [ ] adjust all related docs for governance instead of orchestration @kimmking 
- [ ] adjust all related ui for governance instead of orchestration @menghaoranss 
- [ ] adjust all related examples for governance instead of orchestration @menghaoranss 

### Phase 4--adjust API&SPI

This phase will be pending for uniforming scaling & cluster configurations via an abstract configuration.

**Comment by terrymanu** [comment]
Cool, I think this task is the last one before 5.0.0-alpha release.

**Comment by kimmking** [comment]
@yu199195  sw-agent should be openning a new issue to track.
