### ISSUE TITLE
Usability test of ShardingSphere-Proxy

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#6690]
I'll collect the suggestion or problem here during the test.

**DDL**
- [x] Merge result of DDL is not accurate (#6684)

**DAL**
- [ ] information_schema and sys relevant SQLs can't parse or route (#6693)
- [ ] SHOW FULL COLUMNS get wrong (#6759)

**DDL**
- [x] Unsupported SQL of `CREATE TEMPORARY TABLE` (#7134)
- [x] Unsupported SQL of `CREATE TRIGGER` (#7136)
- [ ] Unsupported SQL of `CREATE PROCEDURE` and `CREATE FUNCTION` (#7137)
- [ ] Unsupported SQL of `CREATE VIEW` (#7138)
- [ ] Unsupported SQL of `RENAME TABLE` (#7967)

**Compatibility**
- [x] Navicat: No database selected (#7141)
- [ ] MySQL Workbench: Unsupported SQL of `SELECT current_user()` (#7187)
- [ ] Navicat connect error: Unknown error (#7982)
- [ ] show variables / binlog / master can only get one of the databases (#8053)

**Comment by sandynz** [comment]
Closed since testing is on progress.
