### ISSUE TITLE
Failure test cases of BaseIT for PostgreSQL

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#6872]
TODO:
- [x] Fix BaseIT.createTables:131 exception, support keyword table name for different databases (#6912)
- [x] Fix BaseIT.createDatabases:121 exception, databases not cleaned by previous BaseIT (#6912)
- [x] Current PostgreSQL login user's password is changed by DCL test (#6943)
- [x] Remove duplicated test case (https://github.com/apache/shardingsphere/pull/6962)
- [x] DQL dataset select_count_tilde_concat.xml not found cause GeneralDQLIT.assertExecuteQuery failed (#7007)
- [x] PostgreSQL dedicated column missed in t_order cause GeneralDQLIT.assertExecuteQuery failed (#7010)
- [x] Print exception context for engine (https://github.com/apache/shardingsphere/pull/7005)
- [x] Integration test of PostgreSQL failed to drop database (#7174)
- [x] LockSegment absent of PostgreSQL parser (#7200)
- [x] Unexpected SELECT DISTINCT result (#7201)
- [x] remove unexpected error log (https://github.com/apache/shardingsphere/pull/7205)
- [x] assertRows failed in PostgreSQL DML integration test (#7204)
- [x] INSERT...RETURING statement failed in PostgreSQL DML integration test (#7207)
- [x] DROP ROLE/USER throws Exception for all database types (https://github.com/apache/shardingsphere/pull/7215)
- [x] Failure test cases of DCL for PostgreSQL (https://github.com/apache/shardingsphere/pull/7224)
- [x] Failure test cases of DCL for PostgreSQL 1 (https://github.com/apache/shardingsphere/pull/7230)
- [x] [Improve Performance] remove unnecessary clear procedure (https://github.com/apache/shardingsphere/pull/7254)
- [x] [Improve Performance] concurrent truncate (https://github.com/apache/shardingsphere/pull/7300 , https://github.com/apache/shardingsphere/pull/7305)
- [x] [Improve Performance] do not close thread pool for each test (https://github.com/apache/shardingsphere/pull/7327)
- [x] [Improve Performance] use delete instead of truncate to improve performance (https://github.com/apache/shardingsphere/pull/7333)
- [x] [Improve Performance] remove connection test `SELECT 1` to improve performance (https://github.com/apache/shardingsphere/pull/7334)
- [x] [Improve Performance] concurrent insert (https://github.com/apache/shardingsphere/pull/7356)
- [x] add PostgreSQL default pwd (https://github.com/apache/shardingsphere/pull/7364)
- [x] add dataset (https://github.com/apache/shardingsphere/pull/7365)
- [x] add log for BatchIT (https://github.com/apache/shardingsphere/pull/7382)
- [x] INSERT...RETURNING test cases failed of BatchDMLIT (#7398)
- [x] Unexpected failed test cases of PostgreSQL DQL test cases (#7481)

### Which version of ShardingSphere did you use?
master branch, 5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
Integration test using PostgreSQL instead of H2. Expect real test cases could run.

### Actual behavior
BaseXyzIT @BeforeClass and @AfterClass method thrown exception.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1, env.properties:
databases=PostgreSQL
postgresql.host=127.0.0.1 (suppose your PostgreSQL is on localhost)
postgresql.password=test

2, go to shardingsphere-test-suite module

3, mvn clean install

### Example codes for reproduce this issue (such as a github link).
```
[INFO] Running org.apache.shardingsphere.dbtest.engine.dcl.GeneralDCLIT
[INFO ] 15:57:37.967 [main] o.a.s.d.e.u.IntegrateTestParameters - [INFO] ======= Test Plan =======
[INFO ] 15:57:37.979 [main] o.a.s.d.e.u.IntegrateTestParameters - [WARN] Total: 3760, Active: PostgreSQL(1664), Disabled: MySQL(416), Oracle(832), SQLServer(848)

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 39.665 s <<< FAILURE! - in org.apache.shardingsphere.dbtest.engine.dcl.GeneralDC
LIT
[ERROR] org.apache.shardingsphere.dbtest.engine.dcl.GeneralDCLIT  Time elapsed: 39.664 s  <<< ERROR!
java.lang.RuntimeException:
org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  位置：15
Caused by: org.postgresql.util.PSQLException:
ERROR: syntax error at or near "`"
  位置：15

[INFO] Running org.apache.shardingsphere.dbtest.engine.ddl.GeneralDDLIT
[INFO ] 15:58:16.790 [main] o.a.s.d.e.u.IntegrateTestParameters - [INFO] ======= Test Plan =======
[INFO ] 15:58:16.790 [main] o.a.s.d.e.u.IntegrateTestParameters - [INFO] Total: 0, Active: 0, Disabled: 0

[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in org.apache.shardingsphere.dbtest.engine.ddl.GeneralDDLIT
[INFO] Running org.apache.shardingsphere.dbtest.engine.dml.AdditionalDMLIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s - in org.apache.shardingsphere.dbtest.engine.dml.AdditionalDMLIT
[INFO] Running org.apache.shardingsphere.dbtest.engine.dml.BatchDMLIT
[INFO ] 15:58:16.816 [main] o.a.s.d.e.u.IntegrateTestParameters - [INFO] ======= Test Plan =======
[INFO ] 15:58:16.816 [main] o.a.s.d.e.u.IntegrateTestParameters - [WARN] Total: 832, Active: PostgreSQL(144), Disabled: H2(152), MySQL(240), Oracle(160)
, SQLServer(136)

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 40.144 s <<< FAILURE! - in org.apache.shardingsphere.dbtest.engine.dml.BatchDMLI
T
[ERROR] org.apache.shardingsphere.dbtest.engine.dml.BatchDMLIT  Time elapsed: 40.144 s  <<< ERROR!
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: database "db_0" already exists
Caused by: org.postgresql.util.PSQLException: ERROR: database "db_0" already exists

[INFO] Running org.apache.shardingsphere.dbtest.engine.dml.GeneralDMLIT
[INFO ] 15:58:57.066 [main] o.a.s.d.e.u.IntegrateTestParameters - [INFO] ======= Test Plan =======
[INFO ] 15:58:57.066 [main] o.a.s.d.e.u.IntegrateTestParameters - [WARN] Total: 1936, Active: PostgreSQL(336), Disabled: H2(352), MySQL(560), Oracle(368
), SQLServer(320)

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 40.279 s <<< FAILURE! - in org.apache.shardingsphere.dbtest.engine.dml.GeneralDM
LIT
[ERROR] org.apache.shardingsphere.dbtest.engine.dml.GeneralDMLIT  Time elapsed: 40.279 s  <<< ERROR!
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: database "db_0" already exists
Caused by: org.postgresql.util.PSQLException: ERROR: database "db_0" already exists

[INFO] Running org.apache.shardingsphere.dbtest.engine.dql.AdditionalDQLIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.apache.shardingsphere.dbtest.engine.dql.AdditionalDQLIT
[INFO] Running org.apache.shardingsphere.dbtest.engine.dql.GeneralDQLIT
[INFO ] 15:59:37.378 [main] o.a.s.d.e.u.IntegrateTestParameters - [INFO] ======= Test Plan =======
[INFO ] 15:59:37.378 [main] o.a.s.d.e.u.IntegrateTestParameters - [WARN] Total: 6752, Active: PostgreSQL(1328), Disabled: H2(1312), MySQL(1664), Oracle(
1232), SQLServer(1216)

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 42.819 s <<< FAILURE! - in org.apache.shardingsphere.dbtest.engine.dql.GeneralDQ
LIT
[ERROR] org.apache.shardingsphere.dbtest.engine.dql.GeneralDQLIT  Time elapsed: 42.819 s  <<< ERROR!
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: database "db_0" already exists
Caused by: org.postgresql.util.PSQLException: ERROR: database "db_0" already exists

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors: 
[ERROR]   GeneralDCLIT>BaseDCLIT.initDatabasesAndTables:100->BaseIT.createDatabasesAndTables:109->BaseIT.createTables:131 ? Runtime
[ERROR]   BatchDMLIT>BatchIT.initDatabasesAndTables:85->BaseIT.createDatabasesAndTables:107->BaseIT.createDatabases:121 ? Runtime
[ERROR]   GeneralDMLIT>BaseDMLIT.initDatabasesAndTables:68->BaseIT.createDatabasesAndTables:107->BaseIT.createDatabases:121 ? Runtime
[ERROR]   GeneralDQLIT>BaseDQLIT.insertData:68->BaseIT.createDatabasesAndTables:107->BaseIT.createDatabases:121 ? Runtime
[INFO]
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0
```

**Comment by tuohai666** [comment]
@sandynz The existing two problems have been fixed. You can go ahead now.

**Comment by sandynz** [comment]
> 
> 
> @sandynz The existing two problems have been fixed. You can go ahead now.

Ok, thanks.
