### ISSUE TITLE
Add unit test cases & study PostgreSQL wire protocol

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#6985]
The closing date for all PRs is **2020.8.27**.

Let's improve the coverage of PostgreSQL protocol up to 90%. The coverage is now much lower than MySQL.

![image](https://user-images.githubusercontent.com/24643893/90896167-c2a04f00-e3f5-11ea-969f-faacba2a810f.png)

The target module is **shardingsphere-db-protocol-postgresql**

Someone who want to participate in can simply submit a PR (at least contain all the tests of a single class), or reply this issue to tell what classes you want. 

**Any simply PR will be accepted.**

**Reference material:**
The official document: https://www.postgresql.org/docs/12/protocol.html
The famous postgres-for-the-wire: http://wulczer.org/postgres-on-the-wire.pdf

**Tips:**
Take a look at what shardingsphere-db-protocol-mysql have done will make things easier.

**TODO:**

- [x] PostgreSQLPacketCodecEngine.java  **( xbkaishui )**
- [x] PostgreSQLArrayColumnType.java  **( xbkaishui )**
- [x] PostgreSQLColumnType.java  **( xbkaishui )**
- [x] PostgreSQLErrorCode.java  **( xbkaishui )**
- [x] PostgreSQLPacket.java  **( xbkaishui )**
- [x] PostgreSQLCommandPacket.java   **( xbkaishui )**
- [x] PostgreSQLCommandPacketFactory.java  **( xbkaishui )**
- [x] PostgreSQLCommandPacketType.java  **( xbkaishui )**
- [x] PostgreSQLCommandPacketTypeLoader.java  **( xbkaishui )**
- [x] PostgreSQLUnsupportedCommandPacket.java   **( xbkaishui )**
- [x] PostgreSQLColumnDescription.java   **( xbkaishui )**
- [x] PostgreSQLRowDescriptionPacket.java   **( xbkaishui )**
- [x] BinaryStatementRegistry.java    **( xbkaishui )**
- [x] ConnectionScopeBinaryStatementRegistry.java    **( xbkaishui )**
- [x] PostgreSQLBinaryStatement.java    **( xbkaishui )**
- [x] PostgreSQLBinaryStatementParameterType.java    **( xbkaishui )**
- [x] PostgreSQLBinaryResultSetRowPacket.java   **( xbkaishui )**
- [x] PostgreSQLBindCompletePacket.java   **( xbkaishui )**
- [x] PostgreSQLComBindPacket.java   **( xbkaishui )**
- [x] PostgreSQLBinaryProtocolValue.java    **( xbkaishui )**
- [x] PostgreSQLBinaryProtocolValueFactory.java   **( xbkaishui )**
- [x] PostgreSQLDateBinaryProtocolValue.java    **( xbkaishui )**
- [x] PostgreSQLDoubleBinaryProtocolValue.java  (  **( xbkaishui )**
- [x] PostgreSQLFloatBinaryProtocolValue.java  **( cenyu00 )**
- [x] PostgreSQLInt2BinaryProtocolValue.java  **( gzdzss  )**
- [x] PostgreSQLInt4BinaryProtocolValue.java  **( gzdzss  )**
- [x] PostgreSQLInt8BinaryProtocolValue.java  **( gzdzss  )**
- [x] PostgreSQLStringBinaryProtocolValue.java  **( gzdzss  )**
- [x] PostgreSQLTimeBinaryProtocolValue.java  **( gzdzss  )**
- [x] PostgreSQLComDescribePacket.java  **( gzdzss  )**
- [x] PostgreSQLComExecutePacket.java  **( gzdzss  )**
- [x] PostgreSQLComParsePacket.java  **( gzdzss  )**
- [x] PostgreSQLParseCompletePacket.java  **( gzdzss  )**
- [x] PostgreSQLComSyncPacket.java  **( gzdzss  )**
- [x] PostgreSQLComQueryPacket.java  **( gzdzss  )**
- [x] PostgreSQLDataRowPacket.java  **( gzdzss  )**
- [x] PostgreSQLComTerminationPacket.java  **( sandynz )**
- [x] PostgreSQLCommandCompletePacket.java  **( sandynz )**
- [x] PostgreSQLErrorResponsePacket.java  **( sandynz )**
- [x] PostgreSQLReadyForQueryPacket.java  **( sandynz )**
- [x] PostgreSQLAuthenticationMD5PasswordPacket.java  **( sandynz )**
- [x] PostgreSQLAuthenticationOKPacket.java  **( sandynz )**
- [x] PostgreSQLComStartupPacket.java  **( sandynz )**
- [x] PostgreSQLParameterStatusPacket.java  **( sandynz )**
- [x] PostgreSQLPasswordMessagePacket.java  **( sandynz )**
- [x] PostgreSQLRandomGenerator.java  **( sandynz )**
- [x] PostgreSQLSSLNegativePacket.java  **( sandynz )**
- [x] PostgreSQLPacketPayload.java  **( sandynz )**

**Comment by tuohai666** [comment]
@xbkaishui @cenyu00 @sandynz 
The closing date for all PRs is 2020.8.27.
It's a little urgent. If you can't finish all of them, please response as soon as possible.

**Comment by xbkaishui** [comment]
got it.

**Comment by gzdzss** [comment]
assgin to me, thanks

**Comment by tuohai666** [comment]
@gzdzss Assigned. Please pick up files from the remain.

**Comment by gzdzss** [comment]
> @gzdzss Assigned. Please pick up files from the remain.

OK , I will be next time as soon as possible.

**Comment by tuohai666** [comment]
@gzdzss There still have tasks in the TODO list, which ones do you want?

- [ ] PostgreSQLInt2BinaryProtocolValue.java
- [ ] PostgreSQLInt4BinaryProtocolValue.java
- [ ] PostgreSQLInt8BinaryProtocolValue.java
- [ ] PostgreSQLStringBinaryProtocolValue.java
- [ ] PostgreSQLTimeBinaryProtocolValue.java
- [ ] PostgreSQLComDescribePacket.java
- [ ] PostgreSQLComExecutePacket.java
- [ ] PostgreSQLComParsePacket.java
- [ ] PostgreSQLParseCompletePacket.java
- [ ] PostgreSQLComSyncPacket.java
- [ ] PostgreSQLComQueryPacket.java
- [ ] PostgreSQLDataRowPacket.java

**Comment by gzdzss** [comment]
> @gzdzss There still have tasks in the TODO list, which ones do you want?
> 
> * [ ]  PostgreSQLInt2BinaryProtocolValue.java
> * [ ]  PostgreSQLInt4BinaryProtocolValue.java
> * [ ]  PostgreSQLInt8BinaryProtocolValue.java
> * [ ]  PostgreSQLStringBinaryProtocolValue.java
> * [ ]  PostgreSQLTimeBinaryProtocolValue.java
> * [ ]  PostgreSQLComDescribePacket.java
> * [ ]  PostgreSQLComExecutePacket.java
> * [ ]  PostgreSQLComParsePacket.java
> * [ ]  PostgreSQLParseCompletePacket.java
> * [ ]  PostgreSQLComSyncPacket.java
> * [ ]  PostgreSQLComQueryPacket.java
> * [ ]  PostgreSQLDataRowPacket.java

Can I have them all? Thanks

**Comment by tuohai666** [comment]
@gzdzss 
Of course. Assigned. 
Please note that the closing date for all PRs is **2020.8.27**.

**Comment by xbkaishui** [comment]
@tuohai666 I have finished the tests in my side,  below files are ingore for test, because those are either interfaces or normal java beans,  just let you konw 
```
PostgreSQLCommandPacket.java
PostgreSQLPacket.java
PostgreSQLBinaryStatement.java
PostgreSQLBinaryStatementParameterType.java
PostgreSQLBinaryProtocolValue.java
```

**Comment by tuohai666** [comment]
@xbkaishui Get it. Thanks.

**Comment by tuohai666** [comment]
@xbkaishui Can you have a check for these ones?

- [ ] PostgreSQLRowDescriptionPacket.java   **( xbkaishui )**
- [ ] BinaryStatementRegistry.java    **( xbkaishui )**
- [ ] ConnectionScopeBinaryStatementRegistry.java    **( xbkaishui )**

**Comment by xbkaishui** [comment]
Yes, Already in this pr https://github.com/apache/shardingsphere/pull/7049, please help to check

**Comment by tuohai666** [comment]
Got it.
