### ISSUE TITLE
Failure test cases of BaseIT for MySQL

### ISSUE THREAD

**Issue by tuohai666** [apache/shardingsphere#7181]
**TODO**

- [x] Failure test cases of DQL BaseIT for MySQL (#6603)
- [x] Failure test cases of DCL BaseIT for MySQL (#6600)
- [x] Failed to get all Tables from Predicate (#7366)

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

master branch, 5.0.0-RC1-SNAPSHOT

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Integration test using MySQL instead of H2. Expect real test cases could run.

### Actual behavior

Failure test cases refer to TODO list.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1, env.properties:
databases=MySQL
mysql.host=127.0.0.1 (suppose your MySQL is on localhost)

2, go to shardingsphere-test-suite module

3, mvn clean install
