### ISSUE TITLE
Support more databases for DataSourceConnectionUrlUtil

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#7849]
## Introduction
`DataSourceConnectionUrlUtil` is to assemble parameters of JDBC URL, e.g., password, database name, to get a complete and correct JDBC URL for the connection pool.
Presently, this class has the function to create JDBC url for `MySQL` and `PostgreSQL` databases with `connectionSegment` and `databaseType` parameters. 
Hence, this issue is to enhance `DataSourceConnectionUrlUtil` by implementing other cases of getUrl() for `Oracle`, `SQLServer` and `MariaDB`.

## Task
- [ ] Add `switch case` for `Oracle` and create the corresponding unit case in `DataSourceConnectionUrlUtilTest`
- [ ] Add `switch case` for `SQLServer` and create the corresponding unit case in `DataSourceConnectionUrlUtilTest`
- [ ] Add `switch case` for `MariaDB` and create the corresponding unit case in `DataSourceConnectionUrlUtilTest`

## Tips
1. The case of `MySQL` in `DataSourceConnectionUrlUtil` will be a good example FYI
2. The case of `assertMySQLGetUrl()` in `DataSourceConnectionUrlUtilTest` will tell you how to add unit test
3. [Contributor guidance](https://shardingsphere.apache.org/community/cn/contribute/contributor/) is for the newbie. :-)
4. You can raise three PRs for each child task one at a time or one PR for all three cases.

**Comment by cenyu00** [comment]
Hi  @tristaZero, I coming...
please  assign me , I want to challenge it。 :-)

**Comment by tristaZero** [comment]
Thanks @cenyu00, and good luck!

**Comment by cenyu00** [comment]
Hi，@tristaZero ，I submit a PR for this issues，can you review for it?  Thanks.
