### ISSUE TITLE
How to create sharing tables and single tables with the default sharing strategies

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#9614]
### Background
As you know, `default database strategy` and `default table strategy` are designed to help users configure sharing table rules efficiently. That is, users can create a sharing table without specific table rules.
However, we still have the concept of `the single table`. 
So the question is, what type of table will be created suppose there are database and table sharding strategies?

### Aims
- [ ] Suppose default database strategy` and `default table strategy` exist concurrently, a sharding table will be created for `CREATE TABLE` query request.
- [ ] Suppose either or none of default database strategy` and `default table strategy` exists, a single table will be created for `CREATE TABLE` query request.

### Tasks
- [ ] Figure out whether ShardingSphere has reached the aims above (I suppose it doesn't)
- [ ] Achieve the aims above.

### Relevant issues
#9580
**Notice**: Please close these issues once this one finishes.

**Comment by sandynz** [comment]
Some scenerios are verified, test tables : `ta` and `tb`:
- In `config-sharding.yaml`, `ta` is configured including `actualDataNodes`, `tb` is not configured, whether default database/table strategy is configured or not, sharding tables will be created for `CREATE TABLE ta (id bigint)`, single table will be created for `CREATE TABLE tb (id bigint)`

According to source code and testing, in order to create sharding tables, `actualDataNodes` will be used to decide the sharding range in routing stage, it already works. It's not necessary to do this after some discusion with developer team.
